module.exports = [
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `Patrick Blair (author)`,
        date: `1710, during or after June`,
        duration: `pp. 53-116`,
        iteration: `Vol. 27, Issue 326`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1710.0008"target="_blank">From publisher (DOI: 10.1098/rstl.1710.0008)</a></li><li><a href="https://archive.org/details/philosophicaltra2717roya/page/53/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/103108"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `H. Clements at the Half-Moon, William Innys at the Prince-Armes in St. Paul's Churchyard, and D. Brown without Temple-Bar`,
        summary: `TBA.`,
        title: `Osteographia Elephantina: Or, A full and exact Description of all the Bones of an Elephant, which died near Dundee, April the 27th, 1706. with their several Dimensions. Communicated in a letter to Dr. Hans Sloane, R. S. Secr.`,
        type: `Journal article`,
    },
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `Patrick Blair (author)`,
        date: `1710, during or after September`,
        duration: `pp. 117-168`,
        iteration: `Vol. 27, Issue 327`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1710.0009"target="_blank">From publisher (DOI: 10.1098/rstl.1710.0009)</a></li><li><a href="https://archive.org/details/philosophicaltra2717roya/page/117/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/103109"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `H. Clements at the Half-Moon, William Innys at the Prince-Armes in St. Paul's Churchyard, and D. Brown at the Black Swan without Temple-Bar`,
        summary: `TBA.`,
        title: `A Continuation of the Osteographia Elephantina: Or, a Description of the Bones of an Elephant, which died near Dundee, April the 27th, 1706.`,
        type: `Journal article`,
    },
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `Anthony van Leeuwenhoek (author)`,
        date: `December 1712`,
        duration: `pp. 518-522`,
        iteration: `Vol. 27, Issue 336`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1710.0062"target="_blank">From publisher (DOI: 10.1098/rstl.1710.0062)</a></li><li><a href="https://archive.org/details/philosophicaltra2717roya/page/518/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/103162"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `H. Clements at the Half-Moon, William Innys at the Prince-Armes in St. Paul's Churchyard, and D. Brown without Temple-Bar`,
        summary: `TBA.`,
        title: `I. Some Remarks upon the Disposition of the Parts, and Microscopical Observations upon the Contexture of the Skin of Elephants.`,
        type: `Journal article`,
    },
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `Hans Sloane (author)`,
        date: `1728, during or after September`,
        duration: `pp. 457-471`,
        iteration: `Vol. 35, Issue 403`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1727.0042"target="_blank">From publisher (DOI: 10.1098/rstl.1727.0042)</a></li><li><a href="https://archive.org/details/philosophicaltra3517roya/page/457/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/103702"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `William Innys`,
        summary: `TBA.`,
        title: `I. An Account of Elephants Teeth and Bones found under Ground.`,
        type: `Journal article`,

    },
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `John Philip Breyne (author)`,
        date: `1739`,
        duration: `pp. 124-125`,
        iteration: `Vol. 40, Issue 446`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1737.0026"target="_blank">From publisher (DOI: 10.1098/rstl.1737.0026)</a></li><li><a href="https://archive.org/details/philosophicaltra4017roya/page/124/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/103902"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `T. Woodward at the Half-Moon, between the Temple-Gates, in Fleetstreet and C. Davis in Paternoster-row, next Warwick-lane`,
        summary: `TBA.`,
        title: `VIII. A Letter From John Phil. Breyne, M. D. F. R. S. To Sir Hans Sloane, Bart. Pres. R. S. with Observations, and a Description of some Mammoth's Bones dug up in Siberia, proving them to have belonged to Elephants.`,
        type: `Journal article`,
    },
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `John Philip Breyne (author)`,
        date: `1739`,
        duration: `pp. 125-130`,
        iteration: `Vol. 40, Issue 446`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1737.0026"target="_blank">From publisher (DOI: 10.1098/rstl.1737.0026)</a></li><li><a href="https://archive.org/details/philosophicaltra4017roya/page/125/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/103902"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `T. Woodward at the Half-Moon, between the Temple-Gates, in Fleetstreet and C. Davis in Paternoster-row, next Warwick-lane`,
        summary: `TBA.`,
        title: `Observations on the Mammoth's Bones and Teeth found in Siberia: Read in a Meeting of some learned Gentlemen at Dantzick in the Year 1728.`,
        type: `Journal article`,
    },
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `Michael Wolochowicz (author); T.S. (Latin-to-English translator)`,
        date: `1739`,
        duration: `pp. 130-138`,
        iteration: `Vol. 40, Issue 446`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1737.0026"target="_blank">From publisher (DOI: 10.1098/rstl.1737.0026)</a></li><li><a href="https://archive.org/details/philosophicaltra4017roya/page/130/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/103902"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `T. Woodward at the Half-Moon, between the Temple-Gates, in Fleetstreet and C. Davis in Paternoster-row, next Warwick-lane`,
        summary: `TBA.`,
        title: `An Explanation of the Draughts of the above-mention’d Antediluvian Bones of an Animal commonly called, The Mammoth of Siberia; or of the Bones of the fossile Skeleton of an Elephant; done to the antient Roman Scale contracted, and exhibited in six Figures.`,
        type: `Journal article`,
    },
    {
        contributors: `Carolus Linnaeus (author)`,
        date: `1758`,
        duration: `823 pp.`,
        eyedee: `Linnaeus_1758`,
        iteration: `10th ed., Tome 1`,
        languages: `Latin`,
        links: `<li><a href="https://www.digitale-sammlungen.de/en/view/bsb10076014?page=40,41"target="_blank">From Munich DigitiZation Center</a> (<a href="https://web.archive.org/web/20210207005415/https://download.digitale-sammlungen.de/pdf/16126589828888bsb10076014.pdf"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://gdz.sub.uni-goettingen.de/id/PPN362053006?tify={%22pages%22:[37],%22view%22:%22info%22}"target="_blank">From Göttinger Digitalisierungszentrum</a></li><li><a href="https://archive.org/details/mobot31753000798865/page/33/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Missouri Botanical Garden</li>`,
        location: `Stockholm, Sweden`,
        publisher: `Laurentius Salvius`,
        summary: `Linnaeus establishes a zoological classification system in which each animal is given a two-part (binomial) name consisting of a genus followed by a species within that genus. Similar species are grouped into genera, similar genera into orders, similar orders into classes, and similar classes into kingdoms. On page 33, Linnaeus lists distinguishing characteristics of elephants and classifies them as a single genus and species, <i>Elephas maximus</i>, in the order Bruta, the class Mammalia, and the kingdom Animalia.`,
        title: `Systema Naturae per Regna Tria Naturae Secundum Classes, Ordines, Genera, Species, Cum Characteribus, Differentiis, Synonymis, Locis.`,
        type: `Book`,
    },
    {
        container: `<i>Philosophical Transactions</i> (<i>Philos</i>. <i>Trans</i>.), journal`,
        contributors: `William Hunter (author)`,
        date: `1769, on or after 15 June`,
        duration: `pp. 34-45`,
        iteration: `Vol. 58`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1768.0005"target="_blank">From publisher (DOI: 10.1098/rstl.1768.0005)</a></li><li><a href="https://archive.org/details/philosophicaltra5817roya/page/34/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/105753"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `L. Davis and C. Reymers`,
        summary: `TBA.`,
        title: `V. Observations on the Bones, commonly supposed to Be Elephants Bones, which have been found near the River Ohio in America`,
        type: `Journal article`,
    },
    {
        contributors: `Thomas Pennant (author); M. Griffith (engraver); R. Murray (engraver); P. Mazell (engraver)`,
        date: `1771, on or after 20 March`,
        duration: `382 pp.`,
        languages: `English`,
        links: `<li><a href="http://access.bl.uk/item/viewer/ark:/81055/vdc_100027396455.0x000001#?c=0&m=0&s=0&cv=142&xywh=-1090%2C-1%2C5304%2C2659"target="_blank">From the British Library</a></li><li><a href="https://www.google.com/books/edition/Synopsis_of_Quadrupeds/cK5gAAAAcAAJ?hl=en&gbpv=1&pg=PA85"target="_blank">From Google Books</a>, copy provided by the British Library (<a href="https://web.archive.org/web/20220622141614/https://books.googleusercontent.com/books/content?req=AKW5Qadsltkxv_5-tvr_n5lCaPWFp-3mLdgR8bqlJtyD7A30GfWwWz8COIHwdq_6-MQkrBuuUl9flS0KoDQXm4v6e6Q2ba6qskR7T6FnYHWxNlmPSJmkSY_tfobJItRNdr11p8ovsabO02_WGf1MMs8eirjdZ7GNzrOTYtuN3JgNZNlkEjXEyeN1lwhRb4jtq4A1mJf0n8cuXrusZ-qYWy8G6LneMu5LFTyDWF1HHv5lA8L5V0ihfamUzEKeL7OtPT6bVTdk7gUKyEvSCI21lvgTMcoX6blwrA"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://archive.org/details/synopsisofquadru00penn/page/85/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li>`,
        location: `Chester, England`,
        publisher: `J. Monk`,
        summary: `The section on elephants, "XIV. Elephant.", is on pages 85-93.  Details TBA.`,
        title: `Synopsis of Quadrupeds`,
        type: `Book`,
    },
    {
        contributors: `Carolus Linnaeus (co-author); Johann Fridrich Gmelin (co-author)`,
        date: `1788, on or after 16 March`,
        duration: `500 pp.`,
        eyedee: `Linnaeus_Gmelin_1788`,
        iteration: `13th ed., Tome 1`,
        languages: `Latin`,
        links: `<li><a href="https://archive.org/details/mobot31753000801537/page/58/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Missouri Botanical Garden</li><li><a href="https://archive.org/details/carolilinnsys01linn/page/58/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by North Carolina State University Libraries</li>`,
        location: `Leizpig, Germany`,
        publisher: `Georg. Emmanuel Beer`,
        summary: `The 13th edition of <a id="Linnaeus_1758_color_0" onclick="goToSource('D1700-1799','Linnaeus_1758', this.id)">Linnaeus, 1758</a> with additions from Johann Fridrich Gmelin.  The section on elephants has been expanded but retains most of the 10th edition's original description, and can be found on pages 58-59.`,
        title: `Systema Naturae per Regna Tria Naturae Secundum Classes, Ordines, Genera, Species, Cum Characteribus, Differentiis, Synonymis, Locis.`,
        type: `Book`,
    },
    {
        contributors: `Robert Kerr (author), Johann Fridrich Gmelin (preface author); J. Archer (engraver)`,
        date: `1792, during or after February`,
        duration: `644 pp.`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/animalkingdomorz00linn/page/115/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li>`,
        location: `Edinburgh, Scotland`,
        publisher: `A. Strahan and T. Cadell in London, and W. Creech in Edinburgh`,
        summary: `The section on elephants, "XI. Elephant‒10. Elephas. 5.", is on pages 115-117. Details TBA.`,
        title: `The Animal Kingdom, or Zoological System, of the Celebrated Sir Charles Linnaeus. Class I. Mammalia `,
        type: `Book`,
    },
    {
        contributors: `Johann Friedrich Blumenbach (author)`,
        date: `1797, on or after 20 March`,
        duration: `714 pp.`,
        eyedee: `Blumenbach_1797`,
        iteration: `5th ed.`,
        languages: `German, Latin`,
        links: `<li><a href="http://access.bl.uk/item/viewer/ark:/81055/vdc_100027397547.0x000001#?c=0&m=0&s=0&cv=147&xywh=-1344%2C-127%2C5158%2C2535"target="_blank">From the British Library</a></li><li><a href="https://www.deutschestextarchiv.de/book/view/blumenbach_naturgeschichte_1797?p=146"target="_blank">From Deutsches Textarchiv</a></li><li><a href="https://blumenbach-online.de/fileadmin/wikiuser/Daten_Digitalisierung/ID%2000026/00026.pdf"target="_blank">From Johann Friedrich Blumenbach – Online</a></li><li><a href="https://blumenbach-online.de/fileadmin/wikiuser/Daten_Digitalisierung/ID%2000038/00038.pdf"target="_blank">From Johann Friedrich Blumenbach – Online</a></li><li><a href="https://www.digitale-sammlungen.de/en/view/bsb10074883?page=148,149"target="_blank">From Munich DigitiZation Center</a> (<a href="https://web.archive.org/web/20210207011419/https://download.digitale-sammlungen.de/pdf/16126596538888bsb10074883.pdf"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://www.digitale-sammlungen.de/en/view/bsb11112082?page=142,143"target="_blank">From Munich DigitiZation Center</a> (<a href="https://web.archive.org/web/20210207011638/https://download.digitale-sammlungen.de/pdf/16126599738888bsb11112082.pdf"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://www.digitale-sammlungen.de/en/view/bsb11271835?page=146,147"target="_blank">From Munich DigitiZation Center</a> (<a href="https://web.archive.org/web/20210207011458/https://download.digitale-sammlungen.de/pdf/16126597818888bsb11271835.pdf"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://www.google.com/books/edition/Handbuch_der_Naturgeschichte/c4g5AAAAcAAJ?hl=en&gbpv=1&pg=PA124"target="_blank">From Google Books</a>, copy provided by the Bavarian State Library (<a href="https://web.archive.org/web/20210207161402/https://books.googleusercontent.com/books/content?req=AKW5Qae5HmmtQeVus5uQJRzeuTVfw17qZB9b6zEByrLwdDTBi2D_zmnmyg3Q9P5iuGAEz426xOgn1CeZuLmdg7efp_HzPSXoGIdqiLVnFdD7uDEagC5dZVoMYifJtn8JPlOGiBi8d96-0HdXcyxXMjF7FkKx6pz8AcXVnaQfSvKNN__TRgR3_r_TdmhOnQy6-9kBPZH_hKbFM-v_Tam_yLWkaJDG-7-XcL4JYFUHX57lVF5z0O8VTFavnKaAWXO8BGuOnKqwWdW7CKHeI2cqcsiFsFHs-Z8QyA"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://www.google.com/books/edition/D_Joh_Fr_Blumenbachs_Handbuch_der_Naturg/d5dlAAAAcAAJ?hl=en&gbpv=1&pg=PA124"target="_blank">From Google Books</a>, copy provided by the Bavarian State Library (<a href="https://web.archive.org/web/20210207161809/https://books.googleusercontent.com/books/content?req=AKW5Qac42eZ_lX1QQ1nrFIwgtJlbjNpkClqTHU5cpAqlGNpovwSsS71MFIVNZQ_YjcrHA5Wh8IdRpxdlopejNK2xfO80rWUxiVKqsSF-Pn4qSj_3yiZa0sPtpVvSajNGlX-U7-_DuvWmoGrnlnfBAXV51O5ArKnInLmIFGyWpIzhzt47WscOzI_g6o1RNtVzcLvFtJFAkswBI6T4QdUGKjuf85FjvpYUKApw4MV-lneuMqwpPKrSLOWhJqW7XsXvdeZC0uH3YoNBegoZ7cV-dWQRFv1EnFYNREvdqNjDqMbbH7p8rEQvRn8"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://www.google.com/books/edition/Handbuch_der_Naturgeschichte/xTZcAAAAcAAJ?hl=en&gbpv=1&pg=PA124"target="_blank">From Google Books</a>, copy provided by the Bavarian State Library (<a href="https://web.archive.org/web/20210207162329/https://books.googleusercontent.com/books/content?req=AKW5Qae40lEcE9cWPn5gETbzSol6VGbpbBJLhIrnV9bsTANoMldU-zmaojHifTPkxmeKNaPwnEMlLDOdPNzvlo8uu6CNAnflq6N89Tha21PqcF6l20OnIreDaVORXZGOXJJQU9B66ThAlQ8-VsZlJxN5P57T7jjDiuDnOqlFHqXv9gcJ1S-EUiOLZxxeBBvHIKJBeh7jdbgKzT9hsix0e2qHpo-tF2LdWsLHSmtxE1Yl9j8CHjZHOijSKgvG3A-FOOsTyIrEGU3VK_8pJseheksfyO_jHddiuA"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://www.google.com/books/edition/D_Joh_Friedr_Blumenbachs_Handbuch_der_Na/xaxgAAAAcAAJ?hl=en&gbpv=1&pg=PA124"target="_blank">From Google Books</a>, copy provided by the British Library (<a href="https://web.archive.org/web/20210207163638/https://books.googleusercontent.com/books/content?req=AKW5QafTV_Mr9vnGqXUzzutnF21c2L-72y2P80CZ7Zaw2h_LMjjxhqc2PfY87gORmI371m46nnVmFK8xcd32BLNijlbhu4BOLVFm9sXGUiB5-v1QzdYaWymC6T6S5Zbepn7Sh2M8qDYbk0SdZzGW7lfpba1A9IAL4GbhB0XakJkbrrEhIZknGnYoVmAc_99xKP9AwqQyCH4ifR5kwC_BKYKLmwAYzR-SwdhukXf-eHXra0uHim6qiPxHC7EhYEVZU01kKU3_ptfzAcWzCTLEJpn0J0TocWudcc24OshJQyy3Dde6-KzCbw4"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://archive.org/details/djohfrblumenbach00blum/page/124/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li>`,
        location: `Göttingen, Germany`,
        notes: `<li>Bottommost copy from Johann Friedrich Blumenbach – Online was owned by Blumenbach.</li>`,
        publisher: `Johann Christian Dieterich`,
        summary: `Blumenbach recognizes two species of living elephants and describes them on pages 124-125. He gives each a distinct name, <i>Elephas asiaticus</i> for the Asian elephant and <i>E</i>. <i>africanus</i> for the African elephant, and places them in the order Belluae.`,
        title: `Handbuch der Naturgeschichte.`,
        type: `Book`,
    },
    {
        contributors: `Georges Léopold Chrétien Frédéric Dagobert Cuvier (author)`,
        date: `1798`,
        duration: `710 pp.`,
        eyedee: `Cuvier_1798`,
        languages: `French`,
        links: `<li><a href="https://archive.org/details/tableaulment00cuvi/page/146/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li><li><a href="https://archive.org/details/tableaulmen00cuvi/page/146/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Toronto</li>`,
        location: `Paris, France`,
        notes: `<li>Published in year 6 of the French Republican calendar, which was established in 1793. The first year of the calendar began on September 22, 1792, meaning year 6 corresponds to 1798 (Convention nationale, 1793).</li>`,
        publisher: `Baudouin`,
        references: `<ul class="refs">Convention nationale (1793). <a href="https://tolosana.univ-toulouse.fr/fr/notice/042658012"target="_blank"><i>Calendrier de la République française</i></a>. Paris: Imprimerie nationale France.</ul>`,
        summary: `Cuvier recognizes two species of living elephants and describes them on pages 146-149. He gives each a distinct name, <i>Elephas indicus</i> for the Asian elephant and <i>E</i>. <i>capensis</i> for the African elephant, and states that elephants warrant placement in a new, unnamed order.`,
        title: `Tableau Élémentaire de l'Histoire Naturelle des Animaux.`,
        type: `Book`,
    },
    {
        container: `<i>Philosophical Transactions of the Royal Society of London</i> (<i>Philos</i>. <i>Trans</i>. <i>R</i>. <i>Soc</i>. <i>Lond</i>.), journal`,
        contributors: `John Corse (author)`,
        date: `1799, on or after 13 June`,
        duration: `pp. 205-236`,
        iteration: `[Vol. 89], Part 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1799.0014"target="_blank">From publisher (DOI: 10.1098/rstl.1799.0014)</a></li><li><a href="https://archive.org/details/philosophicaltra8917roya/page/205/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/107034"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `W. Bulmer & Co.`,
        summary: `TBA.`,
        title: `XIII. Observations on the different Species of Asiatic Elephants, and their Mode of Dentition.`,
        type: `Journal article`,
    },
    {
        container: `<i>Philosophical Transactions of the Royal Society of London</i> (<i>Philos</i>. <i>Trans</i>. <i>R</i>. <i>Soc</i>. <i>Lond</i>.), journal`,
        contributors: `Everard Home (author)`,
        date: `1799, on or after 13 June`,
        duration: `pp. 237-258`,
        iteration: `[Vol. 89], Part 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rstl.1799.0015"target="_blank">From publisher (DOI: 10.1098/rstl.1799.0015)</a></li><li><a href="https://archive.org/details/philosophicaltra8917roya/page/237/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London</li><li><a href="https://www.jstor.org/stable/107035"target="_blank">From JSTOR</a></li>`,
        location: `London, England`,
        publisher: `W. Bulmer & Co.`,
        summary: `TBA.`,
        title: `XIV. Some Observations on the Structure of the Teeth of graminivorous Quadrupeds; particularly those of the Elephant and <i>Sus Æthiopicus</i>.`,
        type: `Journal article`,
    },
]