module.exports = [
    {
        contributors: `Carolus Linnaeus (co-author); Johann Fridrich Gmelin (co-author); William Turton (Latin-to-English translator)`,
        date: `1802`,
        duration: `943 pp.`,
        iteration: `Vol. 1`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/generalsystemofn01linn/page/35/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by NCSU Libraries`,
        location: `London, England`,
        publisher: `Printed for Lackington, Allen, and Co.`,
        summary: `An English translation of <a id="Linnaeus_Gmelin_1788_color_0" onclick="goToSource('D1700-1799','Linnaeus_Gmelin_1788', this.id)">Linnaeus and Gmelin, 1788</a>. The section on elephants is on page 35.`,
        title: `A General System of Nature, Through the Three Grand Kingdoms of Animals, Vegetables, and Minerals; Systematically Divided Into Their Several Classes, Orders, Genera, Species, and Varieties With Their Habitations, Manners, Economy, Structure, and Peculiarities.`,
        type: `Print book`,
    },
    {
        contributors: `Pierre Camper (author); A.G. Camper (address author)`,
        date: `1802, on or after 18 August`,
        duration: `108 pp.`,
        languages: `French`,
        links: `<li><a href="https://archive.org/details/Descriptionanat00Camp/page/iii/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Harvard University Ernst Mayr Library of the Museum of Comparative Zoology`,
        location: `Paris, France`,
        publisher: `H.J. Jansen`,
        summary: `TBA.`,
        title: `Description Anatomique d'un Éléphant Mâle`,
        type: `Print book`,
    },
    {
        contributors: `Carolus D. Illiger (author)`,
        date: `1811, during or after April`,
        duration: `301 pp.`,
        eyedee: `Illiger_1811`,
        languages: `Latin, German`,
        links: `<li><a href="https://www.google.com/books/edition/Caroli_Illigeri_Prodromus_systematis_mam/I9sTAAAAQAAJ?hl=en&gbpv=1&pg=PA96"target="_blank">From Google Books</a>, copy provided by the University of Lausanne (<a href="https://web.archive.org/web/20210207194027/https://books.googleusercontent.com/books/content?req=AKW5QafwELHoIks7C7v9mhRGi72Z-wnh8YtKwbaxS_o9fMZE1s6oYqv9IfcH_toSZgboSp5N8klmAU8CccxPf6aynZghdE1E-1uYF-tqwl1lssWLExJk5brRnT5vsBnalC4BLMmGEMwfPgrbT-0qWeGb6IKrCHmAeosA1irCmqsP6OHBmsRLEuz532tVe5cf0V2UEGNmdWtF4_w_rcQjIQFrX9yaVq8-pFl8ZR63z7VMfp765frU-H2X0tSEYs6hWUMbIE6oX_pW8GkLWcweonsMPhcdRnLObTUc16yXTHRnsQ1eGQJQkDs"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/Prodomus_systematis_mammalium_et_avium_a/Jt6dlbVCOqYC?hl=en&gbpv=1&pg=PA96"target="_blank">From Google Books</a>, copy provided by the University of Turin (<a href="https://web.archive.org/web/20210207194345/https://books.googleusercontent.com/books/content?req=AKW5QaeD7j4eCMVHstHMO9iiZQBU1oMcKNfmTmcvXSUDxBQmdNK0_NJrlkNWUt8bE7fn24u5SOo43X8O0lItrdxyhb2nugAYkYfazYuk_xtrn5aBAP5eHvaYMw9zJX9xDW0PtO9sHw_Xmncp34Ft0i-qnDuW8K4BWyLsI0OOcgBDQqdK5qIKAV6gsGhpVB4v-Y8RWgXYektYFd2bBNLFgzMVb9aPqaTznucpecOilbVxdLddNPrfZoaBAtwidCK8xldzYIk9Gji7497Mv5lce91lE-k8puJ49g"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/b21304397/page/96/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the King's College London Foyle Special Collections Library<li><a href="https://archive.org/details/caroliilligerida00illi/page/96/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `Berlin, Germany`,
        publisher: `C. Salfeld`,
        summary: `Illiger employs <a id="Cuvier_1798_color_0" onclick="goToSource('D1700-1799','Cuvier_1798', this.id)">Cuvier's</a> <i>Elephas indicus</i> for the Asian elephant and <a id="Blumenbach_1797_color_0" onclick="goToSource('D1700-1799','Blumenbach_1797', this.id)">Blumenbach's</a> <i>E</i>. <i>africanus</i> for the African elephant, and on page 96 proposes the name Proboscidea for the family encompassing both.`,
        title: `Prodromus Systematis Mammalium et Avium Additis Terminis Zoographicis Utriusque Classis, Eorumque Versione Germanica.`,
        type: `Print book`,
    },
    {
        container: `<i>The London Medical Repository</i> (<i>Lond</i>. <i>Med</i>. <i>Repos</i>.), print journal`,
        contributors: `John Edward Gray (author)`,
        date: `1 April 1821`,
        duration: `pp. 296-310`,
        iteration: `Vol. 15, No. 88`,
        languages: `English`,
        links: `<li><a href="https://www.google.com/books/edition/The_London_Medical_Repository/igICAAAAYAAJ?hl=en&gbpv=1&pg=PA296"target="_blank">From Google Books</a>, copy provided by Harvard University (<a href="https://web.archive.org/web/20210310040408/https://books.googleusercontent.com/books/content?req=AKW5QaeJwQcNll8IhatcydCwSlIbxPshx17_ovGPEIlnQAmPjdyASisq1zsD47IOal98Hnk1OX9VJ3emnUq5vNHdm5IH7Ac-Sh1HcUKoEAX1Mgt_7N3sXmLzlqBf0tT5K17USf5t8QjvaNb3nvndPajQyxGlwjJwuCQpLZJYk4jdvVu0O3u4RnqwqQnGwS1Hyq3y_aBAV7c8IuBd0qFLz_1_c9drt78tMMfwsetBE2AhOZp72NtuJIKQMBZFjNaAxZYfCzMzLbM3Sp4KkeVG7qqNkVgstjO9Pg"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/s0id11783780/page/296/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Wellcome Library`,
        location: `London, England`,
        publisher: `Printed for Thomas Underwood and George Underwood`,
        summary: `Gray elevates <a id="Illiger_1811_color_0" onclick="goToSource('D1800-1899','Illiger_1811', this.id)">Illiger's</a> Proboscidea family to an order.  He recognizes and describes two proboscidean species named by Cuvier, <a id="Cuvier_1798_color_1" onclick="goToSource('D1700-1799','Cuvier_1798', this.id)"><i>Elephas indicus</i></a> and <i>Mastodon giganteum</i>, and coins the family name Elephantidae for the former and Mastodontidae for the latter.`,
        title: `On The Natural Arrangement of Vertebrose Animals.`,
        type: `Print journal article`,
    },
    {
        container: `<i>Histoire Naturelle des Mammifères Avec des Figures Originales, Coloriées, Dessinées d'Après des Animaux Vivans</i>, print book`,
        contributors: `Frédéric Cuvier (author)`,
        date: `September 1825`,
        duration: `10 pp.`,
        iteration: `Tome 6`,
        languages: `French`,
        links: `<li><a href="https://archive.org/details/histoirenaturel6geof/page/n122/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `Paris, France`,
        publisher: `A. Belin`,
        summary: `TBA.`,
        title: `Éléphant d'Asie.`,
        type: `Print book chapter`,
    },
    {
        container: `<i>Histoire Naturelle des Mammifères Avec des Figures Originales, Coloriées, Dessinées d'Après des Animaux Vivans</i>, print book`,
        contributors: `Frédéric Cuvier (author)`,
        date: `November 1825`,
        duration: `2 pp.`,
        eyedee: `Cuvier_1825b`,
        iteration: `Tome 6`,
        languages: `French`,
        links: `<li><a href="https://archive.org/details/histoirenaturel6geof/page/n116/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `Paris, France`,
        publisher: `A. Belin`,
        summary: `Cuvier argues that African elephants are anatomically distinct from Asian elephants and warrant placement in a separate genus, which he names <i>Loxodonte</i>.`,
        title: `Éléphant d'Afrique.`,
        type: `Print book chapter`,
    },
    {
        container: `<i>The Zoological Journal</i> (<i>Zool</i>. <i>J</i>.), print journal`,
        contributors: `Anonymous`,
        date: `January 1827`,
        duration: `pp. 140-143`,
        iteration: `Vol. 3, No. 9`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/zoologicaljourna03lond/page/140/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London<li><a href="https://archive.org/details/zoologicaljourna318271828sowe/page/140/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `London, England`,
        publisher: `W. Phillips`,
        summary: `The anonymous author Latinizes <a id="Cuvier_1825b_color" onclick="goToSource('D1800-1899','Cuvier_1825b', this.id)">Cuvier's</a> <i>Loxodonte</i> to <i>Loxodonta</i>.`,
        title: `<i>Histoire Naturelle des Mammifères Avec des Figures Originales, Coloriees, Dessinées d'Après des Animaux Vivans; &c.</i> <i>Par</i> MM. Geoffroy Saint-Hillaire, <i>et</i> F. Cuvier. Livraisons 52<sup>de</sup> <i>et</i> 53<sup>eme</sup>`,
        type: `Print journal article`,
    },
    {
        container: `<i>A Prodromus of a Synopsis Animalium, Comprising a Catalogue Raisonné, of the Zootomical Collection of Joshua Brookes, Esq. F.R.S. etc. Part the First; and of the Anatomical Preparations, Part the Second; Which Will Be Sold by Auction, in Various Lots, About the Middle of May, Unless the Whole Be Previously Purchased by Private Contract, Including the Large and Interesting Department of Natural History, etc. &c.</i>, print book`,
        contributors: `Joshua Brookes (author)`,
        date: `1828, before 22 July`,
        duration: `76 pp.`,
        iteration: `Pt. 1`,
        languages: `English`,
        links: `<li><a href="https://www.google.com/books/edition/Brookesian_Museum/4DwAAAAAQAAJ?hl=en&gbpv=1&pg=PA73"target="_blank">From Google Books</a>, copy provided by Oxford University (<a href="https://web.archive.org/web/20210214192925/https://books.googleusercontent.com/books/content?req=AKW5QadwVSVwUZftumH5axJcOdEm56MH-pPNzuN3WEUeWrIl2STrnlws_LwE2-pZ_brdV-uWMBcmRpgXM2LKJwVLWU-D3VT81_OnaML49OzE4tqAVjgk_DqwrVCyJAlm1WKnfLd2aYSWUyvz3kOkioTlN_gZ9fLJKfPGkUFDqPV4NtlBxLZlLOnxDubZctc_ZsV2rFXhLeYVaNzNyv3yCbm8rH-tDpG5ApLWrq8JqD6UkgoH0Qyp8qL_vB2YU3wnHADvmEQbq0_2"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/brookesianmuseu00broogoog/page/n99/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Oxford University`,
        location: `London, England`,
        publisher: `Printed by Richard Taylor`,
        summary: `The section on elephants, "Fam. 1. Elephantidae. Proboscidea", is on pages 73-74.  Details TBA.`,
        title: `A Catalogue of the Anatomical & Zoological Museum of Joshua Brookes, Esq. F.R.S. Etc.`,
        type: `Print catalogue`,
    },
    {
        container: `<i>Transactions of the American Philosophical Society</i> (<i>Trans</i>. <i>Am</i>. <i>Philos</i>. <i>Soc</i>.), print journal`,
        contributors: `John Davidson Godman (author)`,
        date: `1830, on or after 1 January`,
        duration: `pp. 478-485`,
        iteration: `New Ser., Vol. 3`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/transactionsofam03amer/page/478/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the New York Botanical Garden LuEsther T. Mertz Library<li><a href="https://archive.org/details/transactionsofam03inamer/page/478/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Pittsburgh Library System<li><a href="https://doi.org/10.2307/1005152"target="_blank">From JSTOR (DOI: 10.2307/1005152)</a>`,
        location: `Philadelphia, Pennsylvania, United States of America`,
        publisher: `American Philosophical Society (APS)`,
        summary: `TBA.`,
        title: `No. XIX. Description of a New Genus and New Species of Extinct Mammiferous Quadruped.`,
        type: `Print journal article`,
    },
    {
        container: `<i>Proceedings of the Royal Irish Academy</i> (<i>Proc</i>. <i>R</i>. <i>Ir</i>. <i>Acad</i>.), print journal`,
        contributors: `Robert Harrison (author)`,
        date: `1847, on or after 31 March`,
        duration: `pp. 385-398`,
        iteration: `Vol. 3`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/proceedingsofroy03dubl/page/385/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London`,
        location: `Dublin, Ireland`,
        publisher: `Printed by M.H. Gill for the Royal Irish Academy`,
        summary: `TBA.`,
        title: `On the Anatomy of the Elephant.`,
        type: `Print journal article`,
    },
    {
        contributors: `Coenraad Jacob Temminck (author)`,
        date: `1847, during or after May`,
        duration: `470 pp.`,
        eyedee: `Temminck_1847`,
        iteration: `Tome 2`,
        languages: `French`,
        links: `<li><a href="https://www.google.com/books/edition/Coup_d_oeil_general_sur_les_possessions/2pU6AAAAcAAJ?hl=en&authuser=0&gbpv=1&pg=PA91"target="_blank">From Google Books</a>, copy provided by Bayerische Staatsbibliothek (<a href="https://web.archive.org/web/20210207194817/https://books.googleusercontent.com/books/content?req=AKW5QactSJpZ0V7Tum4sUxdtzTm0PRVs6Fh5WGfDUlhGbF7b-ma3BnyA78n0IJAr7HnSHs8_vey7w04pJeIgoYdWbX6c_fH1cvO-XbeSs76-6K-ozJb_gCtURFHjv4kbY5pErqueK3YSTltp117SxxemO3RPfbhY7UkHtO0XFP1RuhBX6_yr6-OEr8oZf4ZlSDqjoQvgvjfVr92DQU0d_maMChaXKhsX4bMhghNZJELy8-5flTXq3I7glNiSXrsDEzsg6BQkTY6e5l8AMKdSgwFhuyR_JUzRJLBLto7kdN28iAK1UbeToK4"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/Coup_d_oeil_général_sur_les_possession/hhkPAAAAQAAJ?hl=en&authuser=0&gbpv=1&pg=PA91"target="_blank">From Google Books</a>, copy provided by Ghent University (<a href="https://web.archive.org/web/20210207195038/https://books.googleusercontent.com/books/content?req=AKW5QadUpSJur5HYW6deSBmosTatgpCXB4oZIF19F1ib52UQZePhSTULThRWbWLM5fL_xY4aqsQvYo3zVtDb-RAYZzpjRj4-Yb4W4Z1I5NvYEEEE_qnUI58PG8fzn0THhv0ZjfoLviCBE5E6eSubo92zzzTGDfyX_R99dTS7czdN50_nA0_5TJv6xCuxLBUGbSWw6w_HQ1V-Yp8dMciAHHQbafG1CYD_e7lnwXnlSh7YfiJA03FnFkvEHfunS6fVuBYDS71jMTzMkkQfBB9ti7his70wDdxYZf4O7L25sM6xtqI1yaalIIw"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/Coup_d_oeil_g%C3%A9n%C3%A9ral_sur_les_possession/15kBAAAAQAAJ?hl=en&gbpv=1&pg=PA91"target="_blank">From Google Books</a>, copy provided by Oxford University (<a href="https://web.archive.org/web/20210214204620/https://books.googleusercontent.com/books/content?req=AKW5Qaew798VW_baDeugJKp9pAomJlj8POy20G6bl29HeEOHlbpidcMwmP_PUVwSORTB_Nbv5V6q8uKF4WN7O-ZT_ScSuiMctPBg7M6t6dXVAEcYgaZP9DnnUDhs-8lyPvx5V_dLQqRH08QX8XZZDnQCIaJ4qEzreQsljVlaGz3mOkg0knqr5BwUv2uZe5gndiVpD0jGK7W4aePX2vkeEBTwwJ_3xsaXRFvKRohuD6Y4HW3H9U0Ujj4YIfB-kdwBj20-ROChMdQVmLq8HlhxEAB8-9IuTnlViDokQodRcjzePr1ggeYwVFc"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/Coup_d_oeil_général_sur_les_possession/0556zAVURRwC?hl=en&authuser=0&gbpv=1&pg=PA91"target="_blank">From Google Books</a>, copy provided by the New York Public Library (<a href="https://web.archive.org/web/20210207195200/https://books.googleusercontent.com/books/content?req=AKW5QafbOH2P2eJoO794E-98xw5xgT41yHTxHsXU9Q5zsXVAOoFfndou4NmdGMxMsybR3jemyCIa6JmephcAUfLB5C8DGadjJqM2ePq0YBAt0Ji66eTdFNcWDLTMnQd5gMkgI98wsMcQzksERtg-TGP7FQOYSApDj1A-Nh100UkCr4UBqaeihKzWAvI-TiGzBR3oIexXRsC3O6YLrqMTTxIyRJjGlFuviPtLTEvcab8VX8rlrgXLH5_Eiu-i_V5_7SJupKiEs4TsD5DMNWBt7EpQNtfpawpOklODKnkJ_K_cMw8sBjj8o7U"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/Coup_d_oeil_g%C3%A9n%C3%A9ral_sur_les_possession/sBMt6rQpK_8C?hl=en&gbpv=1&pg=PA91"target="_blank">From Google Books</a>, copy provided by the University of Michigan (<a href="https://web.archive.org/web/20210207195340/https://books.googleusercontent.com/books/content?req=AKW5QacmIk4y2aMAkuSbgYQM3Q4PYbC-NTZtXKuSvG2kUD1spqtwtpzqi2E6JLq62aAeJOYKKzb7RfbCA7rjpthlTsRvpwjBOAYBFJh2JiqirAtQqIoDuF-ntPWRo2Q8LKI-P4FYv-v7yYTmj7KaYxmtxJN75QTPyFLchEEIqoafYBeFT5q_DjgyhGzbfG0STJZnI3Lyo3v6GNzGpjWus4YZKVbWHnJVrxna0ijI92Ftd5eUHh6NSvBPkw7Soy4rsW4dOUh73wlPO_u7JCsHvA71mJwbyeNnFa25s1lOywusU-xipLfqZ2w"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/coupdoeilgnrals04temmgoog/page/n105/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Oxford University<li><a href="https://archive.org/details/coupdoeilgnrals03temmgoog/page/n104/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Michigan<li><a href="https://www.digitale-sammlungen.de/de/view/bsb10276433?page=102,103"target="_blank">From Bayerische Staatsbibliothek</a> (<a href="https://web.archive.org/web/20210214203429/https://download.digitale-sammlungen.de/pdf/16133347498888bsb10276433.pdf"target="_blank">archived in the Wayback Machine</a>)`,
        location: `Leiden, Netherlands`,
        publisher: `A. Arnz & Comp.`,
        summary: `Temminck proposes on pages 91-92 that the elephants found on the island of Sumatra are a distinct species from those found elsewhere in Asia based on skeletal differences. He dubs these elephants <i>Elephas sumatranus</i>.`,
        title: `Coup-d'Oeil Général sur les Possessions Néerlandaises dans l'Inde Archipélagique.`,
        type: `Print book`,
    },
    {
        container: `<i>The Quarterly Journal of the Geological Society of London</i> (<i>Q</i>. <i>J</i>. <i>Geol</i>. <i>Soc</i>. <i>Lond</i>.), print journal`,
        contributors: `Hugh Falconer (author)`,
        date: `1857, on or after 30 June`,
        duration: `pp. 307-360`,
        iteration: `Vol. 8, Pt. 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1144/GSL.JGS.1857.013.01-02.43"target="_blank">From publisher (DOI: 10.1144/GSL.JGS.1857.013.01-02.43)</a><li><a href="https://archive.org/details/quarterlyjourna131857geol/page/307/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `London, England`,
        publisher: `Longman, Brown, Green, Longmans, and Roberts.`,
        summary: `TBA.`,
        title: `On the Species of Mastodon and Elephant occuring in the fossil state in Great Britain. Part I. Mastodon.`,
        type: `Print journal article`,
    },
    {
        contributors: `J. Emerson Tennant (author)`,
        date: `1861`,
        duration: `500 pp.`,
        languages: `English`,
        links: `<li><a href="https://www.google.com/books/edition/Sketches_of_the_natural_history_of_Ceylo/F6E5AAAAcAAJ?hl=en&gbpv=1"target="_blank">From Google Books</a>, copy provided by Bayerische Staatsbibliothek (<a href="https://web.archive.org/web/20210608153927/https://books.googleusercontent.com/books/content?req=AKW5QadI9xrpDPzXDC2FeHq211NjaxzuKBmCarr0cyeEG1nX0vTl3p-lsu59tE7-jhIEu3xXiiOCTc159LKITuGco0XG1gTEsRFoAx4wTdmfrwq5_ygYtbOgn2WGYyCNtKvKxDtAVzrQpwmMlQedD5f5M3UzqZwbnftGiKVGYEnX4bPUUa6-dUj9gzDofUb1kooRRUPBSOaMTBDcFPg42eoz0_k73E-Z49kUOTyZXc6J5eVG1fhhY0rBWut7fkgz596nVOSbm2cFEse4fb2AbsbPtgdJ5Q-MqQ"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/Sketches_of_the_Natural_History_of_Ceylo/DgoXAAAAYAAJ?hl=en&gbpv=1"target="_blank">From Google Books</a>, copy provided by Harvard University (<a href="https://web.archive.org/web/20210608172841/https://books.googleusercontent.com/books/content?req=AKW5Qaf5CXIfuDObod7z-dgdHIxy2wdC9HpKGmfjzbwSUFKw5N0ik5W9fA2eYo0MeREyOfWx2ajSw8cRpLqUY7-2PUF_TESLMOGxlzKA-qJ4TAi11EL-_e9Mopnq1KAl7-8l0cQOjN1Q7CKZSL6fYWvVEYz_U_6ySKQyGMaHUD2RJJ3IUHMvR-XbwVi5Tv0qlnXB6wW7zYvwEh7-JRrMJuZu7P2X_DPMqTcXrrXruE7J5b1_fLineMBJltGigBc_5rjySLdf1uF6d-atNc-Gx8xhqmkKvQKKUNeNmg4dhcjgdcMLyumHL8k"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/Sketches_of_the_National_History_of_Ceyl/Pm-0-junxGwC?hl=en&gbpv=1"target="_blank">From Google Books</a>, copy provided by the British Library (<a href="https://web.archive.org/web/20210608172511/https://books.googleusercontent.com/books/content?req=AKW5QafeHXFtnZpuEa8eDALUNJVM7CzakfTD1q9ecZP41ts8P4JePkPc3Vv73vMvLHbk657OnbcktfMRw211YlY19wH_o0TITBjw8MQ-NmlpANXO3Wg-HawLUcYNOrmHIlXt3hjfFmw5-z-5a0bg-5LLg0UdxdWFlU8lnkIwEvLFEYXCY_g_rdMtSAz8DX268MmYuAevWatcF24JRgtRbgKvt4zbVuDBdwBLmhnHwiBxOVNHqa9-IyfQweV5thpUSW2HIUbcQicbQJdejR3WFbs4axAKF6AxiQ"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/cu31924001539679/page/n6/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Cornell University Library<li><a href="https://archive.org/details/sketchesofnatura00tenn/page/n8/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by NCSU Libraries<li><a href="https://archive.org/details/Sketchesnatural00Tenn/page/iii/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries<li><a href="https://archive.org/details/dli.ministry.27094/page/n4/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Public Library of India<li><a href="https://archive.org/details/sketchesnatural00tenngoog/page/n9/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Michigan<li><a href="https://archive.org/details/sketchesofnatura00tenn_0/page/n8/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Toronto Thomas Fisher Rare Book Library<li><a href="https://www.digitale-sammlungen.de/de/view/bsb10076559?page=10,11"target="_blank">From Bayerische Staatsbibliothek</a> (<a href="https://web.archive.org/web/20210608175949/https://download.digitale-sammlungen.de/pdf/16231748188888bsb10076559.pdf"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.fulltextarchive.com/page/Sketches-of-Natural-History-of-Ceylon/"target="_blank">Digital copy from Full Text Archive</a>`,
        location: `London, England`,
        publisher: `Longman, Green, Longman, and Roberts`,
        summary: `TBA.`,
        title: `Sketches of the Natural History of Ceylon`,
        type: `Print book`,
    },
    {
        container: `<i>Harper's Weekly. A Journal of Civilization.</i>, print magazine`,
        contributors: `Thomas Nast (cartoonist)`,
        date: `7 November 1874`,
        duration: `p. 912`,
        iteration: `Vol. 18, No. 932`,
        languages: `English`,
        links: `<li><a href="https://art.famsf.org/thomas-nast/third-term-panic-harpers-weekly-november-7-1874-19841182"target="_blank">From the Fine Arts Museums of San Francisco</a><li><a href="http://mutex.gmu.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=h9m&AN=67549865&site=ehost-live"target="_blank">From George Mason University</a><li><a href="https://www.loc.gov/resource/ppmsca.15785/"target="_blank">From the Library of Congress</a><li><a href="https://americanhistory.si.edu/collections/search/object/nmah_528979"target="_blank">From the Smithsonian National Museum of American History</a><li><a href="http://amica.davidrumsey.com/luna/servlet/detail/AMICO~1~1~52090~17421:The-Third-Term-Panic?sort=INITIALSORT_CRN%2COCS%2CAMICOID"target="_blank">From the AMICA Library</a><li><a href="https://www.harpweek.com/09Cartoon/BrowseByDateCartoon.asp?Year=2003&Month=November&Date=7"target="_blank">From HarpWeek</a>`,
        location: `New York, United States of America`,
        publisher: `Harper & Brothers`,
        summary: `The first use of an elephant to represent the Republican vote.`,
        title: `The Third Term Panic.`,
        type: `Print cartoon`,
    },
    {
        container: `<i>Studies in Comparative Anatomy</i>, print book series`,
        contributors: `L.C. Miall (co-author); F. Greenwood (co-author)`,
        date: `1878`,
        duration: `84 pp.`,
        iteration: `No. 2`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/anatomyofindiane00mial/page/n6/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Harvard University Ernst Mayr Library of the Museum of Comparative Zoology`,
        location: `London, England`,
        publisher: `Macmillan and Co.`,
        summary: `TBA.`,
        title: `Anatomy of the Indian Elephant`,
        type: `Print book`,
    },
    {
        contributors: `J.P. Maclean (author)`,
        date: `1878, on or after 25 April`,
        duration: `84 pp.`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/mastodonmammothm00macl/page/n6/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Harvard University Ernst Mayr Library of the Museum of Comparative Zoology`,
        location: `Cincinnati, Ohio, United States of America`,
        publisher: `Williamson & Cantwell Publishing Co.`,
        summary: `TBA.`,
        title: `Mammoth, Mastodon, and Man.`,
        type: `Print book`,
    },
    {
        contributors: `Matthew Scott (author)`,
        date: `1885, sometime between 14 January and 15 September (see Notes)`,
        duration: `96 pp.`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/autobiographyofm00scot/page/n8/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Boston Public Library<li><a href="https://www.fadedpage.com/showbook.php?pid=20150417"target="_blank">Digital copy from Faded Page</a>`,
        location: `Bridgeport, Connecticut, United States of America`,
        notes: `<li>Must have been published on or after 14 January 1885, the date of the dedication, but before 15 September 1885, when Jumbo was killed.`,
        publisher: `Trow's Printing and Bookbinding Co.`,
        summary: `TBA.`,
        title: `Autobiography of Matthew Scott, Jumbo's Keeper: Formerly of the Zoölogical Society's Gardens, London, and Receiver of Sir Edwin Landseer Medal in 1866; Also Jumbo's Biography by the Same Author.`,
        type: `Print book`,
    },
    {
        container: `<i>The American Naturalist</i> (<i>Am</i>. <i>Nat</i>.), print journal`,
        contributors: `Edward Drinker Cope (author)`,
        date: `April 1889`,
        duration: `pp. 191-211`,
        iteration: `Vol. 23, No. 268`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1086/274905"target="_blank">From the University of Chicago Press (DOI: 10.1086/274905)</a><li><a href="https://archive.org/details/mobot31753002156633/page/191/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Missouri Botanical Garden</a><li><a href="https://www.jstor.org/stable/2450949"target="_blank">From JSTOR</a>`,
        location: `Philadelphia, Pennsylvania, United States of America`,
        publisher: `Ferris Bros.`,
        summary: `TBA.`,
        title: `The Proboscidia`,
        type: `Print journal article`,
    },
    {
        contributors: `William Henry Flower (co-author); Richard Lydekker (co-author)`,
        date: `1891, during or after March`,
        duration: `763 pp.`,
        languages: `English`,
        links: `<li><a href="https://www.google.com/books/edition/An_Introduction_to_the_Study_of_Mammals/YclRAAAAMAAJ?hl=en&gbpv=1&pg=PA418"target="_blank">From Google Books</a>, copy provided by the University of Wisconsin-Madison (<a href="https://web.archive.org/web/20210219031828/https://books.googleusercontent.com/books/content?req=AKW5QadLnZED9Lk4AHo1IdsRzR-c_YLYBCxcaZamoylOunbqvPfda-KuOvWV4LL78l1SGe2NRJdZmrR9UtcBaIFFWM9_IB60_yc2acZW2EjRG_CO6ZeyXuT-DzvQ83k8kNqw_3HHHibfY0Yd_KAa6JoOA2Dtr-rIVdnvH8FC0bcw7FlN5qA4j-AlwBSb5gNrgm5w3VbyjzSPWqlYwlVJM5aA_9zbuqDCPPIZrdLgRRY93nq40PFDANu5fB486dfMKbwyHhpAfuq_q4WCJW8HQELv7SOmxBYv7w"target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/cu31924001022684/page/n437/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Cornell University Library<li><a href="https://archive.org/details/introductiontost00flow/page/418/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Marine Biological Laboratory and Woods Hole Oceanographic Institution (MBLWHOI) Library<li><a href="https://archive.org/details/b2191610x/page/418/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Royal College of Physicians in Edinburgh<li><a href="https://archive.org/details/anintroductiont00lydegoog/page/n440/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Wisconsin-Madison`,
        location: `London, England`,
        publisher: `Adam and Charles Black`,
        summary: `The section on elephants, "Suborder Proboscidea", is on pages 418-436. Details TBA.`,
        title: `An Introduction to the Study of Mammals Living and Extinct`,
        type: `Print book`,
    },
    {
        contributors: `Anonymous`,
        date: `1899`,
        duration: `72 x 106 cm (28 x 41.7 in)`,
        languages: `English`,
        links: `<li><a href="https://www.loc.gov/resource/ppmsca.55077/"target="_blank">From the Library of Congress</a>`,
        location: `Buffalo, New York, United States of America`,
        notes: `<li><a href="https://www.loc.gov/resource/cph.3b52708/"target="_blank">Color film copy transparency from the Library of Congress.</a>`,
        publisher: `Courier Litho. Co.`,
        summary: `TBA.`,
        title: `Ringling Bros. World's Greatest Shows Elephant Brass Band.`,
        type: `Print poster`,
    },
]