module.exports = [
    {
        container: `<i>Sitzungs-Berichte der Gesellschaft naturforschender Freunde zu Berlin</i> (<i>Sitz</i>.-<i>Ber</i>. <i>Ges</i>. <i>naturforsch</i>. <i>Freunde</i> <i>Berl</i>.), journal`,
        contributors: `Paul Matschie (author)`,
        date: `1900, on or after 16 October`,
        duration: `pp. 189-197`,
        iteration: `Issue 8`,
        languages: `German`,
        links: `<li><a href="https://www.google.com/books/edition/_/W5dOAQAAMAAJ?hl=en&gbpv=1&pg=PA189"target="_blank">From Google Books</a>, copy provided by the University of Illinois Urbana-Champaign (<a href="https://web.archive.org/web/20210207193625/https://books.googleusercontent.com/books/content?req=AKW5QacuGQQil4EEMX4McXafU8riykOWuKYjcpjliKIDE0bXkrG88aQArnlbHPF2vNnmeGz3T_RwUtQOYsQodCAq3-Tkw1LUV45SF6F7Dg6pqvsntz5lW1-Gl_BPVNvGGrOfPoUoEG0d3rYqpM3_GUvsbgf5BorNzPK48W1gHxg5WAN3kjyULc4CZwgK9ugkE0ht4h8XNFwjO7G-9CKEQGo16CDtMIK98ysqerYQcV9QbBYHi2OGaackuhhql6LK8waAhC_GAjKJ_Kh3KCZNool_7yUA3zb9UMwoI4UOYb4iUFIgCBS41wc"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://archive.org/details/sitzungsberichte1900gese/page/189/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Harvard University Museum of Comparative Zoology Ernst Mayr Library</li>`,
        location: `Berlin, Germany`,
        publisher: `R. Friedländer und Sohn`,
        summary: `TBA.`,
        title: `Über geographische Abarten des afrikanischen Elefanten.`,
        type: `Journal article`,
    },
    {
        contributors: `George Henry Evans (author)`,
        date: `1901`,
        duration: `262 pp.`,
        eyedee: `Evans_1901`,
        languages: `English`,
        links: `<li><a href="https://digital.nls.uk/indiapapers/browse/archive/75190071"target="_blank">From the National Library of Scotland</a></li><li><a href="https://archive.org/details/in.ernet.dli.2015.221068/page/n3/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Digital Library of India</li><li><a href="https://archive.org/details/TreatiseOnElephants/page/n3/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Garden of Shyamal</li>`,
        location: `Rangoon, Burma [Myanmar]`,
        publisher: `Superintendent, Government Printing, Burma`,
        summary: `TBA.`,
        title: `A Treatise On Elephants. Their Treatment in Health and Disease`,
        type: `Book`,
    },
    {
        container: `<i>Proceedings of the Zoological Society of London</i> (<i>Proc</i>. <i>Zool</i>. <i>Soc</i>. <i>Lond</i>.), journal`,
        contributors: `Richard Lydekker (author)`,
        date: `1 August 1907 (Back Matter, 1907)`,
        duration: `pp. 380-403`,
        iteration: `[Vol. 77, Issue 2], No. 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1096-3642.1907.tb01824.x"target="_blank">From publisher (DOI: 10.1111/j.1096-3642.1907.tb01824.x)</a> through Wiley Online Library</li><li><a href="https://archive.org/details/proceedingsofzoo19071446zool/page/380/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li>`,
        location: `London, England`,
        publisher: `Messrs. Longmans, Green, and Co.`,
        references: `<ul class="refs"><a href="https://archive.org/details/proceedingsofzoo19074471121zool/page/n391/mode/2up?view=theater"target="_blank">[Back Matter]</a>. (1907). <i>Proceedings of the Zoological Society of London</i>, <i>77</i>(3).</ul>`,
        summary: `TBA.`,
        title: `The Ears as a Race-Character in the African Elephant.`,
        type: `Journal article`,
    },
    {
        contributors: `Johan Erik Vesti Boas (co-author); Simon Paulli (co-author)`,
        date: `1908`,
        duration: `80 pp.`,
        iteration: `Part 1 <i>The Facial Muscles and the Proboscis</i>`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/elephantshead00boas/page/n2/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li>`,
        location: `Jena, Germany`,
        publisher: `Gustav Fischer`,
        summary: `TBA.`,
        title: `The Elephant's Head Studies in the Comparative Anatomy of the Organs of the Head of the Indian Elephant and Other Mammals`,
        type: `Book`,
    },
    {
        contributors: `Charles A. Williams (author); Arthur Smith Woodward (preface author)`,
        date: `1908, during or after February`,
        duration: `46 pp.`,
        languages: `English`,
        links: `<li><a href="https://www.google.com/books/edition/A_Guide_to_the_Elephants_recent_and_Foss/ets4AAAAMAAJ?hl=en&gbpv=1"target="_blank">From Google Books</a>, copy provided by the University of Michigan (<a href="https://web.archive.org/web/20210223141857/https://books.googleusercontent.com/books/content?req=AKW5Qad7gTvfOOCHik8qdqoiErGshGOkxGbiOFsJsd2o2Hq_RrKj0C-D-fIpZnHim4UPZC1fEY1Raz91yDKuf6rvoMSnzgp2o-hr74Cmhrvq8X-sjiRwvS6CV96eZE88ByLrxYQDb_rmrHDVIn3TsN_L4prcL1rA6a2hqav6bpeIXNPLPPuZ91nVSRJ1nDjjAPSlRW7jsucvL-5fO-Q72DaOXv5iStyy2Uju8Llb6R_o2ZIa5nZnFXHi9x56UqJ_Ue7i57DACcE1Z2lMm8cHOxqyLuM0qthXniBX-1s_7FCSgrHGGUTxndY"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://archive.org/details/guidetoelephants00britrich/page/n4/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of California Libraries</li><li><a href="https://archive.org/details/aguidetoelephan00andrgoog/page/n4/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Michigan</li>`,
        location: `London, England`,
        publisher: `Trustees of the British Museum`,
        summary: `TBA.`,
        title: `A Guide to the Elephants (Recent and Fossil) Exhibited in the Department of Geology and Palæontology in the British Museum (Natural History)`,
        type: `Book`,
    },
    {
        contributors: `George Henry Evans (author)`,
        date: `1910, during or after June`,
        duration: `343 pp.`,
        languages: `English`,
        links: `<li><a href="https://digital.nls.uk/indiapapers/browse/archive/75192017"target="_blank">From the National Library of Scotland</a></li><li><a href="https://archive.org/details/cu31924001176878/page/n23/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Cornell University Library</li><li><a href="https://archive.org/details/elephantstheirdi00evan/page/n10/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li><li><a href="https://web.archive.org/web/20190104030414/http://wildpro.twycrosszoo.org/S/00Ref/BooksContents/B212EvansEle/Contents.htm"target="_blank">Digital copy from Wildpro</a>, archived in the Wayback Machine</li>`,
        location: `Rangoon, Burma [Myanmar]`,
        publisher: `Superintendent, Government Printing, Burma`,
        summary: `The revised edition of <a id="Evans_1901_color_0" onclick="goToSource('D1900-1999','Evans_1901', this.id)">Evans, 1901</a>. Details TBA.`,
        title: `Elephants and Their Diseases a Treatise on Elephants`,
        type: `Book`,
    },
    {
        container: `<i>Proceedings of the Zoological Society of London</i> (<i>Proc</i>. <i>Zool</i>. <i>Soc</i>. <i>Lond</i>.), journal`,
        contributors: `Richard Lydekker (author)`,
        date: `16 June 1914 (Back Matter, 1914)`,
        duration: `pp. 285-288`,
        iteration: `[Vol. 84], Issue 2, No. 18`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1469-7998.1914.tb07036.x"target="_blank">From publisher (DOI: 10.1111/j.1469-7998.1914.tb07036.x)</a> through Wiley Online Library</li><li><a href="https://archive.org/details/proceedingsofzoo19141490zool/page/285/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li>`,
        location: `London, England`,
        publisher: `Messrs. Longmans, Green, and Co.`,
        references: `<ul class="refs"><a href="https://archive.org/details/proceedingsofzoo19144911077zool/page/n541/mode/2up?view=theater"target="_blank">[Back Matter]</a>. (1914). <i>Proceedings of the Zoological Society of London</i>, <i>84</i>(3).</ul>`,
        summary: `TBA.`,
        title: `The Malay Race of the Indian Elephant, <i>Elephas maximus hirsutus</i>.`,
        type: `Journal article`,
    },
    {
        container: `<i>American Museum Novitates</i> (<i>Am</i>. <i>Mus</i>. <i>Novit</i>.), journal`,
        contributors: `Henry Fairfield Osborn (author)`,
        date: `31 January 1921`,
        duration: `15 pp.`,
        iteration: `No. 1`,
        languages: `English`,
        links: `<li><a href="http://digitallibrary.amnh.org/handle/2246/4663"target="_blank">From publisher</a></li><li><a href="https://www.google.com/books/edition/The_Evolution_Phylogney_and_Classificati/1sUrAAAAYAAJ?hl=en&gbpv=1"target="_blank">From Google Books</a>, copy provided by Harvard University (<a href="https://web.archive.org/web/20210401172956/https://books.googleusercontent.com/books/content?req=AKW5QaekHU5wcSu3eYcFaNqml2WL1GXkB_30ntZJ0Uuytid-dsE2prNwdpSMZwUW9FSAPor4YEU0YJd-pA3sB8-p7Vze8l10fe7Fz1zEZAxV09uL4c1raNe1ebfj1DIFzmEyqL198vv1tvj8foSQYM7wyOqPSHqVSzwtyQTu3aPY_-n1TyRPExdg-US6p07Qe4D1BuoYsJf8VxxGJEr2jfrq9m41evm-QfNMIwkG8CdqrUOna5Fxim28ZkpefFcoA0vkBLDDmvtTat23kmAjo1deo9jV8C53JJB0a-P0BAkHb2bRxM69ssg"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://archive.org/details/americanmuseumno01ameruoft/page/n38/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the University of Toronto Gerstein Science Information Centre</li>`,
        location: `New York City, New York, United States of America`,
        publisher: `Trustees of the American Museum of Natural History`,
        summary: `TBA.`,
        title: `The Evolution, Phylogeny, and Classification of the Proboscidea`,
        type: `Journal article`,
    },
    {
        container: `<i>Proceedings of the Academy of Natural Sciences of Philadelphia</i> (<i>Proc</i>. <i>Acad</i>. <i>Nat</i>. <i>Sci</i>. <i>Phila</i>.), journal`,
        contributors: `Glover Morrill Allen (author)`,
        date: `10 March 1936`,
        duration: `pp. 15-44`,
        iteration: `Vol. 88`,
        languages: `English`,
        links: `<li><a href="https://www.jstor.org/stable/4064188"target="_blank">From JSTOR</a></li>`,
        location: `Philadelphia, Pennsylvania, United States of America`,
        publisher: `Academy of Natural Sciences of Philadelphia`,
        summary: `TBA.`,
        title: `Zoological Results of the George Vanderbilt African Expedition of 1934. Part II,—The Forest Elephant of Africa`,
        type: `Journal article`,
    },
    {
        contributors: `Henry Fairfield Osborn (author); Mabel Rice Percy (editor)`,
        date: `15 August 1936`,
        duration: `pp. 1-802`,
        iteration: `Vol. 1 <i>Mœritherioidea Deinotherioidea Mastodontoidea</i>`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/proboscideamonog01osbo/page/n12/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the American Museum of Natural History Library</li>`,
        location: `New York City, New York, United States of America`,
        publisher: `Trustees of the American Museum of Natural History`,
        summary: `TBA.`,
        title: `Proboscidea a Monograph of the Discovery, Evolution, Migration and Extinction of the Mastodonts and Elephants of the World`,
        type: `Book`,
    },
    {
        container: `<i>Bulletin of the Raffles Museum</i> (<i>Bull</i>. <i>Raffles</i> <i>Mus</i>.), journal`,
        contributors: `Frederick Nutter Chasen (author)`,
        date: `April 1940`,
        duration: `209 pp.`,
        iteration: `Vol. 15`,
        languages: `English`,
        links: `<li><a href="https://digitalgems.nus.edu.sg/persistent/55001bfc-e505-473e-8b90-aee1d9867ca2"target="_blank">From the Biodiversity Library of Southeast Asia</a> (<a href="https://web.archive.org/web/20200212165718/https://blsea.nus.edu.sg/shared/UPLOADS/JOURNALS/LOW/BulRaf_no15.pdf"target="_blank">archived in the Wayback Machine</a>)</li><li><a href="https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/10/app/uploads/2017/04/15brmiii-209.pdf"target="_blank">From the Lee Kong Chian Natural History Museum</a></li>`,
        location: `Singapore`,
        publisher: `Raffles Museum`,
        summary: `On page 190, Chasen recognizes Asian elephants as a single species, <i>Elephas maximus</i>, with three subspecies. He retains <a id="Linnaeus_1758_color_1" onclick="goToSource('D1700-1799','Linnaeus_1758', this.id)">Linnaeus's</a> <i>E</i>. <i>m</i>. <i>maximus</i> for the elephants of Sri Lanka, <a id="Cuvier_1798_color_1" onclick="goToSource('D1700-1799','Cuvier_1798', this.id)">Cuvier's</a> <i>E</i>. <i>m</i>. <i>indicus</i> for elephants on the Asian mainland and Borneo, and <a id="Temminck_1847_color_0" onclick="goToSource('D1800-1899','Temminck_1847', this.id)">Temminck's</a> <i>E</i>. <i>m</i>. <i>sumatranus</i> for Sumatran elephants.`,
        title: `A Handlist of Malaysian Mammals a Systematic List of the Mammals of the Malay Peninsula, Sumatra, Borneo and Java, Including the Adjacent Small Islands`,
        type: `Journal article`,
    },
    {
        contributors: `Henry Fairfield Osborn (author); Mabel Rice Percy (editor)`,
        date: `1942`,
        duration: `pp. 805-1675`,
        iteration: `Vol. 2 <i>Stegodontoidea Elephantoidea</i>`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/proboscideamonog02osbo/page/n10/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the American Museum of Natural History Library</li>`,
        location: `New York City, New York, United States of America`,
        publisher: `Trustees of the American Museum of Natural History`,
        summary: `TBA.`,
        title: `Proboscidea a Monograph of the Discovery, Evolution, Migration and Extinction of the Mastodonts and Elephants of the World`,
        type: `Book`,
    },
    {
        container: `<i>Földtani Közlöny</i> (<i>Földt</i>. <i>Közlöny</i>), journal`,
        contributors: `Miklós Kretzoi (author)`,
        date: `1950, on or after 4 October`,
        duration: `pp. 405-408`,
        iteration: `Vol. 80, Issues 10-12`,
        languages: `Hungarian, English`,
        links: `<li><a href="https://archive.org/details/foldtanikozlony8019magy/page/n452/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by the Cornell University Library</li><li><a href="http://epa.oszk.hu/01600/01635/00436/pdf/EPA01635_foldtani_kozlony_1950_80_10-12_405-408.pdf"target="_blank">From Elektronikus Periodika Archívum és Adatbázis</a></li>`,
        publisher: `Nehézipari Könyv- és Folyóiratkiadó Vállalat`,
        summary: `TBA.`,
        title: `<i>Stegeloxodon</i> nov. gen„ a loxodonta elefántok esetleges ázsiai őse`,
        type: `Journal article`,
    },
    {
        container: `<i>Journal of Geography</i> (<i>J</i>. <i>Geogr</i>.), journal`,
        contributors: `Charles F. Bennett, Jr. (author)`,
        date: `April 1957`,
        duration: `pp. 168-172`,
        iteration: `Vol. 56, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1080/00221345708983130"target="_blank">From publisher (DOI: 10.1080/00221345708983130)</a> through Taylor & Francis Online</li>`,
        publisher: `National Council for Geographic Education (NCGE)`,
        summary: `TBA.`,
        title: `A Brief History of Trained African Elephants in the Belgian Congo`,
        type: `Journal article`,
    },
    {
        container: `<i>East African Wildlife Journal</i> (<i>East</i> <i>Afr</i>. <i>Wildl</i>. <i>J</i>.), journal`,
        contributors: `Richard M. Laws (author)`,
        date: `August 1966`,
        duration: `pp. 1-37`,
        iteration: `Vol. 4, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1365-2028.1966.tb00878.x"target="_blank">From publisher (DOI: 10.1111/j.1365-2028.1966.tb00878.x)</a> through Wiley Online Library</li>`,
        publisher: `East African Wild Life Society (EAWLS)`,
        summary: `TBA.`,
        title: `Age Criteria for the African Elephant, <i>Loxodonta</i> <i>a</i>. <i>africana</i>`,
        type: `Journal article`,
    },
    {
        container: `<i>Nature</i> (<i>Nat</i>.), journal`,
        contributors: `D.A. Hooijer (author)`,
        date: `22 September 1972`,
        duration: `pp. 228`,
        iteration: `Vol. 239, [Issue 5369]`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1038/239228a0"target="_blank">From publisher (DOI: 10.1038/239228a0)</a></li>`,
        publisher: `Macmillan Journals`,
        summary: `TBA.`,
        title: `Prehistoric Evidence for <i>Elephas maximus</i> L. in Borneo`,
        type: `Journal article`,
    },
    {
        container: `<i>Mammalian Species</i> (<i>Mamm</i>. <i>Species</i>), journal`,
        contributors: `Larry Laursen (co-author); Marc Bekoff (co-author); Sydney Anderson (editor)`,
        date: `6 January 1978`,
        duration: `8 pp.`,
        iteration: `No. 92`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.2307/3503889"target="_blank">From publisher (DOI: 10.2307/3503889)</a> through Oxford Academic</li><li><a href="https://web.archive.org/web/20130430140501/http://www.science.smith.edu/msi/pdf/i0076-3519-092-01-0001.pdf"target="_blank">From the Smith College Clark Science Center</a>, archived in the Wayback Machine</li><li><a href="https://www.jstor.org/stable/3503889"target="_blank">From JSTOR</a></li>`,
        publisher: `American Society of Mammalogists (ASM)`,
        summary: `TBA.`,
        title: `<i>Loxodonta africana</i>.`,
        type: `Journal article`,
    },
    {
        container: `<i>Elephant</i>, journal`,
        contributors: `A.L. Howard (author)`,
        date: `1979, on or after 1 May`,
        duration: `pp. 36-41`,
        iteration: `Vol. 1, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.22237/elephant/1491420381"target="_blank">From publisher (DOI: 110.22237/elephant/1491420381)</a></li>`,
        location: `Detroit, Michigan, United States of America`,
        publisher: `Wayne State University Department of Biological Sciences`,
        summary: `TBA.`,
        title: `"Motty"--Birth of an African/Asian Elephant at Chester Zoo`,
        type: `Journal article`,
    },
    {
        container: `<i>Elephant</i>, journal`,
        contributors: `Jeheskel Shoshani (co-author); Daniel C. Laughlin (co-author); Lawrence D. McGill (co-author, reviewer); Franz Tisch (co-author); Michael J. Baccala (co-author); Sandra S. Lash (co-author); Mildred Hurt (co-author); Eyal Shy (co-author); Susan L. Raymer (co-author); Dick Frederick (co-author); Dave Sabo (co-author); Sue ann Berbenchuk (co-author); Kathleen M. Morehead (co-author, photographer); Joseph Skoney (co-author); George Overbeck (co-author); Marlene A. Bulgarelli (co-author); Anthony Helinski (co-author); Harold W. Rossmoore (co-author); Joseph G. Engelhard (co-author); Joy Koenig (co-author); Efstratios Efthyvoulidis (co-author); Nicholas J. Mizeres (co-author); Victor T. Lakits, Jr. (co-author); Theodore Gaskins (co-author); Donald Smith (co-author); Chris Heberer (co-author); Sean Murphy (co-author); Anthony A. Muraski (co-author); Susan Grabowski (co-author); Jim Williams (co-author); John W. Cosgriff, Jr. (co-author); Richard Bielaczyc (co-author, photographer); Jim Niedbala (co-author); M. Pamela Bedore (co-author, typist, editor); Karen L. Spodarek (co-author); Irven O. Buss (reviewer); Richard M. Laws (reviewer); Sylvia K. Sikes (reviewer); Zirka S. Clark (typist, editor); Eileen D. Koglin (typist, editor); George Booth (co-author, photographer); Leslie Denes (co-author); Rick Adler (co-author); Krysty Andrews (co-author); Allan Barbish (co-author); Susan Barry (co-author); Ron Battiata (co-author); Nate Bozarth (co-author); Irene Church (co-author); Helen Crowe (co-author); Sherri L. DeFauw (co-author); Merlin Ekstrom (co-author); Patrick English (co-author); Don Fairchild, Jr. (co-author); Carla Fisher (co-author); Kevin Frahm (co-author); Judi Fried (co-author); Joanne Gatt (co-author); Wilma Gentles (co-author); Harry G. Goshgarian (co-author); Debbie Haase (co-author); Kathryn Hajj (co-author); Gary Hall (co-author); Debbie Hawkins (co-author); Shawne R. Henry (co-author); Chuck Heyka (co-author); Mike Kemppainen (co-author); Cathy Kendra (co-author); Paul Konarske (co-author); Sue Konwinski (co-author); Stephan Kopacz (co-author); Stuart Meyers (co-author); Robert Powitz (co-author); Jose A. Rafols (co-author); Lisa Rezzonica (co-author); Paul J. Schwikert (co-author); Peter J. Sujdak (co-author); Todd Tarrant (co-author); Ron Thielman (co-author); Ronnie Thielman (co-author); Linda Walowicz (co-author); Dorit Yehiel (co-author)`,
        date: `1982, on or after 2 May`,
        duration: `pp. 3-93`,
        iteration: `Vol. 2, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.22237/elephant/1521731887"target="_blank">From publisher (DOI: 10.22237/elephant/1521731887)</a></li><li><a href="https://core.ac.uk/display/212887158"target="_blank">From CORE</a></li>`,
        location: `Detroit, Michigan, United States of America`,
        publisher: `Wayne State University Department of Biological Sciences`,
        summary: `TBA.`,
        title: `On the Dissection of a Female Asian Elephant (<u>Elephas</u> <u>maximus</u> <u>maximus</u> Linnaeus, 1758) and Data from Other Elephants`,
        type: `Journal article`,
    },
    {
        container: `<i>Mammalian Species</i> (<i>Mamm</i>. <i>Species</i>), journal`,
        contributors: `Jeheskel Shoshani (co-author); John F. Eisenberg (co-author); M. Pamela Bedore (typist); Eileen D. Koglin (typist); Daniel F. Williams (editor); Sydney Anderson (editor); Timothy E. Lawlor (editor)`,
        date: `18 June 1982`,
        duration: `8 pp.`,
        iteration: `No. 182`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.2307/3504045"target="_blank">From publisher (DOI: 10.2307/3504045)</a> through Oxford Academic</li><li><a href="http://web.archive.org/web/20150318181534/http://www.science.smith.edu/msi/pdf/i0076-3519-182-01-0001.pdf"target="_blank">From the Smith College Clark Science Center</a>, archived in the Wayback Machine</li><li><a href="https://repository.si.edu/handle/10088/4414"target="_blank">From Smithsonian Research Online DSpace Repository</a></li><li><a href="https://www.jstor.org/stable/3504045"target="_blank">From JSTOR</a></li>`,
        publisher: `American Society of Mammalogists (ASM)`,
        summary: `TBA.`,
        title: `<i>Elephas maximus</i>.`,
        type: `Journal article`,
    },
    {
        container: `<i>Bulletin of the Psychonomic Society</i> (<i>Bull</i>. <i>Psychon</i>. <i>Soc</i>.), journal`,
        contributors: `Ronald K. Siegel (co-author); Mark Brodie (co-author)`,
        date: `July 1984`,
        duration: `pp. 49-52`,
        iteration: `Vol. 22, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.3758/BF03333758"target="_blank">From publisher (DOI: 10.3758/BF03333758)</a> through SpringerLink</li>`,
        location: `Austin, Texas, United States of America (Dewsbury, 1996)`,
        publisher: `Psychonomic Society`,
        references: `<ul class="refs">Dewsbury, D.A. (1996). History of the Psychonomic Society II: The journal publishing program. <i>Psychonomic Bulletin & Review</i>, 3, 322–338. <a href="https://doi.org/10.3758/BF03210756"target="_blank">https://doi.org/10.3758/BF03210756</a></ul>`,
        summary: `TBA.`,
        title: `Alcohol self-administration by elephants`,
        type: `Journal article`,
    },
    {
        container: `<i>South African Journal of Zoology</i> (<i>S</i>. <i>Afr</i>. <i>J</i>. <i>Zool</i>.), journal`,
        contributors: `P.G. Wright (author)`,
        date: `October 1984`,
        duration: `pp. 266-269`,
        iteration: `Vol. 19, Issue 4`,
        languages: `English, Afrikaans`,
        links: `<li><a href="https://doi.org/10.1080/02541858.1984.11447891"target="_blank">From publisher (DOI: 10.1080/02541858.1984.11447891)</a> through Taylor & Francis Online</li><li><a href="https://www.ajol.info/index.php/az/article/view/152820"target="_blank">From African Journals Online</a></li><li><a href="https://hdl.handle.net/10520/AJA00445096_2297"target="_blank">From Sabinet African Journals</a></li>`,
        location: `Pretoria, South Africa`,
        publisher: `Bureau for Scientific Publications of the Foundation for Education, Science and Technology`,
        summary: `TBA.`,
        title: `Why do elephants flap their ears?`,
        type: `Journal article`,
    },
    {
        container: `<i>South African Journal of Zoology</i> (<i>S</i>. <i>Afr</i>. <i>J</i>. <i>Zool</i>.), journal`,
        contributors: `P.G. Wright (co-author); C.P. Luck (co-author)`,
        date: `October 1984`,
        duration: `pp. 270-274`,
        iteration: `Vol. 19, Issue 4`,
        languages: `English, Afrikaans`,
        links: `<li><a href="https://doi.org/10.1080/02541858.1984.11447892"target="_blank">From publisher (DOI: 10.1080/02541858.1984.11447892)</a> through Taylor & Francis Online</li><li><a href="https://www.ajol.info/index.php/az/article/view/152821"target="_blank">From African Journals Online</a></li><li><a href="https://hdl.handle.net/10520/AJA00445096_2298"target="_blank">From Sabinet African Journals</a></li>`,
        location: `Pretoria, South Africa`,
        publisher: `Bureau for Scientific Publications of the Foundation for Education, Science and Technology`,
        summary: `TBA.`,
        title: `Do elephants need to sweat?`,
        type: `Journal article`,
    },
    {
        container: `<i>African Journal of Ecology</i> (<i>Afr</i>. <i>J</i>. <i>Ecol</i>.), journal`,
        contributors: `G. Merz (author)`,
        date: `June 1986`,
        duration: `pp. 133-136`,
        iteration: `Vol. 24, Issue 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1365-2028.1986.tb00353.x"target="_blank">From publisher (DOI: 10.1111/j.1365-2028.1986.tb00353.x)</a> through Wiley Online Library</li>`,
        publisher: `East African Wild Life Society (EAWLS)`,
        summary: `TBA.`,
        title: `Movement patterns and group size of the African forest elephant <i>Loxodonta africana cyclotis</i> in the Tai National Park, Ivory Coast`,
        type: `Journal article`,
    },
    {
        container: `<i>Animal Behaviour</i> (<i>Anim</i>. <i>Behav</i>.), journal`,
        contributors: `Phyllis C. Lee (author)`,
        date: `February 1987`,
        duration: `pp. 278-291`,
        iteration: `Vol. 35, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/S0003-3472(87)80234-8"target="_blank">From publisher (DOI: 10.1016/S0003-3472(87)80234-8)</a> through ScienceDirect</li>`,
        publisher: `Baillière Tindall`,
        summary: `TBA.`,
        title: `Allomothering among African elephants`,
        type: `Journal article`,
    },
    {
        container: `<i>Proceedings of the Indian Academy of Sciences (Animal Sciences)</i> (<i>Proc</i>. <i>Indian</i> <i>Acad</i>. <i>Sci</i>. (<i>Anim</i>. <i>Sci</i>.)), journal`,
        contributors: `Raman Sukumar (co-author); N.V. Joshi (co-author); V. Krishnamurthy (co-author)`,
        date: `November 1988`,
        duration: `pp. 561-571`,
        iteration: `Vol. 97, Issue 6`,
        languages: `English`,
        links: `<li><a href="https://www.ias.ac.in/describe/article/anml/097/06/0561-0571"target="_blank">From publisher</a></li><li><a href="https://doi.org/10.1007/BF03179558"target="_blank">From SpringerLink (DOI: 10.1007/BF03179558)</a></li>`,
        location: `Bengaluru, India`,
        publisher: `Indian Academy of Sciences`,
        summary: `TBA.`,
        title: `Growth in the Asian elephant`,
        type: `Journal article`,
    },
    {
        container: '<i>IUCN/SSC Action Plans for the Conservation of Biological Diversity</i>, book series',
        contributors: `Charles Santiapillai (compiler); Peter Jackson (compiler); 
        IUCN/SSC Asian Elephant Specialist Group (compiler); Lyn de Alwis (foreword author)`,
        date: `1990`,
        duration: `79 pp.`,
        iteration: `[No. 12]`,
        languages: `English`,
        links: `<li><a href="https://portals.iucn.org/library/node/6042"target="_blank">From publisher</a></li><li><a href="https://www.google.com/books/edition/The_Asian_Elephant/8QcZYzXZJQMC?hl=en&gbpv=1"target="_blank">From Google Books</a>, copy provided by publisher</li>`,
        publisher: `International Union for Conservation of Nature and Natural Resources (IUCN)`,
        summary: `TBA.`,
        title: `The Asian Elephant An Action Plan for Its Conservation`,
        type: `Book`,
    },
    {
        container: `<i>Biological Conservation</i> (<i>Biol</i>. <i>Conserv</i>.), journal`,
        contributors: `R.F.W. Barnes (co-author); A. Blom (co-author); M.P.T. Alers (co-author)`,
        date: `1995, before May`,
        duration: `pp. 125-132`,
        iteration: `Vol. 71, Issue 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/0006-3207(94)00014-H"target="_blank">From publisher (DOI: 10.1016/0006-3207(94)00014-H)</a></li><li><a href="https://www.academia.edu/23491712/A_review_of_the_status_of_forest_elephants_Loxodonta_africana_in_Central_Africa"target="_blank">From Academia</a></li>`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `A Review of the Status of Forest Elephants <i>Loxodonta africana</i> in Central Africa`,
        type: `Journal article`,
    },
    {
        container: `<i>Journal of Zoology, London</i> (<i>J</i>. <i>Zool</i>., <i>Lond</i>.), journal`,
        contributors: `Phyllis C. Lee (co-author); Cynthia J. Moss (co-author)`,
        date: `May 1995`,
        duration: `pp. 29-41`,
        eyedee: `Lee_Moss_1995`,
        iteration: `Vol. 236, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1469-7998.1995.tb01782.x"target="_blank">From publisher (DOI: 10.1111/j.1469-7998.1995.tb01782.x)</a> through Wiley Online Library</li>`,
        publisher: `Zoological Society of London (ZSL)`,
        summary: `TBA.`,
        title: `Statural growth in known-age African elephants (<i>Loxodonta africana</i>)`,
        type: `Journal article`,
    },
    {
        container: `<i>Acta Theriologica</i> (<i>Acta</i> <i>Theriol</i>.), journal`,
        contributors: `Fred Kurt (co-author); Günther B. Hartl (co-author); Ralph Tiedemann (co-author)`,
        date: `12 October 1995 (Tuskless bulls, n.d.)`,
        duration: `pp. 125-143`,
        iteration: `Suppl. 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.4098/at.arch.95-51"target="_blank">From publisher (DOI: 10.4098/at.arch.95-51)</a> through the Digital Repository of the Scientific Institutes</li>`,
        publisher: `Mammal Research Institute Polish Academy of Sciences (MRI PAS)`,
        references: `<ul class="refs">Tuskless bulls in Asian elephant Elephas maximus. History and population genetics of a man-made phenomenon. (n.d.). <i>Scilit</i>. <a href="https://www.scilit.net/article/2eeb3de43a2074f5147565699a2c31c5"target="_blank">https://www.scilit.net/article/2eeb3de43a2074f5147565699a2c31c5</a></ul>`,
        summary: `TBA.`,
        title: `Tuskless bulls in Asian elephant <i>Elephas maximus</i>. History and population genetics of a man-made phenomenon`,
        type: `Journal article`,
    },
    {
        container: '<i>AWF Technical Handbook Series</i>, book series',
        contributors: `Kadzo Kangwana (chapter author, editor); Cynthia J. Moss (chapter author, copy editor); Joyce H. Poole (chapter author); Holly T. Dublin (chapter co-author); Russell D. Taylor (chapter co-author); Susan Mbugua (chapter author); Iain Douglas-Hamilton (chapter author); Richard Barnes (chapter author); Hugo Jachmann (chapter author); Ian J. Whyte (chapter author); Keith Lindsay (chapter author); Phyllis C. Lee (chapter author); Karen McComb (chapter author); Christopher Robert Thouless (chapter author); Hamisi Mutinda (chapter author); Nioroge Ngure (chapter author); Nigel Leader-Williams (chapter author); Deborah Snelson (proofreader); Chryssee Perry Martin (copy editor); Endangered Wildlife Trust (English-to-Portugese translator); Ursula Taube (English-to-French translator)`,
        date: `1996`,
        duration: `178 pp.`,
        iteration: `No. 7`,
        languages: `English, French`,
        links: `<li><a href="https://www.awf.org/about/resources/studying-elephants"target="_blank">English copy from publisher</a></li><li><a href="https://www.awf.org/about/resources/letude-des-elephants"target="_blank">French copy from publisher</a></li><li><a href="https://www.iucn.org/ssc-groups/mammals/african-elephant-specialist-group/tools-studies"target="_blank">English and French copies from the IUCN</a></li>`,
        publisher: `African Wildlife Foundation (AWF)`,
        summary: `TBA.`,
        title: `Studying Elephants`,
        type: `Book`,
    },
    {
        container: `<i>Zeitschrift für Säugetierkunde</i> (<i>Z</i>. <i>Säugetierkd</i>.), journal`,
        contributors: `Günther B. Hartl (co-author); Fred Kurt (co-author); Ralph Tiedemann (co-author); Christine Gmeiner (co-author); K. Nadlinger (co-author); Khyne U Mar (co-author); A. Rübel (co-author)`,
        date: `October 1996`,
        duration: `pp. 285-294`,
        iteration: `Vol. 61, Issue 5`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/zeitschriftfrsu611996deut/page/285/mode/2up?view=theater"target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li>`,
        publisher: `Gustav Fischer Verlag`,
        summary: `TBA.`,
        title: `Population genetics and systematics of Asian elephant (<i>Elephas maximus</i>): A study based on sequence variation at the Cyt b gene of PCR-amplified mitochondrial DNA from hair bulbs`,
        type: `Journal article`,
    },
    {
        container: `<i>Elephant Encyclopedia</i>, website`,
        contributors: `Dan Koehl (author)`,
        date: `Created on or after 17 January 1998<br>Last updated on or after 23 July 2020`,
        duration: `1120 words`,
        languages: `English`,
        links: `<li><a href="https://www.elephant.se/Motty_the_elephant_crossbreed.php?open=Living%20Elephant%20Species"target="_blank">From publisher</a></li>`,
        publisher: `Dan Koehl`,
        summary: `A detailed account of the birth of Motty, the only known hybrid between an Asian and African elephant. It includes communications with zoo staff about Motty's anatomy and nutrition, and a brief discussion on the implications of Motty's birth for elephant taxonomy.`,
        title: `Motty the elephant crossbreed`,
        type: `Web page`,
    },
    {
        container: `<i>Emerging Infectious Diseases</i> (<i>Emerg</i>. <i>Infect</i>. <i>Dis</i>.), journal`,
        contributors: `Kathleen Michalak (co-author); Connie Austin (co-author); Sandy Diesel (co-author); J. Maichle Bacon (co-author); Phil Zimmerman (co-author); Joel N. Maslow (co-author)`,
        date: `June 1998, before 13 June`,
        duration: `pp. 283-287`,
        iteration: `Vol. 4, Issue 2`,
        languages: `English`,
        links: `<li><a href="https://wwwnc.cdc.gov/eid/article/4/2/98-0217_article"target="_blank">From publisher (DOI: 10.3201/eid0402.980217)</a></li><li><a href="http://stacks.cdc.gov/view/cdc/15492/cdc_15492_DS1.pdf"target="_blank">From publisher</a></li><li><a href="https://europepmc.org/article/PMC/2640151"target="_blank">From Europe PMC</a></li><li><a href="https://www.researchgate.net/publication/13663698_Mycobacterium_tuberculosis_infection_as_a_Zoonotic_Disease_Transmission_between_Humans_and_Elephants"target="_blank">From ResearchGate</a></li>`,
        publisher: `National Center for Infectious Diseases`,
        summary: `TBA.`,
        title: `<i>Mycobacterium tuberculosis</i> Infection as a Zoonotic Disease: Transmission between Humans and Elephants`,
        type: `Journal article`,
    },
    {
        container: `<i>Proceedings of the National Academy of Sciences of the United States of America</i> (<i>Proc</i>. <i>Natl</i>. <i>Acad</i>. <i>Sci</i>. <i>U</i>.<i>S</i>.<i>A</i>.; <i>PNAS</i>), journal`,
        contributors: `Michael J. Stanhope (co-author); Victor G. Waddell (co-author); Ole Madsen (co-author); Wilfried de Jong (co-author); S. Blair Hedges (co-author); Gregory C. Cleven (co-author); Diana Kao (co-author); Mark S. Springer (co-author); Roy J. Britten (editor)`,
        date: `18 August 1998`,
        duration: `pp. 9967–9972`,
        iteration: `Vol. 95, Issue 17`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1073/pnas.95.17.9967"target="_blank">From publisher (DOI: 10.1073/pnas.95.17.9967)</a></li><li><a href="https://www.researchgate.net/publication/235608390_Molecular_evidence_for_multiple_origins_of_the_Insectivora_and_for_a_new_order_of_endemic_African_mammals"target="_blank">From ResearchGate</a></li><li><a href="https://www.jstor.org/stable/45590"target="_blank">Print copy from JSTOR</a></li>`,
        publisher: `National Academy of Sciences of the United States of America (NAS)`,
        summary: `TBA.`,
        title: `Molecular evidence for multiple origins of Insectivora and for a new order of endemic African insectivore mammals`,
        type: `Journal article`,
    },
    {
        container: `<i>Trends in Ecology & Evolution</i> (<i>Trends</i> <i>Ecol</i>. <i>Evol</i>.; <i>TREE</i>), journal`,
        contributors: `Jeheskel Shoshani (author); Jann S. Grimes (artist); Gary H. Marchant (artist)`,
        date: `December 1998`,
        duration: `pp. 480-487`,
        iteration: `Vol. 13, Issue 12`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/S0169-5347(98)01491-8"target="_blank">From publisher (DOI: 10.1016/S0169-5347(98)01491-8)</a></li><li><a href="https://www.sciencedirect.com/science/article/abs/pii/S0169534798014918"target="_blank">From ScienceDirect</a></li>`,
        publisher: `Cell Press`,
        summary: `TBA.`,
        title: `Understanding proboscidean evolution: a formidable task`,
        type: `Journal article`,
    },
    {
        container: `<i>Proceedings of the National Academy of Sciences of the United States of America</i> (<i>Proc</i>. <i>Natl</i>. <i>Acad</i>. <i>Sci</i>. <i>U</i>.<i>S</i>.<i>A</i>.; <i>PNAS</i>), journal`,
        contributors: `Ann P. Gaeth (co-author); Roger Valentine Short (co-author); Marilyn B. Renfree (co-author)`,
        date: `11 May 1999`,
        duration: `pp. 5555–5558`,
        iteration: `Vol. 96, Issue 10`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1073/pnas.96.10.5555"target="_blank">From publisher (DOI: 10.1073/pnas.96.10.5555)</a></li><li><a href="https://europepmc.org/article/med/10318922"target="_blank">From Europe PMC</a></li><li><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC21898/"target="_blank">From PubMed Central</a></li><li><a href="https://www.academia.edu/51171605/The_developing_renal_reproductive_and_respiratory_systems_of_the_African_elephant_suggest_an_aquatic_ancestry"target="_blank">From Academia</a></li><li><a href="https://www.researchgate.net/publication/12979580_The_Developing_Renal_Reproductive_and_Respiratory_Systems_of_the_African_Elephant_Suggest_an_Aquatic_Ancestry "target="_blank">From ResearchGate</a></li><li><a href="https://www.jstor.org/stable/48155"target="_blank">Print copy from JSTOR</a></li>`,
        publisher: `National Academy of Sciences of the United States of America (NAS)`,
        summary: `TBA.`,
        title: `The developing renal, reproductive, and respiratory systems of the African elephant suggest an aquatic ancestry`,
        type: `Journal article`,
    },
]