module.exports = [
    {
        container: `<i>Sitzungsberichte der Gesellschaft Naturforschender Freunde zu Berlin</i> (<i>Sitzber</i>. <i>Ges</i>. <i>Naturforsch</i>. <i>Berl</i>.), journal`,
        contributors: `Paul Matschie (author)`,
        date: `1900, on or after 16 October`,
        duration: `pp. 189-197`,
        iteration: `No. 8`,
        languages: `German`,
        links: `<li><a href="https://www.google.com/books/edition/_/W5dOAQAAMAAJ?hl=en&gbpv=1&pg=PA189" target="_blank">From Google Books</a>, copy provided by the University of Illinois at Urbana-Champaign (<a href="https://web.archive.org/web/20210207193625/https://books.googleusercontent.com/books/content?req=AKW5QacuGQQil4EEMX4McXafU8riykOWuKYjcpjliKIDE0bXkrG88aQArnlbHPF2vNnmeGz3T_RwUtQOYsQodCAq3-Tkw1LUV45SF6F7Dg6pqvsntz5lW1-Gl_BPVNvGGrOfPoUoEG0d3rYqpM3_GUvsbgf5BorNzPK48W1gHxg5WAN3kjyULc4CZwgK9ugkE0ht4h8XNFwjO7G-9CKEQGo16CDtMIK98ysqerYQcV9QbBYHi2OGaackuhhql6LK8waAhC_GAjKJ_Kh3KCZNool_7yUA3zb9UMwoI4UOYb4iUFIgCBS41wc" target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/sitzungsberichte1900gese/page/189/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the Harvard University Ernst Mayr Library of the Museum of Comparative Zoology`,
        location: `Berlin, Germany`,
        medium: `Journal article`,
        publisher: `R. Friedländer und Sohn`,
        summary: `TBA.`,
        title: `Über geographische Albarten des afrikanischen Elefanten.`,
    },
    {
        contributors: `George Henry Evans (author)`,
        date: `1901`,
        duration: `343 pp.`,
        eyedee: `Evans_1901`,
        iteration: `3rd ed.`,
        languages: `English`,
        links: `<li><a href="https://digital.nls.uk/indiapapers/browse/archive/75190071" target="_blank">From the National Library of Scotland</a><li><a href="https://archive.org/details/in.ernet.dli.2015.221068/page/n3/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the Digital Library of India<li><a href="https://archive.org/details/TreatiseOnElephants/page/n3/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the Digital Library of India`,
        location: `Rangoon, Burma [Myanmar]`,
        medium: `Book`,
        publisher: `Printed by the Superintendent of Government Printing, Burma`,
        summary: `TBA.`,
        title: `A Treatise On Elephants. Their Treatment in Health and Disease`,
    },
    {
        container: `<i>Proceedings of the General Meetings for Scientific Business of the Zoological Society of London</i> (<i>Proc</i>. <i>Zool</i>. <i>Soc</i>. <i>Lond</i>.), journal`,
        contributors: `Richard Lydekker (author)`,
        date: `1 August 1907 (Back Matter, 1907)`,
        duration: `pp. 380-403`,
        iteration: `[Vol. 77, Issue 2]`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1096-3642.1907.tb01824.x" target="_blank">From publisher (DOI: 10.1111/j.1096-3642.1907.tb01824.x)</a> through Wiley Online Library<li><a href="https://archive.org/details/proceedingsofzoo19071446zool/page/380/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `London, England`,
        medium: `Journal article`,
        publisher: `Printed by Messrs. Longmans, Green, and Co. for the Zoological Society of London`,
        references: `<ul class="refs"><a href="https://archive.org/details/proceedingsofzoo19074471121zool/page/n391/mode/2up?view=theater" target="_blank">[Back Matter]</a>. (1907). <i>Proceedings of the General Meetings for Scientific Business of the Zoological Society of London</i>, <i>78</i>(2).</ul>`,
        summary: `TBA.`,
        title: `1. The Ears as a Race-Character in the African Elephant.`,
    },
    {
        contributors: `Charles A. Williams (author); Arthur Smith Woodward (preface author)`,
        duration: `46 pp.`,
        date: `1908, during or after February`,
        iteration: `1st ed.`,
        languages: `English`,
        links: `<li><a href="https://www.google.com/books/edition/A_Guide_to_the_Elephants_recent_and_Foss/ets4AAAAMAAJ?hl=en&gbpv=1" target="_blank">From Google Books</a>, copy provided by the University of Michigan (<a href="https://web.archive.org/web/20210223141857/https://books.googleusercontent.com/books/content?req=AKW5Qad7gTvfOOCHik8qdqoiErGshGOkxGbiOFsJsd2o2Hq_RrKj0C-D-fIpZnHim4UPZC1fEY1Raz91yDKuf6rvoMSnzgp2o-hr74Cmhrvq8X-sjiRwvS6CV96eZE88ByLrxYQDb_rmrHDVIn3TsN_L4prcL1rA6a2hqav6bpeIXNPLPPuZ91nVSRJ1nDjjAPSlRW7jsucvL-5fO-Q72DaOXv5iStyy2Uju8Llb6R_o2ZIa5nZnFXHi9x56UqJ_Ue7i57DACcE1Z2lMm8cHOxqyLuM0qthXniBX-1s_7FCSgrHGGUTxndY" target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/guidetoelephants00britrich/page/n4/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the University of California Libraries<li><a href="https://archive.org/details/aguidetoelephan00andrgoog/page/n3/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the University of Michigan`,
        location: `London, England`,
        medium: `Book`,
        publisher: `Printed by Taylor & Francis for the Trustees of the British Museum`,
        summary: `TBA.`,
        title: `A Guide to the Elephants (Recent and Fossil) Exhibited in the Department of Geology and Palæontology in the British Museum (Natural History)`,
    },
    {
        contributors: `George Henry Evans (author)`,
        date: `1910, during or after June`,
        duration: `343 pp.`,
        iteration: `4th ed.`,
        languages: `English`,
        links: `<li><a href="https://digital.nls.uk/indiapapers/browse/archive/75192017" target="_blank">From the National Library of Scotland</a><li><a href="https://archive.org/details/elephantstheirdi00evan/page/n10/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries</li><li><a href="https://archive.org/details/cu31924001176878/page/n23/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by Cornell University Libraries<li><a href="https://web.archive.org/web/20190104030414/http://wildpro.twycrosszoo.org/S/00Ref/BooksContents/B212EvansEle/Contents.htm" target="_blank">Digital copy from Wildpro</a>, archived in the Wayback Machine`,
        location: `Rangoon, Burma [Myanmar]`,
        medium: `Book`,
        publisher: `Superintendent of Government Printing, Burma`,
        summary: `The 4th edition of <a id="Evans_1901_color_0" onclick="goToSource('D1900-1999','Evans_1901', this.id)">Evans, 1901</a>. Details TBA.`,
        title: `Elephants and Their Diseases: A Treatise on Elephants`,
    },
    {
        container: `<i>Proceedings of the General Meetings for Scientific Business of the Zoological Society of London</i> (<i>Proc</i>. <i>Zool</i>. <i>Soc</i>. <i>Lond</i>.), journal`,
        contributors: `Richard Lydekker (author)`,
        date: `6 June 1914 (Back Matter, 1914)`,
        duration: `pp. 285-288`,
        iteration: `[Vol. 84], Pt 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1469-7998.1914.tb07036.x" target="_blank">From publisher (DOI: 10.1111/j.1469-7998.1914.tb07036.x)</a> through Wiley Online Library<li><a href="https://archive.org/details/proceedingsofzoo19141490zool/page/285/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `London, England`,
        medium: `Journal article`,
        publisher: `Printed by Messrs. Longmans, Green, and Co. for the Zoological Society of London`,
        references: `<ul class="refs"><a href="https://archive.org/details/proceedingsofzoo19144911077zool/page/n541/mode/2up?view=theater" target="_blank">[Back Matter]</a>. (1914). <i>Proceedings of the General Meetings for Scientific Business of the Zoological Society of London</i>, <i>85</i>(3).</ul>`,
        summary: `TBA.`,
        title: `18. The Malay Race of the Indian Elephant, <i>Elephas maximus hirsutus</i>.`,
    },
    {
        container: `<i>American Museum Novitates</i> (<i>Am</i>. <i>Mus</i>. <i>Novit</i>.), journal`,
        contributors: `Henry Fairfield Osborn (author)`,
        date: `31 January 1921`,
        duration: `15 pp.`,
        iteration: `No. 1`,
        languages: `English`,
        links: `<li><a href="http://digitallibrary.amnh.org/handle/2246/4663" target="_blank">From publisher</a><li><a href="https://www.google.com/books/edition/The_Evolution_Phylogney_and_Classificati/1sUrAAAAYAAJ?hl=en&gbpv=1" target="_blank">From Google Books</a>, copy provided by Harvard University (<a href="https://books.googleusercontent.com/books/content?req=AKW5QaekHU5wcSu3eYcFaNqml2WL1GXkB_30ntZJ0Uuytid-dsE2prNwdpSMZwUW9FSAPor4YEU0YJd-pA3sB8-p7Vze8l10fe7Fz1zEZAxV09uL4c1raNe1ebfj1DIFzmEyqL198vv1tvj8foSQYM7wyOqPSHqVSzwtyQTu3aPY_-n1TyRPExdg-US6p07Qe4D1BuoYsJf8VxxGJEr2jfrq9m41evm-QfNMIwkG8CdqrUOna5Fxim28ZkpefFcoA0vkBLDDmvtTat23kmAjo1deo9jV8C53JJB0a-P0BAkHb2bRxM69ssg" target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/details/americanmuseumno01ameruoft/page/n40/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the University of Toronto`,
        location: `New York City, New York, United States of America`,
        medium: `Journal article`,
        publisher: `Trustees of the American Museum of Natural History (AMNH)`,
        summary: `TBA.`,
        title: `The Evolution, Phylogeny, and Classification of Proboscidea`,
    },
    {
        container: `<i>Proceedings of the Academy of Natural Sciences of Philadelphia</i> (<i>Proc</i>. <i>Acad</i>. <i>Nat</i>. <i>Sci</i>. <i>Phila</i>.), journal`,
        contributors: `Glover M. Allen (author)`,
        date: `10 March 1936`,
        duration: `pp. 15-44`,
        iteration: `Vol. 88`,
        languages: `English`,
        links: `<li><a href="https://www.jstor.org/stable/4064188" target="_blank">From JSTOR</a>`,
        location: `Philadelphia, Pennsylvania, United States of America`,
        medium: `Journal article`,
        publisher: `Academy of Natural Sciences of Philadelphia`,
        summary: `TBA.`,
        title: `Zoological Results of the George Vanderbilt African Expedition of 1934. Part II: The Forest Elephant of Africa`,
    },
    {
        contributors: `Henry Fairfield Osborn (author); Mabel Rice Percy (editor)`,
        date: `15 August 1936`,
        duration: `802 pp.`,
        iteration: `1st ed., Vol. 1 <i>Moeritherioidea, Deinotherioidea, Mastodontoidea</i>`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/proboscideamonog01osbo/page/n12/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the American Museum of Natural History Library`,
        location: `New York City, New York, United States of America`,
        medium: `Book`,
        publisher: `Trustees of the American Museum of Natural History (AMNH); American Museum Press`,
        summary: `TBA.`,
        title: `Proboscidea: A Monograph of the Discovery, Evolution, Migration and Extinction of the Mastodonts and Elephants of the World`,
    },
    {
        container: `<i>Bulletin of the Raffles Museum</i> (<i>Bull</i>. <i>Raffle</i> <i>Mus</i>.), journal`,
        contributors: `Frederick Nutter Chasen (author)`,
        date: `April 1940`,
        duration: `209 pp.`,
        iteration: `No. 15`,
        languages: `English`,
        links: `<li><a href="https://digitalgems.nus.edu.sg/persistent/55001bfc-e505-473e-8b90-aee1d9867ca2" target="_blank">From the Biodiversity Library of Southeast Asia</a> (<a href="https://web.archive.org/web/20200212165718/https://blsea.nus.edu.sg/shared/UPLOADS/JOURNALS/LOW/BulRaf_no15.pdf" target="_blank">archived in the Wayback Machine</a>)<li><a href="https://lkcnhm.nus.edu.sg/wp-content/uploads/sites/10/app/uploads/2017/04/15brmiii-209.pdf" target="_blank">From the Lee Kong Chian Natural History Museum</a>`,
        location: `Singapore`,
        medium: `Journal article`,
        publisher: `Raffles Museum`,
        summary: `On page 190, Chasen recognizes Asian elephants as a single species, <i>Elephas maximus</i>, with three subspecies. He retains <a id="Linnaeus_1758_color_1" onclick="goToSource('D1700-1799','Linnaeus_1758', this.id)">Linnaeus's</a> <i>E</i>. <i>m</i>. <i>maximus</i> for the elephants of Sri Lanka, <a id="Temminck_1847_color_0" onclick="goToSource('D1800-1899','Temminck_1847', this.id)">Temminck's</a> <i>E</i>. <i>m</i>. <i>sumatranus</i> for Sumatran elephants, and <a id="Cuvier_1798_color_1" onclick="goToSource('D1700-1799','Cuvier_1798', this.id)">Cuvier's</a> <i>E</i>. <i>m</i>. <i>indicus</i> for all other living Asian elephants.`,
        title: `A Handlist of Malaysian Mammals`,
    },
    {
        contributors: `Henry Fairfield Osborn (author); Mabel Rice Percy (editor)`,
        date: `1942`,
        duration: `1675 pp.`,
        iteration: `1st ed., Vol. 2 <i>Stegodontoidea, Elephantoidea</i>`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/proboscideamonog02osbo/page/n10/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the American Museum of Natural History Library`,
        location: `New York City, New York, United States of America`,
        medium: `Book`,
        publisher: `Trustees of the American Museum of Natural History (AMNH); American Museum Press`,
        summary: `TBA.`,
        title: `Proboscidea: A Monograph of the Discovery, Evolution, Migration and Extinction of the Mastodonts and Elephants of the World`,
    },
    {
        container: `<i>Földtani Közlöny</i> (<i>Földt</i>. <i>Közlöny</i>), journal`,
        contributors: `Kretzoi Miklós (author)`,
        date: `1950, on or after 17 May`,
        duration: `pp. 405-408`,
        iteration: `Vol. 80, Parts 10-12`,
        languages: `Hungarian`,
        links: `<li><a href="https://archive.org/details/foldtanikozlony8019magy/page/n452/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by the Cornell University Library`,
        location: `Budapest, Hungary`,
        medium: `Journal article`,
        publisher: `Magyarhoni Földtani Társulat`,
        summary: `TBA.`,
        title: `<i>Stegeloxodon</i> nov. gen, a <i>Loxodonta</i> elefántok esetleges ázsiai őse`,
    },
    {
        container: `<i>Journal of Geography</i> (<i>J</i>. <i>Geogr</i>.), journal`,
        contributors: `Charles F. Bennett, Jr. (author)`,
        date: `April 1957`,
        duration: `pp. 168-172`,
        iteration: `Vol. 56, No. 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1080/00221345708983130" target="_blank">From publisher (DOI: 10.1080/00221345708983130)</a> through Taylor & Francis Online`,
        location: `Menasha, Wisconsin, United States of America`,
        medium: `Journal article`,
        publisher: `National Council for Geographic Education (NCGE)`,
        summary: `TBA.`,
        title: `A Brief History of Trained African Elephants in the Belgian Congo`,
    },
    {
        container: `<i>East African Wildlife Journal</i> (<i>East</i> <i>Afr</i>. <i>Wildl</i>. <i>J</i>.), journal`,
        contributors: `Richard M. Laws (author)`,
        date: `August 1966`,
        duration: `pp. 1-37`,
        iteration: `Vol. 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1365-2028.1966.tb00878.x" target="_blank">From publisher (DOI: 10.1111/j.1365-2028.1966.tb00878.x)</a> through Wiley Online Library`,
        location: `Nairobi, Kenya`,
        medium: `Journal article`,
        publisher: `East African Wildlife Society (EAWLS)`,
        summary: `TBA.`,
        title: `Age Criteria for the African Elephant <i>Loxodonta</i> <i>a</i>. <i>africana</i>`,
    },
    {
        container: `<i>Nature</i> (<i>Nat</i>.), journal`,
        contributors: `D.A. Hooijer (author)`,
        date: `22 September 1972`,
        duration: `pp. 228`,
        iteration: `Vol. 239, Issue 5369`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1038/239228a0" target="_blank">From publisher (DOI: 10.1038/239228a0)</a>`,
        location: `London, England`,
        medium: `Journal article`,
        publisher: `Macmillan Journals Limited`,
        summary: `TBA.`,
        title: `Prehistoric Evidence for <i>Elephas maximus</i> L. in Borneo`,
    },
    {
        container: `<i>Mammalian Species</i> (<i>Mamm</i>. <i>Species</i>), journal`,
        contributors: `Larry Laursen (co-author); Marc Bekoff (co-author); Sydney Anderson (principal editor)`,
        date: `6 January 1978`,
        duration: `8 pp.`,
        iteration: `No. 92`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.2307/3503889" target="_blank">From publisher (DOI: 10.2307/3503889)</a> through Oxford Academic<li><a href="https://web.archive.org/web/20130430140501/http://www.science.smith.edu/msi/pdf/i0076-3519-092-01-0001.pdf" target="_blank">From the Smith College Clark Science Center</a>, archived in the Wayback Machine<li><a href="https://www.jstor.org/stable/3503889" target="_blank">From JSTOR</a>`,
        location: `Lawrence, Kansas, United States of America (Birney and Choate, 1994, p. 142)`,
        medium: `Journal article`,
        publisher: `American Society of Mammalogists (ASM)`,
        references: `<ul class="refs">Birney, Elmer F. and Choate, Jerry R. (eds.). (1994). <a href="https://archive.org/details/seventyfiveyears00birn/page/142/mode/2up?view=theater" target="_blank"><i>Seventy Five Years of Mammalogy (1919-1994)</i></a>. Provo, Utah: American Society of Mammalogists.</ul>`,
        summary: `TBA.`,
        title: `<i>Loxodonta africana</i>.`,
    },
    {
        container: `<i>Elephant</i>, journal`,
        contributors: `A.L. Howard (author)`,
        date: `1979, on or after 1 May`,
        duration: `pp. 36-41`,
        iteration: `Vol. 1, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.22237/elephant/1491420381" target="_blank">From Wayne State University DigitalCommons (DOI: 110.22237/elephant/1491420381)</a>`,
        location: `Detroit, Michigan, United States of America`,
        medium: `Journal article`,
        publisher: `Wayne State University Department of Biological Sciences`,
        summary: `TBA.`,
        title: `"Motty"—Birth of an African/Asian Elephant at Chester Zoo`,
    },
    {
        container: `<i>Elephant</i>, journal`,
        contributors: `Jeheskel Shoshani (senior author); Daniel C. Laughlin (dissector); Franz Tisch (dissector); Jim "Chico" Williams (co-author); John D. Taylor (co-author); John W. Cosgriff, Jr. (co-author); William L. Thompson (co-author); Calvin D. Bogart (co-author); Joseph L. Gualtieri (co-author); John Hayden (co-author); Katy Morehead (chief photographer); Richard Bielaczyc (co-author, photographer); Thomas W. Roberts (co-author); Harry Maisel (co-author); Nicholas J. Mizeres (co-author); Victor T. Lakits (co-author); Jim Niedbala (co-author); W.D. Pool (co-author); Richard C. Manikowski and other Science Library Staff (co-author); Gordon W. Rose (co-author); Sandra S. Lash (co-author); Mildred Hurt (co-author);  Michael J. Baccala (co-author); Marlene A. Bulgarelli (co-author); M.  Pamela Bedore (co-author, typist, editor); Anthony Helinski (co-author); George Overbeck (co-author); Susan L. Raymer (co-author); Eyal Shy (co-author); Lee M. Peterson (co-author); Albert Wilson (co-author); Dick Frederick (co-author); Karen L. Spodarek (co-author); Irven O. Buss (reviewer); Richard M. Laws (reviewer); Lawrence D. McGill (reviewer); Sylvia K. Sikes (reviewer); Zirka S. Clark (typist, editor); Eileen D. Koglin (typist, editor); Rick Adler (co-author); Lynne Aldrich (co-author); Krysty Andrews (co-author); Allan Barbish (co-author); Susan Barry (co-author); Ron Battiata (co-author); Fran Beever (co-author); Sue ann Berbenchuk (co-author); Jeanne Blad (co-author); Larry Blad (co-author); George Booth (co-author, photographer); Nate  Bozarth (co-author); Donna Britt (co-author); John Burnet (co-author); Walter Chavin (co-author); Irene Church (co-author); Helen Crowe (co-author); Richard D. Cummings, Terry Cummings, Sherri L. DeFauw (co-author); Leslie Denes (co-author); Efstratios Efthyvoulidis (co-author); Merlin Ekstrom (co-author); Joseph G. Engelhard (co-author); Patrick English (co-author); Don Fairchild, Jr. (co-author); Carla Fisher (co-author); Kevin Frahm (co-author); Susan Francis (co-author); Judi Fried (co-author); Theodore Gaskins (co-author); Joanne Gatt (co-author); Wilma Gentles (co-author); Harry G. Goshgarian (co-author); Susan Grabowski (co-author); Debbie Haase (co-author); Kathryn Hajj (co-author); Gary Hall (co-author); Roger Hanson (co-author); Albert Hatche (co-author); Debbie Hawkins (co-author); Chris Heberer (co-author); Shawne R. Henry (co-author); M. Patricia Hensler, Chuck Heyka (co-author); Mike Kemppainen (co-author); Cathy Kendra (co-author); Bonnie Knutsen (co-author); Carl C.M. Knutsen (co-author); Joy Koenig (co-author); Louis Kolodzinski (co-author); Paul Konarske (co-author); Sue Konwinski (co-author); Stephan Kopacz (co-author); Beth Kozak (co-author); Donna M. Laciak, (co-author); David J.  Lowrie (co-author); Susan Lyman (co-author); Frances F. McCormick (co-author); Robert McDonald (co-author); Richard C. Martin (co-author); Willis W. Mathews (co-author); Stuart Meyers (co-author); Joseph Montana (co-author); David Montezinos (co-author); Kathleen M. Morehead (co-author); Pamela Moron (co-author); Audrey Muczynski (co-author); Anthony Muraski (co-author); Sean Murphy (co-author); Charles P. Otto (co-author); Cornelius Perkins, Jr. (co-author); Valerie Pfluke (co-author); Robert Powitz (co-author); Louise Radanovich (co-author); Jose A. Rafols (co-author); Dennis Reefer (co-author); Lisa Rezzonica (co-author); Edward J. Riley, Jr. (co-author); Harold W. Rossmoore (co-author); Lanette Rowland (co-author); Laura Rudy (co-author); Dave Sabo (co-author); Dallas Schneider (co-author); Paul J. Schwikert (co-author); N.O. Seraphinoff (co-author); Peter Singler (co-author); Paul Sklut (co-author); Joseph Skoney (co-author); Donald Smith (co-author); Nan Smith, Charles Storey, Peter J. Sujdak (co-author); Robert Sumner, Curtis J.  Swanson, Todd Tarrant (co-author); Ron Thielman (co-author); Ronnie Thielman (co-author); Linda Walowicz (co-author); Wayne State Fund Staff (co-author); Ann Werling (co-author); Dorit Yehiel (co-author)`,
        date: `1982, on or after 2 May`,
        duration: `pp. 3-93`,
        iteration: `Vol. 2, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.22237/elephant/1521731887" target="_blank">From Wayne State University DigitalCommons (DOI: 10.22237/elephant/1521731887)</a><li><a href="https://core.ac.uk/display/212887158" target="_blank">From CORE</a>`,
        location: `Detroit, Michigan, United States of America`,
        medium: `Journal article`,
        publisher: `Wayne State University Department of Biological Sciences`,
        summary: `TBA.`,
        title: `On the Dissection of a Female Asian Elephant (<u>Elephas</u> <u>maximus</u> <u>maximus</u> Linnaeus, 1758) and Data from Other Elephants`,
    },
    {
        container: `<i>Mammalian Species</i> (<i>Mamm</i>. <i>Species</i>), journal`,
        contributors: `Jeheskel Shoshani (co-author); John F. Eisenberg (co-author); Timothy E. Lawlor (managing editor; Daniel F. Williams (editor); Sydney Anderson (editor); M. Pamela Bedore (typist), Eileen D. Koglin (typist)`,
        date: `18 June 1982`,
        duration: `8 pp.`,
        iteration: `No. 182`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.2307/3504045" target="_blank">From publisher (DOI: 10.2307/3504045)</a> through Oxford Academic<li><a href="http://web.archive.org/web/20150318181534/http://www.science.smith.edu/msi/pdf/i0076-3519-182-01-0001.pdf" target="_blank">From the Smith College Clark Science Center</a>, archived in the Wayback Machine<li><a href="https://repository.si.edu/handle/10088/4414" target="_blank">From Smithsonian Research Online DSpace Repository</a><li><a href="https://www.jstor.org/stable/3504045" target="_blank">From JSTOR</a>`,
        location: `Lawrence, Kansas, United States of America (Birney and Choate, 1994, p. 142)`,
        medium: `Journal article`,
        publisher: `American Society of Mammalogists (ASM)`,
        references: `<ul class="refs">Birney, Elmer F. and Choate, Jerry R. (eds.). (1994). <a href="https://archive.org/details/seventyfiveyears00birn/page/142/mode/2up?view=theater" target="_blank"><i>Seventy Five Years of Mammalogy (1919-1994)</i></a>. Provo, Utah: American Society of Mammalogists.</ul>`,
        summary: `TBA.`,
        title: `<i>Elephas maximus</i>.`,
    },
    {
        container: `<i>Bulletin of the Psychonomic Society</i> (<i>Bull</i>. <i>Psychon</i>. <i>Soc</i>.), journal`,
        contributors: `Ronald K. Siegel (co-author); Mark Brodie (co-author)`,
        date: `July 1984`,
        duration: `pp. 49-52`,
        iteration: `Vol. 22, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.3758/BF03333758" target="_blank">From publisher (DOI: 10.3758/BF03333758)</a> through SpringerLink`,
        location: `Chicago, Illinois, United States of America`,
        medium: `Journal article`,
        publisher: `Psychonomic Society`,
        summary: `TBA.`,
        title: `Alcohol self-administration by elephants`,
    },
    {
        container: `<i>African Journal of Ecology</i> (<i>Afr</i>. <i>J</i>. <i>Ecol</i>.), journal`,
        contributors: `G. Merz (author)`,
        date: `June 1986`,
        duration: `pp. 133-136`,
        iteration: `Vol. 24, Issue 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1365-2028.1986.tb00353.x" target="_blank">From publisher (DOI: 10.1111/j.1365-2028.1986.tb00353.x)</a> through Wiley Online Library`,
        location: `Nairobi, Kenya`,
        medium: `Journal article`,
        publisher: `East African Wildlife Society (EAWLS)`,
        summary: `TBA.`,
        title: `Movement patterns and group size of the African forest elephant <i>Loxodonta africana cyclotis</i> in the Tai National Park, Ivory Coast`,
    },
    {
        container: `<i>Animal Behavior</i> (<i>Anim</i>. <i>Behav</i>.), journal`,
        contributors: `Phyllis C. Lee (author)`,
        date: `February 1987`,
        duration: `pp. 278-291`,
        iteration: `Vol. 35, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/S0003-3472(87)80234-8" target="_blank">From publisher (DOI: 10.1016/S0003-3472(87)80234-8)</a> through Elsevier`,
        location: `London, England`,
        medium: `Journal article`,
        publisher: `Association for the Study of Animal Behaviour (ASAB)`,
        summary: `TBA.`,
        title: `Allomothering among African elephants`,
    },
    {
        container: '<i>IUCN/SSC Action Plans for the Conservation of Biological Diversity</i>, book series',
        contributors: `Charles Santiapillai (compiler); Peter Jackson (compiler); 
        IUCN/SSC Asian Elephant Specialist Group (compiler); Lyn de Alwis (foreword author)`,
        date: `1990`,
        duration: `79 pp.`,
        iteration: `No. 12`,
        languages: `English`,
        links: `<li><a href="https://portals.iucn.org/library/node/6042" target="_blank">From publisher</a><li><a href="https://www.google.com/books/edition/The_Asian_Elephant/8QcZYzXZJQMC?hl=en&gbpv=1" target="_blank">From Google Books</a>, copy provided by publisher`,
        location: `Gland, Switzerland`,
        medium: `Book`,
        publisher: `International Union for Conservation of Nature and Natural Resources (IUCN)`,
        summary: `TBA.`,
        title: `The Asian Elephant: An Action Plan for Its Conservation`,
    },
    {
        container: `<i>Journal of Zoology London</i> (<i>J</i>. <i>Zool</i>. <i>Lond</i>.), journal`,
        contributors: `Phyllis C. Lee (co-author); Cynthia J. Moss (co-author)`,
        date: `May 1995`,
        duration: `pp. 29-41`,
        eyedee: `Lee_Moss_1995`,
        iteration: `Vol. 236, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1469-7998.1995.tb01782.x" target="_blank">From publisher (DOI: 10.1111/j.1469-7998.1995.tb01782.x)</a> through Wiley Online Library`,
        location: `London, England`,
        medium: `Journal article`,
        publisher: `Zoological Society of London (ZSL)`,
        summary: `TBA.`,
        title: `Statural growth in known‐age African elephants (<i>Loxodonta africana</i>)`,
    },
    {
        container: `<i>Acta Theriologica</i> (<i>Acta</i> <i>Theriol</i>.), journal`,
        contributors: `Fred Kurt (co-author); Günther B. Hartl (co-author); Ralph Tiedemann (co-author)`,
        date: `12 October 1995 (Tuskless bulls, n.d.)`,
        duration: `pp. 125-143`,
        iteration: `Suppl. 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.4098/at.arch.95-51" target="_blank">From publisher (DOI: 10.4098/at.arch.95-51</a> through Repozytorium Cyfrowe Instytutów Naukowych`,
        location: `Białowieża, Poland`,
        medium: `Journal article`,
        publisher: `Mammal Research Institute of the Polish Academy of Sciences`,
        references: `<ul class="refs">Tuskless bulls in Asian elephant Elephas maximus. History and population genetics of a man-made phenomenon. (n.d.). <i>Scilit</i>. <a href="https://www.scilit.net/article/2eeb3de43a2074f5147565699a2c31c5" target="_blank">https://www.scilit.net/article/2eeb3de43a2074f5147565699a2c31c5</a></ul>`,
        summary: `TBA.`,
        title: `Tuskless bulls in Asian elephant <i>Elephas maximus</i>. History and population genetics of a man-made phenomenon`,
    },
    {
        container: `<i>Biological Conservation</i> (<i>Biol</i>. <i>Conserv</i>.), journal`,
        contributors: `R.F.W. Barnes (co-author); A. Blom (co-author); M.P.T. Alers (co-author)`,
        date: `1995, before 27 November`,
        duration: `pp. 125-132`,
        iteration: `Vol. 71, Issue 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/0006-3207(94)00014-H" target="_blank">From publisher (DOI: 10.1016/0006-3207(94)00014-H)</a><li><a href="https://www.academia.edu/23491712/A_review_of_the_status_of_forest_elephants_Loxodonta_africana_in_Central_Africa" target="_blank">From Academia</a>`,
        location: `Oxford, England`,
        medium: `Journal article`,
        publisher: `Elsevier Science Limited`,
        summary: `TBA.`,
        title: `A review of the status of forest elephants <i>Loxodonta africana</i> in Central Africa`,
    },
    {
        container: '<i>AWF Technical Handbook Series</i>,  handbook series',
        contributors: `Kadzo Kangwana (editor, chapter author); Cynthia J. Moss (chapter author, copy editor); Joyce H. Poole (chapter author); Holly T. Dublin (chapter co-author); Russell Taylor (chapter co-author); Susan Mbugua (chapter author); Iain Douglas-Hamilton (chapter author); Richard Barnes (chapter author); Hugo Jachmann (chapter author); I. J. White (chapter author); Keith Lindsay (chapter author); Phyllis C. Lee (chapter author); Karen McComb (chapter author); Chris Thouless (chapter author); Hamisi Mutinda (chapter author); Nioroge Ngure (chapter author); Nigel Leader-Williams (chapter author); Ian Whyte (chapter author); Deborah Snelson (proof-reader); Chryssee Perry Martin (copy editor); Endangered Wildlife Trust (English-to-Portugese translator); Ursula Taube (English-to-French translator)`,
        date: `1996`,
        duration: `178 pp.`,
        iteration: `No. 7`,
        languages: `English, French`,
        links: `<li><a href="https://www.awf.org/about/resources/studying-elephants" target="_blank">English copy from publisher</a><li><a href="https://www.awf.org/about/resources/letude-des-elephants" target="_blank">French copy from publisher</a>`,
        location: `Nairobi, Kenya`,
        medium: `Digital handbook`,
        publisher: `African Wildlife Foundation (AWF)`,
        summary: `TBA.`,
        title: `Studying Elephants`,
    },
    {
        container: `<i>Zeitschrift für Säugetierkunde</i> (<i>Z</i>. <i>Saugetierkd</i>.), journal`,
        contributors: `Günther B. Hartl (co-author); Fred Kurt (co-author); Ralph Tiedemann (co-author); Christine Gmeiner (co-author); K. Nadlinger (co-author); Khyne U. Mar (co-author); A. Rübel (co-author)`,
        date: `October 1996`,
        duration: `pp. 285-294`,
        iteration: `Vol. 61, No. 5`,
        languages: `English`,
        links: `<li><a href="https://archive.org/details/zeitschriftfrsu611996deut/page/285/mode/2up?view=theater" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
        location: `Jena, Germany`,
        medium: `Journal article`,
        publisher: `Gustav Fischer`,
        summary: `TBA.`,
        title: `Population genetics and systematics of Asian elephant (<i>Elephas maximus</i>): A study based on sequence variation at the Cyt b gene of PCR-amplified mitochondrial DNA from hair bulbs`,
    },
    {
        container: `<i>Elephant Encyclopedia</i>, website`,
        contributors: `Dan Koehl (author)`,
        date: `Created on or after 17 January 1998, last updated on or after 23 July 2020`,
        duration: `1120 words`,
        languages: `English`,
        links: `<li><a href="https://www.elephant.se/Motty_the_elephant_crossbreed.php?open=Living%20Elephant%20Species" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Web page`,
        publisher: `Dan Koehl`,
        summary: `A detailed summary of the birth of Motty, the only known hybrid between an Asian and African elephant. Includes firsthand information about his anatomy and nutrition from zoo staff, and a discussion of current elephant taxonomy.`,
        title: `Motty the elephant crossbreed`,
    },
    {
        container: `<i>Emerging Infectious Diseases</i> (<i>Emerg</i>. <i>Infect</i>. <i>Dis</i>.), digital journal`,
        contributors: `Kathleen Michalak (co-author); Connie Austin (co-author); Sandy Diesel (co-author); J. Maichle Bacon (co-author); Phil Zimmerman (co-author); Joel N. Maslow (co-author)`,
        date: `June 1998, before 13 June`,
        duration: `pp. 283-287`,
        iteration: `Vol. 4, No. 2`,
        languages: `English`,
        links: `<li><a href="https://wwwnc.cdc.gov/eid/article/4/2/98-0217_article" target="_blank">From publisher (DOI: 10.3201/eid0402.980217)</a><li><a href="http://stacks.cdc.gov/view/cdc/15492/cdc_15492_DS1.pdf" target="_blank">From publisher</a><li><a href="https://europepmc.org/article/PMC/2640151" target="_blank">From Europe PMC</a><li><a href="https://www.researchgate.net/publication/13663698_Mycobacterium_tuberculosis_infection_as_a_Zoonotic_Disease_Transmission_between_Humans_and_Elephants" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digital journal article`,
        publisher: `Centers for Disease Control and Prevention (CDC)`,
        summary: `TBA.`,
        title: `<i>Mycobacterium tuberculosis</i> infection as a Zoonotic Disease: Transmission between Humans and Elephants`,
    },
    {
        container: `<i>Proceedings of the National Academy of Sciences of the United States of America</i> (<i>Proc</i>. <i>Natl</i>. <i>Acad</i>. <i>Sci</i>. <i>U</i>.<i>S</i>.<i>A</i>., <i>PNAS</i>), digital journal`,
        contributors: `Michael J. Stanhope (co-author); Victor G. Waddell (co-author); Ole Madsen (co-author); Wilfried de Jong (co-author); S. Blair Hedges (co-author); Gregory C. Cleven (co-author); Diana Kao (co-author); Mark S. Springer (co-author)`,
        date: `18 August 1998`,
        duration: `pp. 9967–9972`,
        iteration: `Vol. 95, No. 17`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1073/pnas.95.17.9967" target="_blank">From publisher (DOI: 10.1073/pnas.95.17.9967)</a><li><a href="https://www.researchgate.net/publication/235608390_Molecular_evidence_for_multiple_origins_of_the_Insectivora_and_for_a_new_order_of_endemic_African_mammals" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digital journal article`,
        publisher: `National Academy of Sciences (NAS)`,
        summary: `TBA.`,
        title: `Molecular evidence for multiple origins of Insectivora and for a new order of endemic African insectivore mammals`,
    },
    {
        container: `<i>Trends in Ecology and Evolution</i> (<i>Trends</i> <i>Ecol</i>. <i>Evol</i>., <i>TREE</i>), digital journal`,
        contributors: `Jeheskel Shoshani (author)`,
        date: `1 December 1998`,
        duration: `pp. 480-487`,
        iteration: `Vol. 13, No. 12`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/S0169-5347(98)01491-8" target="_blank">From publisher (DOI: 10.1016/S0169-5347(98)01491-8)</a><li><a href="https://www.sciencedirect.com/science/article/abs/pii/S0169534798014918" target="_blank">From Elsevier</a>`,
        location: `N/A`,
        medium: `Digital journal article`,
        publisher: `Cell Press`,
        summary: `TBA.`,
        title: `Understanding proboscidean evolution: a formidable task`,
    },
]
