module.exports = [
    {
        container: `<i>Elephant</i>, physically published academic journal`,
        contributors: `Peter Grubb (coauthor); Colin P. Groves (coauthor); Joseph P. Dudley (coauthor); Jeheskel Shoshani (coauthor)`,
        date: `2000/01`,
        duration: `pp. 1-4`,
        iteration: `Vol. 2, No. 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.22237/elephant/1521732169" target="_blank">From Wayne State University DigitalCommons (DOI: 10.22237/elephant/1521732169)</a>`,
        location: `Bloomfield Hills, Michigan, United States of America`,
        medium: `Physically published academic journal article, digitized`,
        publisher: `Elephant Research Foundation (ERF)`,
        summary: `TBA.`,
        title: `Living African Elephants Belong to Two Species: <i>Loxodonta africana</i> (Blumenbach, 1797) and <i>Loxodonta cyclotis</i> (Matschie, 1900)`,
    },
    {
        container: `<i>Elephant</i>, physically published academic journal`,
        contributors: `Colin P. Groves (coauthor); Peter Grubb (coauthor)`,
        date: `2000/01`,
        duration: `pp. 4-7`,
        iteration: `Vol. 2, No. 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.22237/elephant/1521732173" target="_blank">From Wayne State University DigitalCommons (DOI: 10.22237/elephant/1521732173)</a>`,
        location: `Bloomfield Hills, Michigan, United States of America`,
        medium: `Physically published academic journal article, digitized`,
        publisher: `Elephant Research Foundation (ERF)`,
        summary: `TBA.`,
        title: `Do <i>Loxodonta cyclotis</i> and <i>L</i>. <i>africana</i> Interbreed?`,
    },
    {
        container: `<i>Heredity</i> (<i>Hered</i>.), digitally published academic journal`,
        contributors: `Prithiviraj Fernando (coauthor); Michael E. Pfrender (coauthor); Sandra E. Encalada (coauthor); Russell Lande (coauthor)`,
        date: `2000/03/01`,
        duration: `pp. 362-372`,
        iteration: `Vol. 84`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1046/j.1365-2540.2000.00674.x" target="_blank">From publisher (DOI: 10.1046/j.1365-2540.2000.00674.x)</a><li><a href="https://www3.nd.edu/~mpfrende/PDFs/Fernando%20et%20al%20Heredity%202000.pdf" target="_blank">From the University of Notre Dame</a><li><a href="https://www.researchgate.net/publication/290500155_Mitochondrial_DNA_variation_phylogeography_and_population_structure_of_the_Asian_elephant" target="_blank">From ResearchGate</a><li><a href="https://www.researchgate.net/publication/12554926_Fernando_P_Pfrender_ME_Encalada_SE_Lande_R_Mitochondrial_DNA_variation_phylogeography_and_population_structure_of_the_Asian_elephant_Heredity_84_362-372" target="_blank">From ResearchGate</a>`,
        location: `London, England`,
        medium: `Digitally published academic journal article`,
        publisher: `Nature Publishing Group`,
        summary: `TBA.`,
        title: `Mitochondrial DNA variation, phylogeography and population structure of the Asian elephant`,
    },
    {
        container: `<i>News in Physiological Sciences</i> (<i>News</i> <i>Physiol</i>. <i>Sci</i>., <i>NIPS</i>), digitally published academic journal`,
        contributors: `John B. West (author)`,
        date: `2002/04/01`,
        duration: `pp. 47-50`,
        iteration: `Vol. 17, Issue 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1152/nips.01374.2001" target="_blank">From publisher (DOI: 10.1152/nips.01374.2001)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `American Physiological Society (APS)`,
        summary: `TBA.`,
        title: `Why Doesn't the Elephant Have a Pleural Space?`,
    },
    {
        container: `<i>Quaternary Science Reviews</i> (<i>Quat</i>. <i>Sci</i>. <i>Rev</i>.), digitally published academic journal`,
        contributors: `Anthony J. Stuart (coauthor); Leopold D. Sulerzhitsky (coauthor); Lyobov A. Orlova (coauthor); Yaroslav V. Kuzmind (coauthor); Adrian M. Lister (coauthor)`,
        date: `2002/05/28`,
        duration: `pp. 1559-1569`,
        iteration: `Vol. 21, Issues 14-15`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/S0277-3791(02)00026-4" target="_blank">From publisher (DOI: 10.1016/S0277-3791(02)00026-4)</a><li><a href="https://www.researchgate.net/publication/222655225_The_latest_woolly_mammoths_Mammuthus_primigenius_Blumenbach_in_Europe_and_Asia" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `The latest woolly mammoths (<i>Mammuthus primigenius</i> Blumenbach) in Europe and Asia: a review of the current evidence`,
    },
    {
        container: `<i>PLoS Biology</i> (<i>PLoS</i> <i>Biol</i>.), digitally published academic journal`,
        contributors: `Prithiviraj Fernando (coauthor); T.N.C. Vidya (coauthor); John Payne (coauthor); Michael Stuewe (coauthor); Geoffrey Davison (coauthor); Raymond J. Alfred (coauthor); Patrick Andau (coauthor); Edwin Bosi (coauthor); Annelisa Kilbourn (coauthor); Don J. Melnick (coauthor)`,
        date: `2003/08/18`,
        duration: `pp. 110-115`,
        iteration: `Vol. 1, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1371/journal.pbio.0000006" target="_blank">From publisher (DOI: 10.1371/journal.pbio.0000006)</a><li><a href="https://academiccommons.columbia.edu/doi/10.7916/D8W958ZZ" target="_blank">From Columbia University Libraries</a><li><a href="https://www.researchgate.net/publication/6233845_DNA_Analysis_Indicates_That_Asian_Elephants_Are_Native_to_Borneo_and_Are_Therefore_a_High_Priority_for_Conservation" target="_blank">From ResearchGate</a><li><a href="https://fh-sites.imgix.net/sites/4169/2020/06/17185748/fernando_2003.pdf" target="_blank">From imgIX</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Public Library of Science (PLoS)`,
        summary: `TBA.`,
        title: `DNA Analysis Indicates That Asian Elephants Are Native to Borneo and Are Therefore a High Priority for Conservation`,
    },
    {
        container: `<i>Physiological and Biochemical Zoology: Ecological and Evolutionary Approaches</i> (<i>Physiol</i>. <i>Biochem</i>. <i>Zool</i>.), digitally published academic journal`,
        contributors: `Kathleen E. Hunt (coauthor); Samuel K. Wasser (coauthor)`,
        date: `2003/≥12`,
        duration: `pp. 918-928`,
        iteration: `Vol. 76, No. 6`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1086/380209" target="_blank">From publisher (DOI: 10.1086/380209)</a><li><a href="https://www.jstor.org/stable/10.1086/380209" target="_blank">From JSTOR</a><li><a href="https://www.researchgate.net/publication/5384225_Effect_of_Long-Term_Preservation_Methods_on_Fecal_Glucocorticoid_Concentrations_of_Grizzly_Bear_and_African_Elephant" target="_blank">From ResearchGate</a>`,
        location: `Chicago, Illinois, United States of America`,
        medium: `Digitally published academic journal article`,
        publisher: `The University of Chicago Press`,
        summary: `TBA.`,
        title: `Effect of Long‐Term Preservation Methods on Fecal Glucocorticoid Concentrations of Grizzly Bear and African Elephant`,
    },
    {
        container: `<i>Quaternary International</i> (<i>Quat</i>. <i>Int</i>.), digitally published academic journal`,
        contributors: `Jeheskel Shoshani (coauthor); Pascal Tassy (coauthor)`,
        date: `2004/06/26`,
        duration: `pp. 5-20`,
        iteration: `Vols. 126-128 <i>Studying Proboscideans: knowledge, Problems and Perspectives. Selected papers from "The world of Elephants" Congress, Rome</i>`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.quaint.2004.04.011" target="_blank">From publisher (DOI: 10.1016/j.quaint.2004.04.011)</a><li><a href="http://biochem.flas.kps.ku.ac.th/elephant.pdf" target="_blank">From Envi Biochem KPS ชีวเคมี สิ่งแวดล้อม เทคโนโลยีและชีวิต</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `Advances in proboscidean taxonomy & classification, anatomy & physiology, and ecology & behavior`,
    },
    {
        container: `<i>YouTube</i>, published website`,
        contributors: `jawed (uploader)`,
        date: `2005/04/23`,
        duration: `18 s`,
        languages: `English`,
        links: `<li><a href="https://www.youtube.com/watch?v=jNQXAC9IVRw" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published video`,
        publisher: `YouTube`,
        summary: `The first YouTube video, filmed at the elephant exhibit at the San Diego Zoo.`,
        title: `Me at the zoo`,
    },
    {
        container: `<i>Proceedings of the National Academy of Sciences of the United States of America</i> (<i>Proc</i>. <i>Natl</i>. <i>Acad</i>. <i>Sci</i>. <i>U</i>.<i>S</i>.<i>A</i>., <i>PNAS</i>), digitally published academic journal`,
        contributors: `Todd Surovell (coauthor); Nicole Waguespack (coauthor); P. Jeffrey Brantingham (coauthor)`,
        date: `2005/04/26`,
        duration: `pp. 6231–6236`,
        iteration: `Vol. 102, No. 17`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1073/pnas.0501947102" target="_blank">From publisher (DOI: 10.1073/pnas.1720554115)</a><li><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1087946/" target="_blank">From PubMed Central</a><li><a href="https://www.researchgate.net/publication/7906690_Global_archaeological_evidence_for_proboscidean_overkill" target="_blank">From ResearchGate</a><li><a href="https://www.jstor.org/stable/3375282" target="_blank">Digitized physical copy from JSTOR</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `National Academy of Sciences (NAS)`,
        summary: `TBA.`,
        title: `Global archaeological evidence for proboscidean overkill`,
    },
    {
        container: `<i>Genetics</i> (<i>Genet</i>.), digitally published academic journal`,
        contributors: `Shozo Yokoyama (coauthor); Naomi Takenaka (coauthor); Dalen W. Agnew (coauthor); Jeheskel Shoshani (coauthor)`,
        date: `2005/05/01`,
        duration: `pp. 335-344`,
        iteration: `Vol. 170, No. 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1534/genetics.104.039511" target="_blank">From publisher (DOI: 10.1534/genetics.104.039511)</a><li><a href="https://www.researchgate.net/publication/7952815_Elephants_and_Human_Color-Blind_Deuteranopes_Have_Identical_Sets_of_Visual_Pigments" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Genetics Society of America (GSA)`,
        summary: `TBA.`,
        title: `Elephants and Human Color-Blind Deuteranopes Have Identical Sets of Visual Pigments`,
    },
    {
        container: `<i>ScienceDaily</i>, published website`,
        contributors: `Anonymous`,
        date: `2005/12/05`,
        duration: `303 words`,
        languages: `English`,
        links: `<li><a href="https://www.sciencedaily.com/releases/2005/12/051205235555.htm" target="_blank">From publisher</a>`,
        location: `Rockville, Maryland, United States of America`,
        medium: `Digitally published news article`,
        publisher: `ScienceDaily`,
        summary: `A layman-oriented summary of <a id="Morris_et_al_2006_color_0" onclick="goToSource('D2000-2021','Morris_et_al_2006', this.id)">Morris et al., 2006</a>.`,
        title: `Drunken Elephants: The Marula Fruit Myth`,
    },
    {
        container: `<i>National Geographic</i>, digitally published magazine`,
        contributors: `Nicholas Bakalar (author)`,
        date: `2005/12/21`,
        duration: `786 words`,
        languages: `English`,
        links: `<li><a href="https://www.nationalgeographic.com/animals/article/news-elephants-drunk-wild-myth" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published magazine article`,
        publisher: `National Geographic Society`,
        summary: `A layman-oriented summary of <a id="Morris_et_al_2006_color_1" onclick="goToSource('D2000-2021','Morris_et_al_2006', this.id)">Morris et al., 2006</a>, with quotes from one of the paper's coauthors.`,
        title: `Elephants Drunk in the Wild? Scientists Put the Myth to Rest`,
    },
    {
        container: `<i>Physiological and Biochemical Zoology: Ecological and Evolutionary Approaches</i> (<i>Physiol</i>. <i>Biochem</i>. <i>Zool</i>.), digitally published academic journal`,
        contributors: `Steve Morris (coauthor); David Humphreys (coauthor); Dan Reynolds (coauthor)`,
        date: `2006/02/06`,
        duration: `pp. 363-369`,
        eyedee: `Morris_et_al_2006`,
        iteration: `Vol. 79, No. 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1086/499983" target="_blank">From publisher (DOI: 10.1086/499983)</a><li><a href="http://www.bio.bris.ac.uk/research/morlab/Morris%20et%20al%20%5BPBZ%5D%202006.pdf" target="_blank">From the University of Bristol's School of Biological Sciences</a><li><a href="https://www.jstor.org/stable/10.1086/499983" target="_blank">From JSTOR</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `The University of Chicago Press`,
        summary: `TBA.`,
        title: `Myth, Marula, and Elephant: An Assessment of Voluntary Ethanol Intoxication of the African Elephant (<i>Loxodonta africana</i>) Following Feeding on the Fruit of the Marula Tree (<i>Sclerocarya birrea</i>)`,
    },
    {
        container: `<i>Brain Research Bulletin</i> (<i>Brain</i> <i>Res</i>. <i>Bull</i>.), digitally published academic journal`,
        contributors: `Jeheskel Shoshani (coauthor); William J. Kupsky (coauthor); Gary H. Marchant (coauthor)`,
        date: `2006/04/18`,
        duration: `pp. 124-157`,
        iteration: `Vol. 70, Issue 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.brainresbull.2006.03.016" target="_blank">From publisher (DOI: 10.1016/j.brainresbull.2006.03.016)</a><li><a href="http://drnissani.net/MNISSANI/ElephantCorner/ElephantBrain_shoshani.pdf" target="_blank">From Moti Nissani's Webpage</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `Elephant brain: Part I: Gross morphology, functions, comparative anatomy, and evolution`,
    },
    {
        container: `<i>Applied Animal Behaviour Science</i> (<i>Appl</i>. <i>Anim</i>. <i>Behav</i>. <i>Sci</i>.), digitally published academic journal`,
        contributors: `Iain Douglas-Hamilton (coauthor); Shivani Bhalla (coauthor); George Wittemyer (coauthor); Fritz Vollrath (coauthor)`,
        date: `2006/06/27`,
        duration: `pp. 87-102`,
        iteration: `Vol. 100, Issues 1-2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.applanim.2006.04.014" target="_blank">From publisher (DOI: 10.1016/j.applanim.2006.04.014)</a><li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.588.1305" target="_blank">From CiteSeerX</a><li><a href="https://web.archive.org/web/20121127020837/http://www.savetheelephants.org/files/pdf/publications/2006%20Douglas-Hamilton%20et%20al%20Behavioural%20reactions%20of%20elephants%20to%20a%20dying%20matriarch.pdf" target="_blank">From Save the Elephants</a>, archived in the Wayback Machine`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `Behavioural reactions of elephants towards a dying and deceased matriarch`,
    },
    {
        container: `<i>PLoS Biology</i> (<i>PLoS</i> <i>Biol</i>.), digitally published academic journal`,
        contributors: `Liza Gross (author)`,
        date: `2007/04/03`,
        duration: `pp. 0001-0003`,
        iteration: `Vol. 5, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1371/journal.pbio.0050115" target="_blank">From publisher (DOI: 10.1371/journal.pbio.0050115)</a>`,
        location: `N/A`,
        medium: `Digitally published article`,
        publisher: `Public Library of Science (PLoS)`,
        summary: `A layman-oriented summary of <a id="Blake_et_al_2007_color_0" onclick="goToSource('D2000-2021','Blake_et_al_2007', this.id)">Blake et al., 2007</a>.`,
        title: `In the Shadows of the Congo Basin Forest, Elephants Fall to the Illegal Ivory Trade`,
    },
    {
        container: `<i>PLoS Biology</i> (<i>PLoS</i> <i>Biol</i>.), digitally published academic journal`,
        contributors: `Stephen Blake (coauthor); Samantha Strindberg (coauthor); Patrick Boudjan (coauthor); Calixte Makombo (coauthor); Inogwabini Bila-Isia (coauthor); Omari Ilambu (coauthor); Falk Grossmann (coauthor); Lambert Bene-Bene (coauthor); Bruno de Semboli (coauthor); Valentin Mbenzo (coauthor); Dino S'hwa (coauthor); Rosine Bayogo (coauthor); Liz Williamson (coauthor); Mike Fay (coauthor); John Hart (coauthor); Fiona Maisels (coauthor)`,
        date: `2007/04/03`,
        duration: `pp. 0945-0953`,
        eyedee: `Blake_et_al_2007`,
        iteration: `Vol. 5, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1371/journal.pbio.0050111" target="_blank">From publisher (DOI: 10.1371/journal.pbio.0050111)</a><li><a href="https://dspace.stir.ac.uk/handle/1893/1176#.YCfc_3WYXx4" target="_blank">From the University of Stirling Online Research Repository (STORRE)</a><li><a href="https://www.academia.edu/11927981/Forest_elephant_crisis_in_the_Congo_Basin" target="_blank">From Academia</a><li><a href="https://www.academia.edu/12991147/Forest_Elephant_Crisis_in_the_Congo_Basin" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/6415339_Forest_Elephant_Crisis_in_the_Congo_Basin" target="_blank">From ResearchGate</a><li><a href="https://www.researchgate.net/publication/215934739_Forest_elephant_crisis_in_the_Congo_Basin" target="_blank">From ResearchGate</a><li><a href="https://www.sciencebuzz.com/forest-elephant-crisis-in-the-congo-basin/" target="_blank">From Science Buzz</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Public Library of Science (PLoS)`,
        summary: `TBA.`,
        title: `Forest Elephant Crisis in the Congo Basin`,
    },
    {
        container: `<i>Journal of Anatomy</i> (<i>J</i>. <i>Anat</i>.), digitally published academic journal`,
        contributors: `D.M. Bouley (coauthor); C.N. Alarcón (coauthor); Thomas Hildebrandt (coauthor); Caitlin E. O’Connell‐Rodwell (coauthor)`,
        date: `2007/08/15`,
        duration: `pp. 428-435`,
        iteration: `Vol. 211, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1469-7580.2007.00792.x" target="_blank">From publisher (DOI: 10.1111/j.1469-7580.2007.00792.x)</a><li><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2375831/" target="_blank">From PubMed Central</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Wiley Online Library on behalf of the Anatomical Society (AS)`,
        summary: `TBA.`,
        title: `The distribution, density and three‐dimensional histomorphology of Pacinian corpuscles in the foot of the Asian elephant (<i>Elephas maximus</i>) and their potential role in seismic communication`,
    },
    {
        container: `<i>Molecular Ecology</i> (<i>Mol</i>. <i>Ecol</i>.), digitally published academic journal`,
        contributors: `Elizabeth A. Archie (coauthor); Julie A. Hollister‐Smith (coauthor); Joyce H. Poole (coauthor); Phyllis C. Lee (coauthor); Cynthia J. Moss (coauthor); Jésus E. Maldonado (coauthor); Robert C. Fleischer (coauthor); Susan C. Alberts (coauthor)`,
        date: `2007/09/04`,
        duration: `pp. 4138-4148`,
        iteration: `Vol. 16, Issue 19`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1365-294X.2007.03483.x" target="_blank">From publisher (DOI: 10.1111/j.1365-294X.2007.03483.x)</a><li><a href="https://web.archive.org/web/20160308224835/https://sites.biology.duke.edu/albertslab/pdfs/Archie&al_2007.pdf" target="_blank">From the Duke University Department of Biology</a>, archived in the Wayback Machine<li><a href="https://repository.si.edu/handle/10088/6000" target="_blank">From Smithsonian Research Online DSpace Repository</a><li><a href="https://web.archive.org/web/20170110131548/http://www3.nd.edu:80/~earchie/documents/1543inbreeding.pdf" target="_blank">From the University of Notre Dame</a>, archived in the Wayback Machine<li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.515.7606" target="_blank">From CiteSeerX</a><li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.510.5270" target="_blank">From CiteSeerX</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Wiley Online Library`,
        summary: `TBA.`,
        title: `Behavioural inbreeding avoidance in wild African elephants`,
    },
    {
        container: `<i>Current Biology</i> (<i>Curr</i>. <i>Biol</i>.), digitally published academic journal`,
        contributors: `Lucy E. King (coauthor); Iain Douglas-Hamilton (coauthor); Fritz Vollrath (coauthor)`,
        date: `2007/10/09`,
        duration: `2 pp.`,
        iteration: `Vol. 17, Issue 19`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.cub.2007.07.038" target="_blank">From publisher (DOI: 10.1016/j.cub.2007.07.038)</a><li><a href="https://www.sciencedirect.com/science/article/pii/S0960982207017186" target="_blank">From Elsevier</a><li><a href="https://core.ac.uk/download/pdf/82503538.pdf" target="_blank">From CORE</a><li><a href="https://www.researchgate.net/publication/5920247_African_elephants_run_from_the_sound_of_disturbed_bees" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Cell Press`,
        summary: `TBA.`,
        title: `African elephants run from the sound of disturbed bees`,
    },
    {
        container: `<i>South African Journal of Wildlife Research</i> (<i>South</i> <i>Afr</i>. <i>J</i>. <i>Wildl</i>. <i>Res</i>.), digitally published academic journal`,
        contributors: `Jozua J. Viljoen (coauthor); André Ganswindt (coauthor); Johan T. du Toit (coauthor); William R. Langbauer (coauthor)`,
        date: `2008/10/01`,
        duration: `pp. 146-152`,
        iteration: `Vol. 38, No. 2`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.3957/0379-4369-38.2.146" target="_blank">From publisher (DOI: 10.3957/0379-4369-38.2.146)</a> through BioOne<li><a href="https://hdl.handle.net/10520/EJC117293" target="_blank">From publisher</a> through Sabinet African Journals<li><a href="http://hdl.handle.net/2263/9274" target="_blank">From UPSpace Digital Repository</a><li><a href="https://www.researchgate.net/publication/228634063_Translocation_stress_and_faecal_glucocorticoid_metabolite_levels_in_free-ranging_African_savanna_elephants" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Southern African Wildlife Management Association (SAWMA)`,
        summary: `TBA.`,
        title: `Translocation stress and faecal glucocorticoid metabolite levels in free-ranging African savanna elephants`,
    },
    {
        container: `<i>Animal Welfare</i> (<i>Anim</i>. <i>Welf</i>.), digitally published academic journal`,
        contributors: `D.L. Wells (coauthor); R.M. Irwin (coauthor)`,
        date: `2008/11/01`,
        duration: `pp. 335-340`,
        iteration: `Vol. 17, No. 4`,
        languages: `English`,
        links: `<li><a href="https://www.ingentaconnect.com/content/ufaw/aw/2008/00000017/00000004/art00001" target="_blank">From publisher</a> through Ingenta Connect`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Universities Federation for Animal Welfare (UFAW)`,
        summary: `TBA.`,
        title: `Auditory stimulation as enrichment for zoo-housed Asian elephants (<i>Elephas maximus</i>)`,
    },
    {
        container: `<i>Proceedings of the Royal Society B: Biological Sciences</i> (<i>Proc</i>. <i>R</i>. <i>Soc</i>. <i>Lond</i>. <i>B</i> <i>Biol</i>. <i>Sci</i>.), digitally published academic journal`,
        contributors: `T.N.C. Vidya (coauthor); Raman Sukumar (coauthor); Don J. Melnick (coauthor)`,
        date: `2008/11/18`,
        duration: `pp. 893-902`,
        iteration: `Vol. 276, Issue 1658`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rspb.2008.1494" target="_blank">From publisher (DOI: 10.1098/rspb.2008.1494)</a><li><a href="https://www.researchgate.net/publication/23483866_Range-wide_mtDNA_phylogeography_yields_insights_into_the_origins_of_Asian_elephants" target="_blank">From ResearchGate</a><li><a href="https://www.jstor.org/stable/30243964" target="_blank">Digitized physical copy from JSTOR</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Royal Society`,
        summary: `TBA.`,
        title: `Range-wide mtDNA phylogeography yields insights into the origins of Asian elephants`,
    },
    {
        container: `<i>Science</i> (<i>Sci</i>.), digitally published academic journal`,
        contributors: `Ros Clubb (coauthor); Marcus Rowcliffe (coauthor); Phyllis C. Lee (coauthor); Khyne U. Mar (coauthor); Cynthia J. Moss (coauthor); Georgia J. Mason (coauthor)`,
        date: `2008/12/12`,
        duration: `p. 1649`,
        iteration: `Vol. 322, Issue 5908`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1126/science.1164298" target="_blank">From publisher (DOI: 10.1126/science.1164298)</a><li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.940.3314" target="_blank">From CiteSeerX</a><li><a href="https://www.academia.edu/5078924/Compromised_Survivorship_in_Zoo_Elephants" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/23655237_Compromised_Survivorship_in_Zoo_Elephants" target="_blank">From ResearchGate</a><li><a href="https://web.archive.org/web/20090529195253/http://www.elephants.com/media/Compromised%20Survivorship%20in%20Zoo%20Elephants.pdf" target="_blank">From the Elephant Sanctuary</a>, archived in the Wayback Machine<li><a href="https://endcap.eu/wp-content/uploads/2012/06/Compromised-Survivorship-in-Zoo-Elephants-2008-G.-Mason-et-al.pdf" target="_blank">From ENDCAP</a><li><a href="http://www.freewpzelephants.com/wp-content/uploads/2008/12/zoo-life-harmful-to-elephants.pdf" target="_blank">From the Friends of Woodland Park Zoo Elephants</a><li><a href="https://web.archive.org/web/20170808115604/http://www.rufford.org/files/Science%20Vol%20322%2012%20December%202008.pdf" target="_blank">From the Rufford Foundation</a>, archived in the Wayback Machine<li><a href="https://web.archive.org/web/20170809215617/http://www.rufford.org/files/Science%20Clubb%20etal%202008.pdf" target="_blank">From the Rufford Foundation</a>, archived in the Wayback Machine`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `American Association for the Advancement of Science (AAAS)`,
        summary: `TBA.`,
        title: `Compromised Survivorship in Zoo Elephants`,
    },
    {
        container: `<i>Biotropica</i>, digitally published academic journal`,
        contributors: `Ahimsa Campos‐Arceiz (author)`,
        date: `2009/06/29`,
        duration: `pp. 406-407`,
        iteration: `Vol. 41, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1111/j.1744-7429.2009.00525.x" target="_blank">From publisher (DOI: 10.1111/j.1744-7429.2009.00525.x)</a><li><a href="http://www.chm.bris.ac.uk/sillymolecules/shithappens.pdf" target="_blank">From the University of Bristol's School of Chemistry</a><li><a href="https://www.academia.edu/1486428/Shit_Happens_to_be_Useful_Use_of_Elephant_Dung_as_Habitat_by_Amphibians" target="_blank">From Academia</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Wiley Online Library on behalf of the Association for Tropical Biology and Conservation`,
        summary: `TBA.`,
        title: `Shit Happens (to be Useful)! Use of Elephant Dung as Habitat by Amphibians`,
    },
    {
        container: `<i>The Anatomical Record: Advances in Integrative Anatomy and Evolutionary Biology</i> (<i>Anat</i>. <i>Rec</i>.), digitally published academic journal`,
        contributors: `Nancy E. Todd (author)`,
        date: `2009/12/28`,
        duration: `pp. 62-73`,
        iteration: `Vol. 293, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1002/ar.21011" target="_blank">From publisher (DOI: 10.1002/ar.21011)</a> through Wiley Online Library`,
        location: `Rockville, Maryland, United States of America`,
        medium: `Digitally published academic journal article`,
        publisher: `American Association for Anatomy (AAA)`,
        summary: `TBA.`,
        title: `Qualitative Comparison of the Cranio‐Dental Osteology of the Extant Elephants, <i>Elephas maximus</i> (Asian Elephant) and <i>Loxodonta africana</i> (African Elephant)`,
    },
    {
        container: `<i>The Anatomical Record: Advances in Integrative Anatomy and Evolutionary Biology</i> (<i>Anat</i>. <i>Rec</i>.), digitally published academic journal`,
        contributors: `Nancy E. Todd (author)`,
        date: `2009/12/28`,
        duration: `pp. 74-90`,
        iteration: `Vol. 293, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1002/ar.21010" target="_blank">From publisher (DOI: 10.1002/ar.21010)</a> through Wiley Online Library<li><a href="https://www.academia.edu/10092521/New_Phylogenetic_Analysis_of_the_Family_Elephantidae_Based_on_Cranial_Dental_Morphology" target="_blank">From Academia</a>`,
        location: `Rockville, Maryland, United States of America`,
        medium: `Digitally published academic journal article`,
        publisher: `American Association for Anatomy (AAA)`,
        summary: `TBA.`,
        title: `New Phylogenetic Analysis of the Family Elephantidae Based on Cranial‐Dental Morphology`,
    },
    {
        container: `<i>PLoS Biology</i> (<i>PLoS</i> <i>Biol</i>.), digitally published academic journal`,
        contributors: `Nadin Rohland (coauthor); David Reich (coauthor); Swapan Mallick (coauthor); Matthias Meyer (coauthor); Richard E. Green (coauthor); Nicholas J. Georgiadis (coauthor); Alfred L. Roca (coauthor); Michael Hofreiter (coauthor)`,
        date: `2010/12/21`,
        duration: `10 pp.`,
        eyedee: `Rohland_et_al_2010`,
        iteration: `Vol. 8, Issue 12`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1371/journal.pbio.1000564" target="_blank">From publisher (DOI: 10.1371/journal.pbio.1000564)</a><li><a href="https://web.archive.org/web/20151018114203/http://genetics.med.harvard.edu/reichlab/Reich_Lab/Publications_files/2010_Rohland_Mastodon.pdf" target="_blank">From the David Reich Lab</a>, archived in the Wayback Machine<li><a href="http://nrs.harvard.edu/urn-3:HUL.InstRepos:4874828" target="_blank">From Digital Access to Scholarship at Harvard (DASH)</a><li><a href="https://europepmc.org/article/PMC/3006346" target="_blank">From Europe PMC</a><li><a href="https://www.academia.edu/35196283/Genomic_DNA_sequences_from_mastodon_and_woolly_mammoth_reveal_deep_speciation_of_forest_and_savanna_elephants" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/49726374_Genomic_DNA_Sequences_from_Mastodon_and_Woolly_Mammoth_Reveal_Deep_Speciation_of_Forest_and_Savanna_Elephants" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Public Library of Science (PLoS)`,
        summary: `TBA.`,
        title: `Genomic DNA Sequences from Mastodon and Woolly Mammoth Reveal Deep Speciation of Forest and Savanna Elephants`,
    },
    {
        container: `<i>Nature</i> (<i>Nat</i>.), digitally published academic journal`,
        contributors: `Natasha Gilbert (author)`,
        date: `2010/12/21`,
        duration: `549 words`,
        languages: `N/A`,
        links: `<li><a href="https://doi.org/10.1038/news.2010.691" target="_blank">From publisher (DOI: 10.1038/news.2010.691)</a>`,
        location: `London, England`,
        medium: `Digitally published news article`,
        publisher: `Nature Publishing Group`,
        summary: `A layman-oriented summary of <a id="Rohland_et_al_2010_color_0" onclick="goToSource('D2000-2021','Rohland_et_al_2010', this.id)">Rohland et al., 2010</a>, with quotes from one of the paper's coauthors.`,
        title: `African elephants are two distinct species`,
    },
    {
        container: `<i>Smithsonian Magazine</i>, digitally published magazine`,
        contributors: `Laura Helmuth (author)`,
        date: `2010/12/27`,
        duration: `476 words`,
        languages: `N/A`,
        links: `<li><a href="https://www.smithsonianmag.com/science-nature/the-elephant-family-tree-extinct-and-extant-40883904/" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published magazine article`,
        publisher: `Smithsonian`,
        summary: `A layman-oriented summary of <a id="Rohland_et_al_2010_color_1" onclick="goToSource('D2000-2021','Rohland_et_al_2010', this.id)">Rohland et al., 2010</a>.`,
        title: `The Elephant Family Tree, Extinct and Extant`,
    },
    {
        container: `<i>The IUCN Red List of Threatened Species</i>, published website`,
        contributors: `A. Gopala (coauthor, assessor); O. Hadian (coauthor, assessor); Sunarto (coauthor, assessor); A. Sitompul (coauthor, assessor); A. Williams (coauthor, assessor); P. Leimgruber (coauthor, assessor); S.E. Chambliss (coauthor, assessor); D. Gunaryardi (coauthor, assessor); S. Hedges (reviewer); A. Desai (reviewer); M. Tyson (reviewer)`,
        date: `2011/≥08/≥01`,
        duration: `11 pp.`,
        languages: `English`,
        links: `<li><a href="https://dx.doi.org/10.2305/IUCN.UK.2011-2.RLTS.T199856A9129626.en" target="_blank">From publisher (DOI: 10.2305/IUCN.UK.2011-2.RLTS.T199856A9129626.en)</a>`,
        location: `Gland, Switzerland`,
        medium: `Digitally published article`,
        publisher: `International Union for Conservation of Nature (IUCN)`,
        summary: `TBA.`,
        title: `<i>Elephas maximus</i> ssp. <i>sumatranus</i>`,
    },
    {
        container: `<i>Science</i> (<i>Sci</i>.), digitally published academic journal`,
        contributors: `Elizabeth Pennisi (author)`,
        date: `2011/12/22`,
        duration: `816 words`,
        languages: `English`,
        links: `<li><a href="https://www.sciencemag.org/news/2011/12/elephants-have-sixth-toe" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `American Association for the Advancement of Science (AAAS)`,
        summary: `A layman-oriented summary of <a id="Hutchinson_et_al_2011_color_0" onclick="goToSource('D2000-2021','Hutchinson_et_al_2011', this.id)">Hutchinson et al., 2011</a>.`,
        title: `Elephants Have a Sixth 'Toe'`,
    },
    {
        container: `<i>Science</i> (<i>Sci</i>.), digitally published academic journal`,
        contributors: `Josh R. Hutchinson (coauthor); Cyrille Delmer (coauthor); Charlotte E. Miller (coauthor); Thomas Hildebrandt (coauthor); Andrew A. Pitsillides (coauthor); Alan Boyde (coauthor)`,
        date: `2011/12/23`,
        duration: `pp. 1699-1703`,
        eyedee: `Hutchinson_et_al_2011`,
        iteration: `Vol. 334, Issue 6063`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1126/science.1211437" target="_blank">From publisher (DOI: 10.1126/science.aba5991)</a><li><a href="https://www.academia.edu/1491273/From_flat_foot_to_fat_foot_structure_ontogeny_function_and_evolution_of_elephant_sixth_toes" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/51920693_From_Flat_Foot_to_Fat_Foot_Structure_Ontogeny_Function_and_Evolution_of_Elephant_Sixth_Toes" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `American Association for the Advancement of Science (AAAS)`,
        summary: `TBA.`,
        title: `From Flat Foot to Fat Foot: Structure, Ontogeny, Function, and Evolution of Elephant “Sixth Toes”`,
    },
    {
        container: `<i>Brain, Behavior and Evolution</i> (<i>Brain</i> <i>Behav</i>. <i>Evol</i>.), digitally published academic journal`,
        contributors: `Busisiwe C. Maseko (coauthor); Bob Jacobs (coauthor); Muhammad A. Spocter (coauthor); Chet C. Sherwood (coauthor); P.R. Hoff (coauthor); Paul R. Manger (coauthor)`,
        date: `2012/12/29`,
        duration: `pp. 40-55`,
        iteration: `Vol. 81`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1159/000345565" target="_blank">From publisher (DOI: 10.1159/000345565)</a><li><a href="https://web.archive.org/web/20170811055855/https://www.coloradocollege.edu/dotAsset/e0c9b276-e4f9-4dea-8b16-495715d9ff9e.pdf" target="_blank">From Colorado College</a>, archived in the Wayback Machine<li><a href="https://www.researchgate.net/publication/234076293_Qualitative_and_Quantitative_Aspects_of_the_Microanatomy_of_the_African_Elephant_Cerebellar_Cortex" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Karger`,
        summary: `TBA.`,
        title: `Qualitative and Quantitative Aspects of the Microanatomy of the African Elephant Cerebellar Cortex`,
    },
    {
        container: `<i>PLoS ONE</i>, digitally published academic journal`,
        contributors: `Andrea K. Turkalo (coauthor); Peter H. Wrege (coauthor); George Wittemyer (coauthor)`,
        date: `2013/12/26`,
        duration: `12 pp.`,
        iteration: `Vol. 8, Issue 12`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1371/journal.pone.0085154" target="_blank">From publisher (DOI: 10.1371/journal.pone.0085154)</a><li><a href="https://www.academia.edu/13051179/Long_Term_Monitoring_of_Dzanga_Bai_Forest_Elephants_Forest_Clearing_Use_Patterns" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/259567455_Long-Term_Monitoring_of_Dzanga_Bai_Forest_Elephants_Forest_Clearing_Use_Patterns" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Public Library of Science (PLoS)`,
        summary: `TBA.`,
        title: `Long-Term Monitoring of Dzanga Bai Forest Elephants: Forest Clearing Use Patterns`,
    },
    {
        container: `<i>Empire</i>, digitally published magazine`,
        contributors: `Simon Otto (author)`,
        date: `2014/07/10`,
        duration: `941 words`,
        languages: `English`,
        links: `<li><a href="https://www.empireonline.com/movies/features/train-dragon-designs/" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published magazine article`,
        publisher: `Empire`,
        summary: `Simon Otto, then Dreamworks's Head of Character animation, describes the Bewilderbeast from <i>How to Train Your Dragon 2</i> (2014) as part mammoth.`,
        title: `How To Create Your Dragon: The Inspirations Behind The Creatures`,
    },
    {
        container: `<i>Annual Review of Animal Biosciences</i> (<i>Annu</i>. <i>Rev</i>. <i>Anim</i>. <i>Biosci</i>.), digitally published academic journal`,
        contributors: `Alfred L. Roca (coauthor); Yasuko Ishida (coauthor); Adam L. Brandt (coauthor); Neal R. Benjamin (coauthor); Kai Zhao (coauthor); Nicholas J. Georgiadis (coauthor)`,
        date: `2014/12/08`,
        duration: `pp. 139-167`,
        iteration: `Vol. 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1146/annurev-animal-022114-110838" target="_blank">From publisher (DOI: 10.1146/annurev-animal-022114-110838)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Annual Reviews`,
        summary: `TBA.`,
        title: `Elephant Natural History: A Genomic Perspective`,
    },
    {
        container: `<i>Acta Palaeontologica Polonica</i> (<i>Acta</i> <i>Palaeontol</i>. <i>Pol</i>.), digitally published academic journal`,
        contributors: `Asier Larramendi (author)`,
        date: `2015/07/10`,
        duration: `pp. 537-574`,
        eyedee: `Larramendi_2015`,
        iteration: `Vol. 61, No. 3`,
        languages: `English`,
        links: `<li><a href="http://dx.doi.org/10.4202/app.00136.2014" target="_blank">From publisher (DOI: 10.4202/app.00136.2014)</a><li><a href="https://bioone.org/journals/acta-palaeontologica-polonica/volume-61/issue-3/app.00136.2014/Shoulder-Height-Body-Mass-and-Shape-of-Proboscideans/10.4202/app.00136.2014.full" target="_blank">From BioOne</a><li><a href="https://www.researchgate.net/publication/280014062_Shoulder_Height_Body_Mass_and_Shape_of_Proboscideans" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Institute of Palaeobiology of the Polish Academy of Sciences`,
        summary: `TBA.`,
        title: `Shoulder height, body mass and shape of proboscideans`,
    },
    {
        container: `<i>Animal Cognition</i> (<i>Anim</i>. <i>Cogn</i>.), digitally published academic journal`,
        contributors: `Kaori Mizuno (coauthor); Naoko Irie (coauthor); Mariko Hiraiwa-Hasegawa (coauthor); Nobuyuki Kutsukake (coauthor)`,
        date: `2015/11/05`,
        duration: `pp. 215-222`,
        iteration: `Vol. 19`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1007/s10071-015-0929-2" target="_blank">From publisher (DOI: 10.1007/s10071-015-0929-2)</a><li><a href="https://www.researchgate.net/publication/283545065_Asian_elephants_acquire_inaccessible_food_by_blowing" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `SpringerLink`,
        summary: `TBA.`,
        title: `Asian elephants acquire inaccessible food by blowing`,
    },
    {
        container: `<i>Journal of Vertebrate Paleontology</i> (<i>J</i>. <i>Vertebr</i>. <i>Paleontol</i>.), digitally published academic journal`,
        contributors: `W. David Lambert (author); Marcelo Sanchez-Villagra (handling editor)`,
        date: `2016/02/18`,
        duration: `7 pp.`,
        iteration: `Vol. 36, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1080/02724634.2016.1091352" target="_blank">From publisher (DOI: 10.1080/02724634.2016.1091352)</a><li><a href="https://bioone.org/journals/journal-of-vertebrate-paleontology/volume-36/issue-3/02724634.2016.1091352/Eurybelodon-shoshanii-an-Unusual-New-Shovel-Tusked-Gomphothere-Mammalia-Proboscidea/10.1080/02724634.2016.1091352.short" target="_blank">From BioOne</a><li><a href="https://www.academia.edu/22396449/Eurybelodon_shoshanii_an_unusual_new_shovel_tusked_gomphothere_Mammalia_Proboscidea_from_the_late_Miocene_of_Oregon" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/295398216_Eurybelodon_shoshanii_an_unusual_new_shovel-tusked_gomphothere_Mammalia_Proboscidea_from_the_late_Miocene_of_Oregon" target="_blank">From ResearchGate</a><li><a href="https://www.jstor.org/stable/24740329" target="_blank">Digitized physical copy from JSTOR</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Taylor & Francis Group`,
        summary: `TBA.`,
        title: `<i>Eurybelodon shoshanii</i>, an unusual new shovel-tusked gomphothere (Mammalia, Proboscidea) from the late Miocene of Oregon`,
    },
    {
        container: `<i>Nature</i> (<i>Nat</i>.), digitally published academic journal`,
        contributors: `Ewen Callaway (author)`,
        date: `2016/09/16`,
        duration: `569 words`,
        languages: `English`,
        links: `<li><a href="https://www.nature.com/news/elephant-history-rewritten-by-ancient-genomes-1.20622" target="_blank">From publisher</a>`,
        location: `London, England`,
        medium: `Digitally published news article`,
        publisher: `Nature Publishing Group`,
        summary: `A layman-oriented summary of the 2016 announcement of <a id="Palkopoulou_et_al_2018_color_0" onclick="goToSource('D2000-2021','Palkopoulou_et_al_2018', this.id)">Palkopoulou et al., 2018</a>, with quotes from one of the paper's coauthors.`,
        title: `Elephant history rewritten by ancient genomes`,
    },
    {
        container: `<i>State Council</i>, digitally published periodical`,
        contributors: `Anonymous`,
        date: `2016/12/30`,
        duration: `1 p.`,
        iteration: `No. 103`,
        languages: `Chinese`,
        links: `<li><a href="http://www.gov.cn/zhengce/content/2016-12/30/content_5155017.htm" target="_blank">From publisher</a>`,
        location: `Beijing, China`,
        medium: `Digitally published article`,
        publisher: `General Office of the State Council of the People's Republic of China`,
        summary: `TBA.`,
        title: `国务院办公厅关于有序停止商业性加工销售象牙及制品活动的通知`,
    },
    {
        container: `<i>eLife</i>, digitally published academic journal`,
        contributors: `Matthias Meyer (coauthor); Eleftheria Palkopoulou (coauthor); Sina Baleka (coauthor); Mathias Stiller (coauthor); Kirsty E.H. Penkman (coauthor); Kurt W. Alt (coauthor); Yasuko Ishida (coauthor); Dietrich Mania (coauthor); Swapan Mallick (coauthor); Tom Meijer (coauthor); Harald Meller (coauthor); Sarah Nagel (coauthor); Birgit Nickel (coauthor); Sven Ostritz (coauthor); Nadin Rohland (coauthor); Karol Schauer (coauthor); Tim Schüler (coauthor); Alfred L/ Roca (coauthor); David Reich (coauthor); Beth Shapiro (coauthor); Michael Hofreiter (coauthor); Antonis Rokas (reviewing editor)`,
        date: `2017/06/06`,
        duration: `15 pp.`,
        eyedee: `Meyer_et_al_2017`,
        iteration: `No. 6`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.7554/eLife.25413.001" target="_blank">From publisher (DOI: 10.7554/eLife.25413.001)</a><li><a href="https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/elife-25413.pdf" target="_blank">From the David Reich Lab</a><li><a href="https://www.researchgate.net/publication/322204001_Palaeogenomes_of_Eurasian_straight-tusked_elephants_challenge_the_current_view_of_elephant_evolution" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `eLife`,
        summary: `TBA.`,
        title: `Palaeogenomes of Eurasian straight-tusked elephants challenge the current view of elephant evolution`,
    },
    {
        container: `<i>Illinois News Bureau</i>, published website`,
        contributors: `Diana Yates (author)`,
        date: `2017/06/06`,
        duration: `707 words`,
        languages: `English`,
        links: `<li><a href="https://news.illinois.edu/view/6367/510687" target="_blank">From publisher</a><li><a href="https://phys.org/news/2017-06-genetic-elephant-family-tree.html" target="_blank">From Phys.org</a></a><li><a href="https://www.sciencedaily.com/releases/2017/06/170606112809.htm" target="_blank">From ScienceDaily</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `University of Illinois at Urbana-Champaign`,
        summary: `A layman-oriented summary of <a id="Meyer_et_al_2017_color_0" onclick="goToSource('D2000-2021','Meyer_et_al_2017', this.id)">Meyer et al., 2017</a>, with quotes from four of the paper's coauthors.`,
        title: `Genetic study shakes up the elephant family tree`,
    },
    {
        container: `<i>PLoS ONE</i>, digitally published academic journal`,
        contributors: `Robert A.R. Guldemond (coauthor); Andrew Purdon (coauthor); Rudi J. van Aarde (coauthor)`,
        date: `2017/06/07`,
        duration: `12 pp.`,
        iteration: `Vol. 12, Issue 6`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1371/journal.pone.0178935" target="_blank">From publisher (DOI: 10.1371/journal.pone.0178935)</a><li><a href="https://www.semanticscholar.org/paper/A-systematic-review-of-elephant-impact-across-Guldemond-Purdon/683c352d2551b1edce880febed47c3beab5362fc" target="_blank">From Semantic Scholar</a><li><a href="https://www.researchgate.net/publication/317392829_A_systematic_review_of_elephant_impact_across_Africa" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Public Library of Science (PLoS)`,
        summary: `TBA.`,
        title: `A systematic review of elephant impact across Africa`,
    },
    {
        container: `<i>Journal of Vertebrate Paleontology</i> (<i>J</i>. <i>Vertebr</i>. <i>Paleontol</i>.), digitally published academic journal`,
        contributors: `Shi-Qi Wang (coauthor); Yu Li (coauthor); Jaroon Duangkrayom (coauthor); Xiang-Wen Yang (coauthor); Wen He (coauthor); Shan-Qin Chen (coauthor)`,
        date: `2017/06/13`,
        duration: `15 pp.`,
        iteration: `Vol. 37, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1080/02724634.2017.1318284" target="_blank">From publisher (DOI: 10.1080/02724634.2017.1318284)</a><li><a href="https://bioone.org/journals/journal-of-vertebrate-paleontology/volume-37/issue-3/02724634.2017.1318284/A-New-Species-of-Gomphotherium-Proboscidea-Mammalia-from-China-and/10.1080/02724634.2017.1318284.short" target="_blank">From BioOne</a><li><a href="https://www.researchgate.net/publication/317572819_A_new_species_of_Gomphotherium_Proboscidea_Mammalia_from_China_and_the_evolution_of_Gomphotherium_in_Eurasia" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Taylor & Francis Group`,
        summary: `TBA.`,
        title: `A new species of <i>Gomphotherium</i> (Proboscidea, Mammalia) from China and the evolution of Gomphotherium in Eurasia`,
    },
    {
        container: `<i>Der Zoologische Garten</i> (<i>Zool</i>. <i>Gart</i>.), digitally published academic journal`,
        contributors: `Ulrich Schürer (author)`,
        date: `2017/06/20`,
        duration: `pp. 108-166`,
        iteration: `Vol. 86, Issues 1-6`,
        languages: `German, English`,
        links: `<li><a href="https://doi.org/10.1016/j.zoolgart.2017.04.006" target="_blank">From publisher (DOI: 10.1016/j.zoolgart.2017.04.006)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `Über Waldelefanten`,
    },
    {
        container: `<i>Wikimedia Commons</i>, published website`,
        contributors: `Steveoc 86 (illustrator)`,
        date: `2017/10/13`,
        duration: `1920 x 800 px`,
        languages: `English`,
        links: `<li><a href="https://commons.wikimedia.org/wiki/File:African-Elephant-Scale-Chart-SVG-Steveoc86.svg" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published illustration`,
        publisher: `Wikimedia Foundation`,
        summary: `An illustrated comparison of a man's and a woman's heights with the average shoulder height of male, female, adult, and juvenile African bush elephants (<i>Loxodonta africana</i>), as well as the tallest known adult male. Shoulder heights are based on data from <a id="Lee_Moss_1995_color_0" onclick="goToSource('D1900-1999','Lee_Moss_1995', this.id)">Lee and Moss, 1995</a> and <a id="Larramendi_2015_color_0" onclick="goToSource('D2000-2021','Larramendi_2015', this.id)">Larramendi, 2015</a>.`,
        title: `File:African-Elephant-Scale-Chart-SVG-Steveoc86.svg`,
    },
    {
        container: `<i>Zoological Journal of the Linnean Society</i> (<i>Zool</i>. <i>J</i>. <i>Linn</i>. <i>Soc</i>.), digitally published academic journal`,
        contributors: `Advait M. Jukar (coauthor); S. Kathleen Lyons (coauthor); Mark D. Uhen (coauthor)`,
        date: `2018/01/16`,
        duration: `pp. 919-931`,
        iteration: `Vol. 184, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1093/zoolinnean/zlx108" target="_blank">From publisher (DOI: 10.1093/zoolinnean/zlx108)</a>`,
        location: `London, England`,
        medium: `Digitally published academic journal article`,
        publisher: `Linnean Society of London`,
        summary: `TBA.`,
        title: `A cranial correlate of body mass in proboscideans`,
    },
    {
        container: `<i>Scientific Reports</i> (<i>Sci</i>. <i>Rep</i>.), digitally published academic journal`,
        contributors: `Reeta Sharma (coauthor); Benoit Goossens (coauthor); Rasmus Heller (coauthor); Rita Rasteiro (coauthor); Nurzhafarina Othman (coauthor); Michael W. Bruford (coauthor); Lounès Chikhi (coauthor)`,
        date: `2018/01/17`,
        duration: `11 pp.`,
        eyedee: `Sharma_et_al_2018`,
        iteration: `Vol. 8, No. 880`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1038/s41598-017-17042-5" target="_blank">From publisher (DOI: 10.1038/s41598-017-17042-5)</a><li><a href="https://research-information.bris.ac.uk/ws/portalfiles/portal/145867880/Full_text_PDF_final_published_version_.pdf" target="_blank">From the University of Bristol Research Portal</a>`,
        location: `London, England`,
        medium: `Digitally published academic journal article`,
        publisher: `Nature Research`,
        summary: `TBA.`,
        title: `Genetic analyses favour an ancient and natural origin of elephants on Borneo`,
    },
    {
        container: `<i>Phys.org</i>, published website`,
        contributors: `Instituto Gulbenkian de Ciencia (author)`,
        date: `2018/01/17`,
        duration: `545 words`,
        languages: `English`,
        links: `<li><a href="https://phys.org/news/2018-01-mysterious-bornean-elephants.html" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `Science X`,
        summary: `A layman-oriented summary of <a id="Sharma_et_al_2018_color_0" onclick="goToSource('D2000-2021','Sharma_et_al_2018', this.id)">Sharma et al., 2018</a>, with quotes from three of the paper's coauthors.`,
        title: `New light on the mysterious origin of Bornean elephants`,
    },
    {
        container: `<i>Proceedings of the National Academy of Sciences of the United States of America</i> (<i>Proc</i>. <i>Natl</i>. <i>Acad</i>. <i>Sci</i>. <i>U</i>.<i>S</i>.<i>A</i>., <i>PNAS</i>), digitally published academic journal`,
        contributors: `Eleftheria Palkopoulou (coauthor); Mark Lipson (coauthor); Swapan Mallick (coauthor); Svend Nielsen (coauthor); Nadin Rohland (coauthor); Sina Baleka (coauthor); Emil Karpinski (coauthor); Atma M. Ivancevic (coauthor); Thu-Hien To (coauthor); R. Daniel Kortschak (coauthor); Joy M. Raison (coauthor); Zhipeng Qu (coauthor); Tat-Jun Chin (coauthor); Kurt W. Alt (coauthor); Stefan Claesson (coauthor); Love Dalén (coauthor); Ross D.E. MacPhee (coauthor); Harald Meller (coauthor); Alfred L. Roca (coauthor); Oliver A. Ryder (coauthor); David Heiman (coauthor); Sarah Young (coauthor); Matthew Breen (coauthor); Christina Williams (coauthor); Bronwen L. Aken (coauthor); Magali Ruffier (coauthor); Elinor Karlsson (coauthor); Jeremy Johnson (coauthor); Federica Di Palma (coauthor); Jessica Alfoldi (coauthor);  David L. Adelson (coauthor); Thomas Mailund (coauthor); Kasper Munch (coauthor); Kerstin Lindblad-Toh (coauthor); Michael Hofreiter (coauthor); Hendrik Poinar (coauthor); David Reich (coauthor)`,
        date: `2018/02/26`,
        duration: `pp. E2566–E2574`,
        eyedee: `Palkopoulou_et_al_2018`,
        iteration: `Vol. 115, No. 11`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1073/pnas.1720554115" target="_blank">From publisher (DOI: 10.1073/pnas.1720554115)</a><li><a href="https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/2018_PNAS_ElephantGenome_3.pdf" target="_blank">From the David Reich Lab</a><li><a href="https://www.researchgate.net/publication/323409209_A_comprehensive_genomic_history_of_extinct_and_living_elephants" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `National Academy of Sciences (NAS)`,
        summary: `TBA.`,
        title: `A comprehensive genomic history of extinct and living elephants`,
    },
    {
        container: `<i>WCS Newsroom</i>, published website`,
        contributors: `Anonymous`,
        date: `2018/03/22`,
        duration: `<li>Article: 216 words<li>Video: 57 s`,
        languages: `English`,
        links: `<li><a href="https://newsroom.wcs.org/News-Releases/articleType/ArticleView/articleId/11161/VIDEO-Smoke-Breathing-Elephant-Stumps-Scientists.aspx" target="_blank">From publisher</a>`,
        location: `New York, United States of America`,
        medium: `Digitally published news article and video`,
        publisher: `Wildlife Conservation Society (WCS)`,
        summary: `TBA.`,
        title: `VIDEO: “Smoke-Breathing” Elephant Stumps Scientists`,
    },
    {
        container: `<i>Remote Sensing Applications: Society and Environment</i> (<i>Remote</i> <i>Sens</i>. <i>Appl</i>. <i>Soc</i>. <i>Environ</i>.), digitally published academic journal`,
        contributors: `Zorodzai Dzinotizei (coauthor); Amon Murwira (coauthor); Mhosisi Masocha (coauthor)`,
        date: `2018/10/26`,
        duration: `pp. 97-105`,
        eyedee: `Dzinotizei_et_al_2018`,
        iteration: `Vol. 13`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.rsase.2018.10.009" target="_blank">From publisher (DOI: 10.1016/j.rsase.2018.10.009)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `Elephant-induced landscape heterogeneity change around artificial waterholes in a protected savanna woodland ecosystem`,
    },
    {
        container: `<i>ArtStation</i>, published website`,
        contributors: `Tianhua Xu (illustrator); Xiaodi Jin (illustrator); Ravi Bansal (art director); Loic Zimmermann (art director)`,
        date: `2018/12/06`,
        duration: `9 illustrations`,
        languages: `English`,
        links: `<li><a href="https://www.artstation.com/artwork/Jl8orn" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published illustrations`,
        publisher: `ArtStation`,
        summary: `Concept art of Behemoth from <i>Godzilla: King of the Monsters</i> (2019), in which its final design can be seen alongside an earlier draft that more closely resembled a proboscidean.`,
        title: `Godzilla III`,
    },
    {
        container: `<i>Frontiers in Ecology and Evolution</i> (<i>Front</i>. <i>Ecol</i>. <i>Evol</i>.), digitally published academic journal`,
        contributors: `L. Jen Shaffer (coauthor); Kapil K. Khadka (coauthor); Jamon Van Den Hoek (coauthor); Kusum J. Naithani (coauthor)`,
        date: `2019/01/11`,
        duration: `12 pp.`,
        iteration: `Vol. 6, No. 235`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.3389/fevo.2018.00235" target="_blank">From publisher (DOI: 10.3389/fevo.2018.00235)</a><li><a href="https://www.semanticscholar.org/paper/Human-Elephant-Conflict%3A-A-Review-of-Current-and-Shaffer-Khadka/91eecebb9970521150e68757cb00fc5a4aa7ee8f" target="_blank">From Semantic Scholar</a><li><a href="https://www.researchgate.net/publication/330330444_Human-Elephant_Conflict_A_Review_of_Current_Management_Strategies_and_Future_Directions" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Frontiers`,
        summary: `TBA.`,
        title: `Human-Elephant Conflict: A Review of Current Management Strategies and Future Directions`,
    },
    {
        container: `<i>Behavioral Ecology</i> (<i>Behav</i>. <i>Ecol</i>.), digitally published academic journal`,
        contributors: `Michael A. Pardo (coauthor); Joyce H. Poole (coauthor); Angela S. Stoeger (coauthor); Peter H. Wrege (coauthor); Caitlin E. O'Connell-Rodwell (coauthor); Udaha Kapugedara Padmalal (coauthor); Shermin de Silva (coauthor)`,
        date: `2019/02/23`,
        duration: `pp. 809-820`,
        eyedee: `Pardo_et_al_2019`,
        iteration: `Vol. 30, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1093/beheco/arz018" target="_blank">From publisher (DOI: 10.1093/beheco/arz018)</a><li><a href="https://www.researchgate.net/publication/331875685_Differences_in_combinatorial_calls_among_the_3_elephant_species_cannot_be_explained_by_phylogeny" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Oxford Academic`,
        summary: `TBA.`,
        title: `Differences in combinatorial calls among the 3 elephant species cannot be explained by phylogeny`,
    },
    {
        container: `<i>Maximus</i>, published blog`,
        contributors: `Michael A. Pardo (author)`,
        date: `2019/05/01`,
        duration: `798 words`,
        languages: `N/A`,
        links: `<li><a href="https://maximus.trunksnleaves.org/2019/05/01/call-combinations-differ/" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Published blog post`,
        publisher: `Trunks & Leaves Inc.`,
        summary: `A layman-oriented summary of <a id="Pardo_et_al_2019_color_0" onclick="goToSource('D2000-2021','Pardo_et_al_2019', this.id)">Pardo et al., 2019</a> by one of the paper's coauthors.`,
        title: `Call Combinations Differ Among Living Elephants`,
    },
    {
        container: `<i>Polygon</i>, published website`,
        contributors: `Matt Patches (author)`,
        date: `2019/06/07`,
        duration: `1774 words`,
        languages: `English`,
        links: `<li><a href="https://www.polygon.com/2019/6/7/18648048/godzilla-king-of-monsters-post-credits-ending-kong-woolly-mammoth-interview" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `Vox Media`,
        summary: `<i>Godzilla: King of the Monsters</i> (2019) director Michael Dougherty reveals that Behemoth's creation and design were inspired by his fascination with woolly mammoths.`,
        title: `An incredibly spoilery conversation with Godzilla: King of Monsters director Mike Dougherty`,
    },
    {
        container: `<i>The IUCN Red List of Threatened Species</i>, published website`,
        contributors: `C. Williams (coauthor, assessor, reviewer, facilitator, compiler); S.K. Tiwari (coauthor, assessor, facilitator, compiler); V.R. Goswami (coauthor, assessor); Shermin de Silva (coauthor, assessor); A. Kumar (coauthor, assessor); N. Baskaran (coauthor, assessor); K. Yoganand (coauthor, assessor); V. Menon (coauthor, assessor); T.N.C. Vidya (reviewer); B. Goossens (reviewer)`,
        date: `2020`,
        duration: `29 pp.`,
        languages: `English`,
        links: `<li><a href="https://dx.doi.org/10.2305/IUCN.UK.2020-3.RLTS.T7140A45818198.en" target="_blank">From publisher (DOI: 10.2305/IUCN.UK.2020-3.RLTS.T7140A45818198.en)</a>`,
        location: `Gland, Switzerland`,
        medium: `Digitally published article`,
        publisher: `International Union for Conservation of Nature (IUCN)`,
        summary: `TBA.`,
        title: `<i>Elephas maximus</i>`,
    },
    {
        container: `<i>Primates</i>, digitally published academic journal`,
        contributors: `Shifra Z. Goldenberg (coauthor); George Wittemyer (coauthor)`,
        date: `2019/11/11`,
        duration: `pp. 119-128`,
        eyedee: `Goldenberg_Wittemyer_2019`,
        iteration: `Vol. 61`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1007/s10329-019-00766-5" target="_blank">From publisher (DOI: 10.1007/s10329-019-00766-5)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `SpringerLink`,
        summary: `TBA.`,
        title: `Elephant behavior toward the dead: A review and insights from field observations`,
    },
    {
        container: `<i>Journal of Paleontology</i> (<i>J</i>. <i>Paleontol</i>.), digitally published academic journal`,
        contributors: `Rodolphe Tabuce (coauthor); Raphaël Sarr (coauthor); Sylvain Adnet (coauthor); Renaud Lebrun (coauthor); Fabrice Lihoreau (coauthor); Jeremy E. Martin (coauthor); Bernard Sambou (coauthor); Mustapha Thiam (coauthor); Lionel Hautier (coauthor)`,
        date: `2019/11/29`,
        duration: `pp. 580-588`,
        iteration: `Vol. 94, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1017/jpa.2019.98" target="_blank">From publisher (DOI: 10.1017/jpa.2019.98)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Cambridge University Press`,
        summary: `TBA.`,
        title: `Filling a gap in the proboscidean fossil record: a new genus from the Lutetian of Senegal`,
    },
    {
        container: `<i>Animals</i> (<i>Anim</i>.), digitally published academic journal`,
        contributors: `Martin W. Seltmann (coauthor); Susanna Ukonaho (coauthor); Sophie Reichert (coauthor); Diogo Dos Santos (coauthor); U Kyaw Nyein (coauthor); Win Htut (coauthor); Virpi Lummaa (coauthor)`,
        date: `2020/01/06`,
        duration: `16 pp.`,
        iteration: `Vol. 10, No. 1 <i>Captive Elephant Welfare and Behaviour</i>`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.3390/ani10010094" target="_blank">From publisher (DOI: 10.3390/ani10010094)</a><li><a href="https://www.researchgate.net/publication/338416582_Faecal_Glucocorticoid_Metabolites_and_HL_Ratio_Are_Related_Markers_of_Stress_in_Semi-Captive_Asian_Timber_Elephants" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Molecular Diversity Preservation International (MDPI)`,
        summary: `TBA.`,
        title: `Faecal Glucocorticoid Metabolites and H/L Ratio Are Related Markers of Stress in Semi-Captive Asian Timber Elephants`,
    },
    {
        container: `<i>Science</i> (<i>Sci</i>.), digitally published academic journal`,
        contributors: `Zhihong Wang (coauthor); Zhengling Li (coauthor); Yongjing Tang (coauthor); Chongxue Yao (coauthor); Yu Liu (coauthor); Guilian Jiang (coauthor); Fang Wang (coauthor); Liang Liang (coauthor); Wenlan Zhao (coauthor); Gaofan Zhu (coauthor); Mingyong Chen (coauthor)`,
        date: `2020/01/24`,
        duration: `pp. 373-374`,
        iteration: `Vol. 367, Issue 6476`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1126/science.aba5991" target="_blank">From publisher (DOI: 10.1126/science.aba5991)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `American Association for the Advancement of Science (AAAS)`,
        summary: `TBA.`,
        title: `China's dams isolate Asian elephants`,
    },
    {
        container: `<i>Conservation Physiology</i> (<i>Conserv</i>. <i>Physiol</i>.), digitally published academic journal`,
        contributors: `Ruchun Tang (coauthor); Wenwen Li (coauthor); Di Zhu (coauthor); Xiaotong Shang (coauthor); Xianming Guo (coauthor); Li Zhang (coauthor)`,
        date: `2020/01/25`,
        duration: `14 pp.`,
        iteration: `Vol. 8, Issue 1`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1093/conphys/coz106" target="_blank">From publisher (DOI: 10.1093/conphys/coz106)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Oxford Academic`,
        summary: `TBA.`,
        title: `Raging elephants: effects of human disturbance on physiological stress and reproductive potential in wild Asian elephants`,
    },
    {
        container: `<i>Journal of Paleontology</i> (<i>J</i>. <i>Paleontol</i>.), digitally published academic journal`,
        contributors: `Ningthoujam Premjit Singh (coauthor); Advait M. Jukar (coauthor); Rajeev Patnaik (coauthor); K. Milankumar Sharma (coauthor); Nongmaithem Amardas Singh (coauthor); Yumlembam Priyananda Singh (coauthor)`,
        date: `2020/01/28`,
        duration: `pp. 788-795`,
        iteration: `Vol. 94, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1017/jpa.2020.3" target="_blank">From publisher (DOI: 10.1017/jpa.2020.3)</a><li><a href="https://pubs.geoscienceworld.org/jpaleontol/article-abstract/94/4/788/587660/The-first-specimen-of-Deinotherium-indicum?redirectedFrom=fulltext" target="_blank">From GeoScienceWorld</a><li><a href="https://www.researchgate.net/publication/338855668_The_first_specimen_of_Deinotherium_indicum_Mammalia_Proboscidea_Deinotheriidae_from_the_late_Miocene_of_Kutch_India" target="_blank">From ResearchGate</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Cambridge University Press`,
        summary: `TBA.`,
        title: `The first specimen of <i>Deinotherium indicum</i> (Mammalia, Proboscidea, Deinotheriidae) from the late Miocene of Kutch, India`,
    },
    {
        container: `<i>Genome Biology and Evolution</i> (<i>Genom</i>. <i>Biol</i>. <i>Evol</i>.), digitally published academic journal`,
        contributors: `Erin Fry (coauthor); Sun K. Kim (coauthor); Sravanthi Chigurapti (coauthor); Katelyn Mika (coauthor); Aakrosh Ratan (coauthor); Alexander Dammermann (coauthor); Brian J. Mitchell (coauthor); Webb Miller (coauthor); Vincent J. Lynch (coauthor)`,
        date: `2020/02/07`,
        duration: `pp. 48-58`,
        eyedee: `Fry_et_al_2020`,
        iteration: `Vol. 12, Issue 3`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1093/gbe/evz279" target="_blank">From publisher (DOI: 10.1093/gbe/evz279)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        notes: `<li><a href="https://doi.org/10.1101/137455" target="_blank">Preprint (DOI: 10.1101/137455)</a> on bioRxiv, digitally published on 2018/04/23`,
        publisher: `Oxford Academic`,
        summary: `TBA.`,
        title: `Functional Architecture of Deleterious Genetic Variants in the Genome of a Wrangel Island Mammoth`,
    },
    {
        container: `<i>Sci-News.com</i>, published website`,
        contributors: `Anonymous`,
        date: `2020/02/07`,
        duration: `488 words`,
        languages: `English`,
        links: `<li><a href="http://www.sci-news.com/paleontology/mutated-genes-wrangel-island-mammoths-08100.html" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `Sci-News.com`,
        summary: `A layman-oriented summary of <a id="Fry_et_al_2020_color_0" onclick="goToSource('D2000-2021','Fry_et_al_2020', this.id)">Fry et al., 2020</a>, with quotes from one of the paper's coauthors`,
        title: `Scientists ‘Resurrect’ Mutated Genes of Wrangel Island Mammoths`,
    },
    {
        container: `<i>Vertebrata PalAsiatica</i> (<i>Vertebr</i>. <i>PalAsiat</i>.), digitally published academic journal`,
        contributors: `Wang Shi-Qi (coauthor); Zhang Xiao-Xiao (coauthor); Li Chun-Xiao (coauthor)`,
        date: `2020/03/13`,
        duration: `pp. 373-374`,
        iteration: `Vol. 58, No. 2`,
        languages: `Chinese, English`,
        links: `<li><a href="http://www.ivpp.cas.cn/cbw/gjzdwxb/xbwzxz/202003/t20200313_5515086.html" target="_blank">From publisher (DOI: 10.19615/j.cnki.1000-3118.200310)</a>`,
        location: `Beijing, China`,
        medium: `Digitally published academic journal article`,
        publisher: `Institute of Vertebrate Paleontology and Paleoanthropology (IVPP)`,
        summary: `TBA.`,
        title: `戈壁锯齿象(<i>Serridentinus gobiensis</i> Osborn & Granger, 1932)和同心中新乳齿象(<i>Miomastodon tongxinensis</i> Chen, 1978)再研究：关于粗壮型轭齿象(<i>Zygolophodon</i>)的讨论`,
    },
    {
        container: `<i>PLoS ONE</i>, digitally published academic journal`,
        contributors: `Collin M. Brand (coauthor); Mireille B. Johnson (coauthor); Lillian D. Parker (coauthor); Jesús E. Maldonado (coauthor); Lisa Korte (coauthor); Hadrian Vanthomme (coauthor); Alfonso Alonso (coauthor); Maria Jose Ruiz-Lopez (coauthor); Caitlin Wells (coauthor); Nelson Ting (coauthor)`,
        date: `2020/04/29`,
        duration: `15 pp.`,
        iteration: `Vol. 15, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1371/journal.pone.0231832" target="_blank">From publisher (DOI: 10.1371/journal.pone.0231832)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        notes: `<li><a href="https://doi.org/10.1101/827188" target="_blank"> Preprint (DOI: 10.1101/827188)</a> on bioRxiv, digitally published on 2019/11/01`,
        publisher: `Public Library of Science (PLoS)`,
        summary: `TBA.`,
        title: `Abundance, density, and social structure of African forest elephants (<i>Loxodonta cyclotis</i>) in a human-modified landscape in southwestern Gabon`,
    },
    {
        container: `<i>Biology Letters</i> (<i>Biol</i>. <i>Lett</i>.), digitally published academic journal`,
        contributors: `Mareike C. Janiak (coauthor); Swellan L. Pinto (coauthor); Gwen Duytschaever (coauthor); Matthew A. Carrigan (coauthor); Amanda D. Melin (coauthor)`,
        date: `2020/04/29`,
        duration: `7 pp.`,
        eyedee: `Janiak_et_al_2020`,
        iteration: `Vol. 16, Issue 4`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1098/rsbl.2020.0070" target="_blank">From publisher (DOI: 10.1098/rsbl.2020.0070)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Royal Society`,
        summary: `TBA.`,
        title: `Genetic evidence of widespread variation in ethanol metabolism among mammals: revisiting the ‘myth' of natural intoxication`,
    },
    {
        container: `<i>The Conversation</i>, published website`,
        contributors: `Mareike C. Janiak (author)`,
        date: `2020/04/29`,
        duration: `774 words`,
        languages: `English`,
        links: `<li><a href="https://theconversation.com/elephants-get-drunk-because-they-cant-metabolize-alcohol-like-us-137475" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `The Conversation`,
        summary: `A layman-oriented summary of <a id="Janiak_et_al_2020_color_0" onclick="goToSource('D2000-2021','Janiak_et_al_2020', this.id)">Janiak et al., 2020</a> by one of the paper's coauthors.`,
        title: `Elephants get drunk because they can’t metabolize alcohol like us`,
    },
    {
        container: `<i>Science News</i>, digitally published magazine`,
        contributors: `Susan Milius (author)`,
        date: `2020/05/01`,
        duration: `673 words`,
        iteration: `Vol. 197, No. 10`,
        languages: `English`,
        links: `<li><a href="https://www.sciencenews.org/article/why-mammals-elephants-armadillos-might-get-drunk-easily" target="_blank">From publisher</a>`,
        location: `Washington, D.C., United States of America`,
        medium: `Digitally published magazine article`,
        publisher: ` Society for Science`,
        summary: `A layman-oriented summary of <a id="Janiak_et_al_2020_color_1" onclick="goToSource('D2000-2021','Janiak_et_al_2020', this.id)">Janiak et al., 2020</a>, with quotes from two of the paper's coauthors.`,
        title: `Why mammals like elephants and armadillos might get drunk easily`,
    },
    {
        container: `<i>Instagram</i>, published website`,
        contributors: `Michael Dougherty (author)`,
        date: `2020/05/01`,
        duration: `140 words`,
        languages: `English`,
        links: `<li><a href="https://www.instagram.com/p/B_qGtNlAZZf/?utm_source=ig_embed" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Published web page`,
        publisher: `Facebook, Inc.`,
        summary: `Director of <i>Godzilla: King of the Monsters</i> (2019) Michael Dougherty reveals woolly mammoth traits were incorporated into Behemoth's design and that, like mammoths, Behemoth is herbivorous and once lived in herds.`,
        title: `Titanus Behemoth`,
    },
    {
        container: `<i>Pokémon Trading Card Game (TCG): Sword and Shield — Darkness Ablaze</i>, physically published trading card game expansion`,
        contributors: `Kouki Saito (illustrator)`,
        date: `<li>Japanese copy: 2020/06/05 (ムゲンゾーン, 2020)<li>English copy: 2020/08/14 (Sword & Shield, 2020)`,
        duration: `6.3 x 8.8 cm (2.5 x 3.5 in)`,
        iteration: `<li>Japanese copy: No. 134/190<li>English copy: No. 132/189`,
        languages: `Japanese, English`,
        links: `<li><a href="https://www.pokemon-card.com/card-search/details.php/card/38779/regu/XY" target="_blank">Japanese copy from publisher</a><li><a href="https://bulbapedia.bulbagarden.net/wiki/File:CopperajahDarknessAblaze132.jpg" target="_blank">Japanese copy from Bulbapedia</a>, copy provided by Ruixiang95<li><a href="https://www.pokemon.com/us/pokemon-tcg/pokemon-cards/ss-series/swsh3/132/" target="_blank">English copy from publisher</a><li><a href="https://pkmncards.com/card/copperajah-darkness-ablaze-daa-132/" target="_blank">English copy from PkmnCards</a><li><a href="https://www.serebii.net/card/darknessablaze/132.shtml" target="_blank">English copy from Serebii.net</a>`,
        location: `N/A`,
        medium: `Physically published trading card, digitized`,
        publisher: `The Pokémon Company`,
        references: `<ul class="refs">ムゲンゾーン (2020). <i>ポケモンカードゲーム</i>. <a href="https://www.pokemon-card.com/ex/s3/" target="_blank">https://www.pokemon-card.com/ex/s3/</a></ul><br><ul class="refs">Sword & Shield—Darkness Ablaze (2020). <i>The Official Pokémon Website</i>. <a href="https://www.pokemon.com/us/pokemon-tcg/sword-shield-darkness-ablaze/explore-and-watch/" target="_blank">https://www.pokemon.com/us/pokemon-tcg/sword-shield-darkness-ablaze/explore-and-watch/</a></ul>`,
        summary: `TBA.`,
        title: `Copperajah`,
    },
    {
        container: `<i>Reuters</i>, published website`,
        contributors: `Brian Benza (author); Tim Cocks (editor); Giles Elgood (editor)`,
        date: `2020/06/15`,
        duration: `292 words`,
        languages: `English`,
        links: `<li><a href="https://www.reuters.com/article/us-botswana-wildlife/botswana-investigates-154-elephant-deaths-rules-out-poaching-idUSKBN23M1JH" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `Reuters News Agency`,
        summary: `TBA.`,
        title: `Botswana investigates 154 elephant deaths, rules out poaching`,
    },
    {
        container: `<i>Biological Conservation</i> (<i>Biol</i>. <i>Conserv</i>.), digitally published academic journal`,
        contributors: `Erin K. Buchholtz (coauthor); Amanda Stronza (coauthor); Anna Songhurst (coauthor); Graham McCulloch (coauthor); Lee A. Fitzgerald (coauthor)`,
        date: `2020/06/30`,
        duration: `9 pp.`,
        eyedee: `Buchholtz_et_al_2020`,
        iteration: `Vol. 248`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.biocon.2020.108677" target="_blank">From publisher (DOI: 10.1016/j.biocon.2020.108677)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `Using landscape connectivity to predict human-wildlife conflict`,
    },
    {
        container: `<i>The Conversation</i>, published website`,
        contributors: `Vicky Boult (author)`,
        date: `2020/07/03`,
        duration: `755 words`,
        languages: `English`,
        links: `<li><a href="https://theconversation.com/hundreds-of-elephants-are-mysteriously-dying-in-botswana-a-conservationist-explains-what-we-know-142004" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `The Conversation`,
        summary: `TBA.`,
        title: `Hundreds of elephants are mysteriously dying in Botswana – a conservationist explains what we know`,
    },
    {
        container: `<i>IUCN</i>, published website`,
        contributors: `IUCN SSC African Elephant Specialist Group (author)`,
        date: `2020/07/10`,
        duration: `1 p.`,
        languages: `English`,
        links: `<li><a href="https://www.iucn.org/news/species-survival-commission/202007/statement-iucn-ssc-african-elephant-specialist-group-elephant-deaths-botswana" target="_blank">From publisher</a>`,
        location: `Nairobi, Kenya`,
        medium: `Digitally published news article`,
        publisher: `International Union for Conservation of Nature (IUCN)`,
        summary: `TBA.`,
        title: `Statement of the IUCN SSC African Elephant Specialist Group on elephant deaths in Botswana`,
    },
    {
        container: `<i>Conservation Corridor</i>, published website`,
        contributors: `Erin K. Buchholtz (author)`,
        date: `2020/10/12`,
        duration: `353 words`,
        languages: `English`,
        links: `<li><a href="https://conservationcorridor.org/digests/2020/10/landscapeconnectivity/" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Conservation Corridor`,
        summary: `A layman-oriented summary of <a id="Buchholtz_et_al_2020_color_0" onclick="goToSource('D2000-2021','Buchholtz_et_al_2020', this.id)">Buchholtz et al., 2020</a> by one of the paper's coauthors.`,
        title: `Using landscape connectivity to predict human-wildlife conflict`,
    },
    {
        container: `<i>Remote Sensing Applications: Society and Environment</i> (<i>Remote</i> <i>Sens</i>. <i>Appl</i>. <i>Soc</i>. <i>Environ</i>.), digitally published academic journal`,
        contributors: `Anonymous`,
        date: `2020/10/29`,
        duration: `1 p.`,
        iteration: `Vol. 20`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.rsase.2020.100433" target="_blank">From publisher (DOI: 10.1016/j.rsase.2020.100433)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `Indicates that <a id="Dzinotizei_et_al_2018_color_0" onclick="goToSource('D2000-2021','Dzinotizei_et_al_2018', this.id)">Dzinotizei et al., 2018</a> was missing a declaration of Competing Interests statement.`,
        title: `Erratum regarding missing declaration of Competing Interest statements in previously published articles`,
    },
    {
        container: `<i>Quaternary International</i> (<i>Quat</i>. <i>Int</i>.), digitally published academic journal`,
        contributors: `Jiao Ma (coauthor); Yuan Wang (coauthor); Gennady Baryshnikov (coauthor); Dorothée Drucker (coauthor); Krista McGrath (coauthor); Hanwen Zhang (coauthor); Hervé Bocherens (coauthor); Yaowu Hu (coauthor)`,
        date: `2020/12/23`,
        duration: `43 pp.`,
        eyedee: `Ma_et_al_2020`,
        iteration: `In press`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1016/j.quaint.2020.12.024" target="_blank">From publisher (DOI: 10.1016/j.quaint.2020.12.024)</a>`,
        location: `N/A`,
        medium: `Digitally published academic journal article`,
        publisher: `Elsevier`,
        summary: `TBA.`,
        title: `The <i>Mammuthus</i>-<i>Coelodonta</i> Faunal Complex at its southeastern limit: A biogeochemical paleoecology investigation in Northeast Asia`,
    },
    {
        container: `<i>Institute of Vertebrate Paleontology and Paleoanthropology</i>, published website`,
        contributors: `Anonymous`,
        date: `2020/12/28`,
        duration: `734 words`,
        languages: `Chinese`,
        links: `<li><a href="http://www.ivpp.ac.cn/xwdt/ttyw/202012/t20201229_5847772.html" target="_blank">From publisher</a>`,
        location: `Beijing, China`,
        medium: `Digitally published news article`,
        publisher: `Institute of Vertebrate Paleontology and Paleoanthropology (IVPP)`,
        summary: `A layman-oriented summary of <a id="Ma_et_al_2020_color_0" onclick="goToSource('D2000-2021','Ma_et_al_2020', this.id)">Ma et al., 2020</a>.`,
        title: `东北亚地区更新世晚期猛犸象-披毛犀动物群的古生态研究新进展`,
    },
    {
        container: `<i>Wikipedia</i>, published website`,
        contributors: `Elephant940 (compiler)`,
        date: `Created 2020/12/29, last updated 2021/03/01`,
        duration: `389 Wikipedia articles`,
        languages: `English`,
        links: `<li><a href="https://en.wikipedia.org/wiki/User:Elephant940/Books/Elephants" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Published web page`,
        publisher: `Wikimedia Foundation`,
        summary: `A comprehensive list of English Wikipedia articles relating to probsocideans.`,
        title: `User:Elephant940/Books/Elephants`,
    },
    {
        container: `<i>A Moment of Science</i>, digitally published radio program`,
        contributors: `Paul Patton (author)`,
        date: `2021/02/08`,
        duration: `<li>Article: 261 words<li>Radio segment: 2 min`,
        eyedee: `Patton_2021`,
        languages: `English`,
        links: `<li><a href="https://indianapublicmedia.org/amomentofscience/do-elephants-grieve-their-dead.php" target="_blank">From publisher</a>`,
        location: `Bloomington, Indiana, United States of America`,
        medium: `Digitally published news article and radio segment`,
        publisher: `Indiana Public Media`,
        summary: `A layman-oriented summary of <a id="Goldenberg_Wittemyer_2019_color_0" onclick="goToSource('D2000-2021','Goldenberg_Wittemyer_2019', this.id)">Goldenberg and Wittemyer, 2019</a>.`,
        title: `Do Elephants Grieve Their Dead?`,
    },
    {
        container: `<i>Nature</i> (<i>Nat</i>.), digitally published academic journal`,
        contributors: `Ellen Callaway (author)`,
        date: `2021/02/17`,
        duration: `pp. 537-538`,
        iteration: `Vol. 590`,
        languages: `N/A`,
        links: `<li><a href="https://www.nature.com/articles/d41586-021-00436-x" target="_blank">From publisher</a>`,
        location: `London, England`,
        medium: `Digitally published news article`,
        publisher: `Nature Research`,
        summary: `A layman-oriented summary of <a id="van_der_Valk_et_al_2021_color_0" onclick="goToSource('D2000-2021','van_der_Valk_et_al_2021', this.id)">van der Valk et al., 2021</a>, with quotes from two of the paper's coauthors.`,
        title: `Million-year-old mammoth genomes shatter record for oldest ancient DNA`,
    },
    {
        container: `<i>Nature</i> (<i>Nat</i>.), digitally published academic journal`,
        contributors: `Tom van der Valk (coauthor); Patrícia Pečnerová (coauthor); David Díez-del-Molino (coauthor); Anders Bergström (coauthor); Jonas Oppenheimer (coauthor); Stefanie Hartmann (coauthor); Georgios Xenikoudakis (coauthor); Jessica A. Thomas (coauthor); Marianne Dehasque (coauthor); Ekin Sağlıcan (coauthor); Fatma Rabia Fidan (coauthor); Ian Barnes (coauthor); Shanlin Liu (coauthor); Mehmet Somel (coauthor); Peter D. Heintzman (coauthor); Pavel Nikolskiy (coauthor); Beth Shapiro (coauthor); Pontus Skoglund (coauthor); Michael Hofreiter (coauthor); Adrian M. Lister (coauthor); Anders Götherström (coauthor); Love Dalén (coauthor)`,
        date: `2021/02/17`,
        duration: `pp. 265-269`,
        eyedee: `van_der_Valk_et_al_2021`,
        iteration: `Vol. 591`,
        languages: `English`,
        links: `<li><a href="https://doi.org/10.1038/s41586-021-03224-9" target="_blank">From publisher (DOI: 10.1038/s41586-021-03224-9)</a><li><a href="https://europepmc.org/article/MED/33597750" target="_blank">From Europe PMC</a><li><a href="https://www.researchgate.net/publication/349393756_Million-year-old_DNA_sheds_light_on_the_genomic_history_of_mammoths" target="_blank">From ResearchGate</a><li><a href="https://www.gwern.net/docs/genetics/selection/2021-vandervalk.pdf" target="_blank">From Gwern Branwen</a>`,
        location: `London, England`,
        medium: `Digitally published academic journal article`,
        publisher: `Nature Research`,
        summary: `TBA.`,
        title: `Million-year-old DNA sheds light on the genomic history of mammoths`,
    },
    {
        container: `<i>The Conversation</i>, published website`,
        contributors: `David Díez-del-Molino (coauthor); Love Dalén (coauthor)`,
        date: `2021/02/17`,
        duration: `874 words`,
        languages: `English`,
        links: `<li><a href="https://theconversation.com/we-sequenced-the-oldest-ever-dna-from-million-year-old-mammoths-155485" target="_blank">From publisher</a>`,
        location: `N/A`,
        medium: `Digitally published news article`,
        publisher: `The Conversation`,
        summary: `A layman-oriented summary of <a id="van_der_Valk_et_al_2021_color_1" onclick="goToSource('D2000-2021','van_der_Valk_et_al_2021', this.id)">van der Valk et al., 2021</a> by two of the paper's coauthors.`,
        title: `We sequenced the oldest ever DNA, from million-year-old mammoths`,
    },
    {
        container: `<i>The IUCN Red List of Threatened Species</i>, published website`,
        contributors: `K.S. Gobush (coauthor, assessor); C.T. Edwards (coauthor, assessor); D. Balfour (coauthor, assessor); George Wittemyer (coauthor, assessor); Fiona Maisels (coauthor, assessor); R.D. Taylor (coauthor, assessor); J. Selier (reviewer); N. Sabanda (reviewer); J. Blanc (contributor); J.P. Ross (facilitator, compiler)`,
        date: `2021/03/25`,
        duration: `N/A`,
        languages: `English`,
        links: `<li><a href="https://www.iucnredlist.org/species/181008073/181022663" target="_blank">From publisher</a>`,
        location: `Gland, Switzerland`,
        medium: `Digitally published article`,
        publisher: `International Union for Conservation of Nature (IUCN)`,
        summary: `TBA.`,
        title: `<i>Loxodonta africana</i>`,
    },
    {
        container: `<i>The IUCN Red List of Threatened Species</i>, published website`,
        contributors: `K.S. Gobush (coauthor, assessor); C.T. Edwards (coauthor, assessor); Fiona Maisels (coauthor, assessor); George Wittemyer (coauthor, assessor); D. Balfour (coauthor, assessor); R.D. Taylor (coauthor, assessor); J. Selier (reviewer); N. Sabanda (reviewer); J. Blanc (contributor); J.P. Ross (facilitator, compiler)`,
        date: `2021/03/25`,
        duration: `N/A`,
        languages: `English`,
        links: `<li><a href="https://www.iucnredlist.org/species/181007989/181019888" target="_blank">From publisher</a>`,
        location: `Gland, Switzerland`,
        medium: `Digitally published article`,
        publisher: `International Union for Conservation of Nature (IUCN)`,
        summary: `TBA.`,
        title: `<i>Loxodonta cyclotis</i>`,
    },
]