module.exports = [
    [
        {
            contributors: `Carolus Linnaeus (coauthor); Johann Fridrich Gmelin (coauthor); William Turton (Latin-to-English translator)`,
            date: `1802`,
            duration: `943 pp.`,
            iteration: `1st ed. Vol. 1`,
            languages: `English`,
            links: `<li><a href="https://archive.org/stream/generalsystemofn01linn#page/35/mode/2up" target="_blank">From Internet Archive</a>, copy provided by NCSU Libraries`,
            location: `London, England`,
            medium: `Physically published book, digitized`,
            publisher: `Printed for Lackington, Allen, and Co.`,
            summary: `An English translation of <a id="Linnaeus_Gmelin_1788_color" onclick="goToSource('1700-1799','Linnaeus_Gmelin_1788', this.id)">Linnaeus and Gmelin, 1788</a>. The elephant section is on page 35.`,
            title: `A General System of Nature: Through the Three Grand Kingdoms of Animals, Vegetables, and Minerals; Systematically Divided Into Their Several Classes, Orders, Genera, Species, and Varieties With Their Habitations, Manners, Economy, Structure, and Peculiarities.`,
        },
        {
            contributors: `Pierre Camper (author); A.G. Camper (address author)`,
            date: `1802/>08/>18`,
            duration: `107 pp.`,
            iteration: `1st ed.`,
            languages: `French`,
            links: `<li><a href="https://archive.org/stream/Descriptionanat00Camp#page/iii/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Harvard University Ernst Mayr Library of the Museum of Comparative Zoology`,
            location: `Paris, France`,
            medium: `Physically published book, digitized`,
            publisher: `H.J. Jansen`,
            summary: `TBA.`,
            title: `Description Anatomique d'un Éléphant Mâle`,
        },
    ],
    [
        {
            contributors: `Carolus D. Illiger (author)`,
            date: `1811/>04`,
            duration: `301 pp.`,
            iteration: `1st ed.`,
            languages: `Latin, German`,
            links: `<li><a href="https://www.google.com/books/edition/Caroli_Illigeri_Prodromus_systematis_mam/I9sTAAAAQAAJ?hl=en&gbpv=1&pg=PA96" target="_blank">From Google Books</a>, copy provided by University of Lausanne (<a href="https://web.archive.org/web/20210207194027/https://books.googleusercontent.com/books/content?req=AKW5QafwELHoIks7C7v9mhRGi72Z-wnh8YtKwbaxS_o9fMZE1s6oYqv9IfcH_toSZgboSp5N8klmAU8CccxPf6aynZghdE1E-1uYF-tqwl1lssWLExJk5brRnT5vsBnalC4BLMmGEMwfPgrbT-0qWeGb6IKrCHmAeosA1irCmqsP6OHBmsRLEuz532tVe5cf0V2UEGNmdWtF4_w_rcQjIQFrX9yaVq8-pFl8ZR63z7VMfp765frU-H2X0tSEYs6hWUMbIE6oX_pW8GkLWcweonsMPhcdRnLObTUc16yXTHRnsQ1eGQJQkDs" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://web.archive.org/web/20210207194345/https://books.googleusercontent.com/books/content?req=AKW5QaeD7j4eCMVHstHMO9iiZQBU1oMcKNfmTmcvXSUDxBQmdNK0_NJrlkNWUt8bE7fn24u5SOo43X8O0lItrdxyhb2nugAYkYfazYuk_xtrn5aBAP5eHvaYMw9zJX9xDW0PtO9sHw_Xmncp34Ft0i-qnDuW8K4BWyLsI0OOcgBDQqdK5qIKAV6gsGhpVB4v-Y8RWgXYektYFd2bBNLFgzMVb9aPqaTznucpecOilbVxdLddNPrfZoaBAtwidCK8xldzYIk9Gji7497Mv5lce91lE-k8puJ49g" target="_blank">From Google Books</a>, copy provided by University of Turin (<a href="https://web.archive.org/web/20210207194345/https://books.googleusercontent.com/books/content?req=AKW5QaeD7j4eCMVHstHMO9iiZQBU1oMcKNfmTmcvXSUDxBQmdNK0_NJrlkNWUt8bE7fn24u5SOo43X8O0lItrdxyhb2nugAYkYfazYuk_xtrn5aBAP5eHvaYMw9zJX9xDW0PtO9sHw_Xmncp34Ft0i-qnDuW8K4BWyLsI0OOcgBDQqdK5qIKAV6gsGhpVB4v-Y8RWgXYektYFd2bBNLFgzMVb9aPqaTznucpecOilbVxdLddNPrfZoaBAtwidCK8xldzYIk9Gji7497Mv5lce91lE-k8puJ49g" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://archive.org/stream/b21304397#page/96/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the King's College London Foyle Special Collections Library <li><a href="https://archive.org/stream/caroliilligerida00illi#page/96/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
            location: `Berlin, Germany`,
            medium: `Physically published book, digitized`,
            publisher: `C. Salfeld`,
            summary: `Illiger employs <a id="Cuvier_1798_color" onclick="goToSource('1700-1799','Cuvier_1798', this.id)">Cuvier's</a> <i>Elephas indicus</i> for the Asian elephant and <a id="Blumenbach_1797_color" onclick="goToSource('1700-1799','Blumenbach_1797', this.id)">Blumenbach's</a> <i>E</i>. <i>africanus</i> for the African elephant, and on page 96 proposes the name Proboscidea for the family encompassing both.`,
            title: `Prodromus Systematis Mammalium et Avium Additis Terminis Zoographicis Utriusque Classis, Eorumque Versione Germanica.`,
            
        },
        {
            container: `<i>Histoire Naturelle des Mammifères Avec des Figures Originales, Coloriées, Dessinées d'Après des Animaux Vivans</i>, physically published book`,
            contributors: `Frédéric Cuvier (author)`,
            date: `1825/09`,
            duration: `10 pp.`,
            iteration: `1st ed., Tome 6`,
            languages: `French`,
            links: `<li><a href="https://archive.org/stream/histoirenaturel6geof#page/n122/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
            location: `Paris, France`,
            medium: `Physically published book chapter, digitized`,
            publisher: `A. Belin`,
            summary: `TBA.`,
            title: `Éléphant d'Asie.`,
        },
    ],
    [
        {
            container: `<i>Histoire Naturelle des Mammifères Avec des Figures Originales, Coloriées, Dessinées d'Après des Animaux Vivans</i>, physically published book`,
            contributors: `Frédéric Cuvier (author)`,
            date: `1825/11`,
            duration: `2 pp.`,
            eyedee: `Cuvier_1825b`,
            iteration: `1st ed., Tome 6`,
            languages: `French`,
            links: `<li><a href="https://archive.org/stream/histoirenaturel6geof#page/n116/mode/2up/" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
            location: `Paris, France`,
            medium: `Physically published book chapter, digitized`,
            publisher: `A. Belin`,
            summary: `Cuvier argues that African elephants are anatomically distinct enough from Asian elephants to warrant placement in a separate genus, which he names <i>Loxodonte</i>.`,
            title: `Éléphant d'Afrique.`,
        },
        {
            container: `<i>The Zoological Journal</i> (Zool. J.), physically published academic journal`,
            contributors: `Anonymous`,
            date: `1827/01`,
            duration: `pp. 140-143`,
            iteration: `Vol. 3, No. 9`,
            languages: `English`,
            links: `<li><a href="https://archive.org/stream/zoologicaljourna03lond#page/140/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London<li><a href="https://archive.org/stream/zoologicaljourna318271828sowe#page/140/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
            location: `London, England`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `W. Phillips`,
            summary: `The anonymous author Latinizes <a id="Cuvier_1825b_color" onclick="goToSource('1800-1899','Cuvier_1825b', this.id)">Cuvier's</a> <i>Loxodonte</i> to <i>Loxodonta</i>.`,
            title: `<i>Histoire Naturelle des Mammifères Avec des Figures Originales, Coloriees, Dessinées d'Après des Animaux Vivans; &c.</i> <i>Par</i> MM. Geoffroy Saint-Hillaire, <i>et</i> F. Cuvier. Livraisons 52<sup>de</sup> <i>et</i> 53<sup>eme</sup>`,
        },
    ],
    [
        {
            container: `<i>A Prodromus of a Synopsis Animalium, Comprising A Catalogue Raisonné, of the Zootomical Collection Of Joshua Brookes, Esq. F.R.S. Etc.</i>, physically published catalogue`,
            contributors: `Joshua Brookes (author)`,
            date: `1828/<07/<28`,
            duration: `76 pp.`,
            iteration: `Part 1`,
            languages: `English`,
            links: `<li><a href="https://www.google.com/books/edition/_/4DwAAAAAQAAJ?hl=en&gbpv=1&pg=PA73" target="_blank">From Google Books</a>, copy provided by Oxford University (<a href="https://web.archive.org/web/20210214192925/https://books.googleusercontent.com/books/content?req=AKW5QadwVSVwUZftumH5axJcOdEm56MH-pPNzuN3WEUeWrIl2STrnlws_LwE2-pZ_brdV-uWMBcmRpgXM2LKJwVLWU-D3VT81_OnaML49OzE4tqAVjgk_DqwrVCyJAlm1WKnfLd2aYSWUyvz3kOkioTlN_gZ9fLJKfPGkUFDqPV4NtlBxLZlLOnxDubZctc_ZsV2rFXhLeYVaNzNyv3yCbm8rH-tDpG5ApLWrq8JqD6UkgoH0Qyp8qL_vB2YU3wnHADvmEQbq0_2" target="_blank">archived in the Wayback Machine</a>)<li><a href="https://archive.org/stream/brookesianmuseu00broogoog#page/n99/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Oxford University`,
            location: `London, England`,
            medium: `Physically published catalogue, digitized`,
            publisher: `Printed by Richard Taylor`,
            summary: `The section on elephants, "Fam. 1. Elephantidae. Proboscidea", is on pages 73-74.  Details TBA.`,
            title: `A Catalogue of the Anatomical & Zoological Museum of Joshua Brookes, Esq. F.R.S. Etc.`,
        },
        {
            container: `<i>Transactions of the American Philosophical Society</i> (Trans. Am. Philos. Soc.), physically published academic journal`,
            contributors: `John Davidson Godman (author)`,
            date: `1830/>01/>01`,
            duration: `pp. 478-485`,
            iteration: `New Ser., Vol. 3`,
            languages: `English`,
            links: `<li><a href="https://archive.org/stream/transactionsofam03amer#page/478/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the New York Botanical Garden LuEsther T. Mertz Library<li><a href="https://archive.org/stream/transactionsofam03inamer#page/478/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the University of Pittsburgh Library System<li><a href="https://doi.org/10.2307/1005152" target="_blank">From JSTOR (DOI: 10.2307/1005152)</a>`,
            location: `Philadelphia, Pennsylvania, United States of America`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `American Philosophical Society (APS)`,
            summary: `TBA.`,
            title: `No. XIX. Description of a New Genus and New Species of Extinct Mammiferous Quadruped.`,
        }
    ],
    [
        {
            container: `<i>Proceedings of the Royal Irish Academy</i> (Proc. R. Ir. Acad.), physically published academic journal`,
            contributors: `Robert Harrison (author)`,
            date: `1847/>03/>31`,
            duration: `pp. 385-398`,
            iteration: `Vol. 3`,
            languages: `English`,
            links: `<li><a href="https://archive.org/stream/proceedingsofroy03dubl#page/385/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London`,
            location: `Dublin, Ireland`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Printed by M. H. Gill for the Royal Irish Academy`,
            summary: `TBA.`,
            title: `On the Anatomy of the Elephant.`,
        },
        {
            contributors: `Coenraad Jacob Temminck (author)`,
            date: `1847/>05`,
            duration: `470 pp.`,
            eyedee: `Temminck_1847`,
            iteration: `1st ed., Tome 2`,
            languages: `French`,
            links: `<li><a href="https://www.google.com/books/edition/Coup_d_oeil_general_sur_les_possessions/2pU6AAAAcAAJ?hl=en&authuser=0&gbpv=1&pg=PA91" target="_blank">From Google Books</a>, copy provided by Bayerische Staatsbibliothek(<a href="https://web.archive.org/web/20210207194817/https://books.googleusercontent.com/books/content?req=AKW5QactSJpZ0V7Tum4sUxdtzTm0PRVs6Fh5WGfDUlhGbF7b-ma3BnyA78n0IJAr7HnSHs8_vey7w04pJeIgoYdWbX6c_fH1cvO-XbeSs76-6K-ozJb_gCtURFHjv4kbY5pErqueK3YSTltp117SxxemO3RPfbhY7UkHtO0XFP1RuhBX6_yr6-OEr8oZf4ZlSDqjoQvgvjfVr92DQU0d_maMChaXKhsX4bMhghNZJELy8-5flTXq3I7glNiSXrsDEzsg6BQkTY6e5l8AMKdSgwFhuyR_JUzRJLBLto7kdN28iAK1UbeToK4" target="_blank">archived in the Wayback Machine</a>)<li><a href="https://www.google.com/books/edition/_/hhkPAAAAQAAJ?hl=en&authuser=0&gbpv=1&pg=PA91" target="_blank">From Google Books</a>, copy provided by Ghent University (<a href="https://web.archive.org/web/20210207195038/https://books.googleusercontent.com/books/content?req=AKW5QadUpSJur5HYW6deSBmosTatgpCXB4oZIF19F1ib52UQZePhSTULThRWbWLM5fL_xY4aqsQvYo3zVtDb-RAYZzpjRj4-Yb4W4Z1I5NvYEEEE_qnUI58PG8fzn0THhv0ZjfoLviCBE5E6eSubo92zzzTGDfyX_R99dTS7czdN50_nA0_5TJv6xCuxLBUGbSWw6w_HQ1V-Yp8dMciAHHQbafG1CYD_e7lnwXnlSh7YfiJA03FnFkvEHfunS6fVuBYDS71jMTzMkkQfBB9ti7his70wDdxYZf4O7L25sM6xtqI1yaalIIw" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://www.google.com/books/edition/Coup_d_oeil_g%C3%A9n%C3%A9ral_sur_les_possession/15kBAAAAQAAJ?hl=en&gbpv=1&pg=PA91" target="_blank">From Google Books</a>, copy provided by Oxford University (<a href="https://web.archive.org/web/20210214204620/https://books.googleusercontent.com/books/content?req=AKW5Qaew798VW_baDeugJKp9pAomJlj8POy20G6bl29HeEOHlbpidcMwmP_PUVwSORTB_Nbv5V6q8uKF4WN7O-ZT_ScSuiMctPBg7M6t6dXVAEcYgaZP9DnnUDhs-8lyPvx5V_dLQqRH08QX8XZZDnQCIaJ4qEzreQsljVlaGz3mOkg0knqr5BwUv2uZe5gndiVpD0jGK7W4aePX2vkeEBTwwJ_3xsaXRFvKRohuD6Y4HW3H9U0Ujj4YIfB-kdwBj20-ROChMdQVmLq8HlhxEAB8-9IuTnlViDokQodRcjzePr1ggeYwVFc" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://www.google.com/books/edition/_/0556zAVURRwC?hl=en&authuser=0&gbpv=1&pg=PA91" target="_blank">From Google Books</a>, copy provided by the New York Public Library (<a href="https://web.archive.org/web/20210207195200/https://books.googleusercontent.com/books/content?req=AKW5QafbOH2P2eJoO794E-98xw5xgT41yHTxHsXU9Q5zsXVAOoFfndou4NmdGMxMsybR3jemyCIa6JmephcAUfLB5C8DGadjJqM2ePq0YBAt0Ji66eTdFNcWDLTMnQd5gMkgI98wsMcQzksERtg-TGP7FQOYSApDj1A-Nh100UkCr4UBqaeihKzWAvI-TiGzBR3oIexXRsC3O6YLrqMTTxIyRJjGlFuviPtLTEvcab8VX8rlrgXLH5_Eiu-i_V5_7SJupKiEs4TsD5DMNWBt7EpQNtfpawpOklODKnkJ_K_cMw8sBjj8o7U" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://www.google.com/books/edition/Coup_d_oeil_g%C3%A9n%C3%A9ral_sur_les_possession/sBMt6rQpK_8C?hl=en&gbpv=1&pg=PA91" target="_blank">From Google Books</a>, copy provided by the University of Michigan (<a href="https://web.archive.org/web/20210207195340/https://books.googleusercontent.com/books/content?req=AKW5QacmIk4y2aMAkuSbgYQM3Q4PYbC-NTZtXKuSvG2kUD1spqtwtpzqi2E6JLq62aAeJOYKKzb7RfbCA7rjpthlTsRvpwjBOAYBFJh2JiqirAtQqIoDuF-ntPWRo2Q8LKI-P4FYv-v7yYTmj7KaYxmtxJN75QTPyFLchEEIqoafYBeFT5q_DjgyhGzbfG0STJZnI3Lyo3v6GNzGpjWus4YZKVbWHnJVrxna0ijI92Ftd5eUHh6NSvBPkw7Soy4rsW4dOUh73wlPO_u7JCsHvA71mJwbyeNnFa25s1lOywusU-xipLfqZ2w" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://archive.org/stream/coupdoeilgnrals04temmgoog#page/n105/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Oxford University <li><a href="https://archive.org/stream/coupdoeilgnrals03temmgoog#page/n104/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the University of Michigan <li><a href="https://reader.digitale-sammlungen.de/de/fs1/object/display/bsb10276433_00103.html" target="_blank">From Bayerische Staatsbibliothek</a> (<a href="https://web.archive.org/web/20210214203429/https://download.digitale-sammlungen.de/pdf/16133347498888bsb10276433.pdf" target="_blank">archived in the Wayback Machine</a>)`,
            location: `Leiden, Netherlands`,
            medium: `Physically published book, digitized`,
            publisher: `A. Arnz & Comp.`,
            summary: `Temminck proposes on pages 91-92 that the elephants found on the island of Sumatra are a distinct species from those found elsewhere in Asia based on skeletal differences. He dubs these elephants <i>Elephas sumatranus</i>.`,
            title: `Coup-d'Oeil Général sur les Possessions Néerlandaises dans l'Inde Archipélagique.`,
        },
    ],
    [
        {
            container: `<i>The Quarterly Journal of the Geological Society of London</i> (Q. J. Geol. Soc. Lond.), physically published academic journal`,
            contributors: `Hugh Falconer (author)`,
            date: `1857/>06/>30`,
            duration: `pp. 307-360`,
            iteration: `Vol. 8, Part 1`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1144/GSL.JGS.1857.013.01-02.43" target="_blank">From publisher (DOI: 10.1144/GSL.JGS.1857.013.01-02.43 )</a><li><a href="https://archive.org/stream/quarterlyjourna131857geol#page/307/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
            location: `London, England`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Longman, Brown, Green, Longmans, and Roberts.`,
            summary: `TBA.`,
            title: `On the Species of Mastodon and Elephant occuring in the fossil state in Great Britain. Part I. Mastodon.`,
        },
        {
            container: `<i>Harper's Weekly. A Journal of Civilization.</i>, physically published newspaper`,
            contributors: `Thomas Nast (illustrator)`,
            date: `1874/11/07`,
            duration: `p. 912, 26.67 x 40.005 cm (10.5 x 15.75 in)`,
            iteration: `Vol. 18, No. 932`,
            languages: `English`,
            links: `<li><a href="http://mutex.gmu.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=h9m&AN=67549865&site=ehost-live" target="_blank">From George Mason University</a> <li><a href="https://www.loc.gov/resource/ppmsca.15785/" target="_blank">From the Library of Congress</a> <li><a href="https://americanhistory.si.edu/collections/search/object/nmah_528979" target="_blank">From the Smithsonian National Museum of American History</a> <li><a href="https://www.harpweek.com/09Cartoon/BrowseByDateCartoon.asp?Year=2003&Month=November&Date=7" target="_blank">From HarpWeek</a>`,
            location: `New York, United States of America`,
            medium: `Physically published engraving, digitized`,
            publisher: `Harper & Brothers`,
            summary: `The earliest use of the elephant to represent the Republican Party.`,
            title: `The Third Term Panic.`,
        },
    ],
    [
        {
            container: `<i>Studies in Comparative Anatomy</i>, physically published book series`,
            contributors: `L.C. Miall (coauthor); F. Greenwood (coauthor)`,
            date: `1878`,
            duration: `84 pp.`,
            iteration: `No. 2`,
            languages: `English`,
            links: `<li><a href="https://archive.org/stream/anatomyofindiane00mial#page/n6/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Harvard University Ernst Mayr Library of the Museum of Comparative Zoology`,
            location: `London, England`,
            medium: `Physically published book, digitized`,
            publisher: `Macmillan and Co.`,
            summary: `TBA.`,
            title: `Anatomy of the Indian Elephant`,
        },
        {      
            contributors: `Matthew Scott (author)`,
            date: `1885/01/14~1885/09/15`,
            duration: `96 pp.`,
            iteration: `1st ed.`,
            languages: `English`,
            links: `<li><a href="https://archive.org/stream/autobiographyofm00scot#page/n8/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Boston Public Library <li><a href="https://www.fadedpage.com/showbook.php?pid=20150417" target="_blank">Digital copy from Faded Page</a>`,
            location: `Bridgeport, Connecticut, United States of America`,
            medium: `Physically published book, digitized`,
            notes: `<li>Published in 1885 sometime after January 14th. Since Jumbo was killed on September 15th, 1885 but was alive at the time of writing, it must have been published between January 14th and September 15th.`,
            publisher: `Trow's Printing and Bookbinding Co.`,
            summary: `TBA.`,
            title: `Autobiography of Matthew Scott, Jumbo's Keeper Formerly of the Zoölogical Society's Gardens, London, and Receiver of Sir Edwin Landseer Medal in 1866 Also Jumbo's Biography by the Same Author.`,
        },
    ],
    [    
        {   
            contributors: `William Henry Flower (coauthor); Richard Lydekker (coauthor)`,
            date: `1891/>03`,
            duration: `763 pp.`,
            iteration: `1st ed.`,
            languages: `English`,
            links: `<li><a href="https://www.google.com/books/edition/An_Introduction_to_the_Study_of_Mammals/YclRAAAAMAAJ?hl=en&gbpv=1&pg=PA418" target="_blank">From Google Books</a>, copy provided by the University of Wisconsin-Madison (<a href="https://web.archive.org/web/20210219031828/https://books.googleusercontent.com/books/content?req=AKW5QadLnZED9Lk4AHo1IdsRzR-c_YLYBCxcaZamoylOunbqvPfda-KuOvWV4LL78l1SGe2NRJdZmrR9UtcBaIFFWM9_IB60_yc2acZW2EjRG_CO6ZeyXuT-DzvQ83k8kNqw_3HHHibfY0Yd_KAa6JoOA2Dtr-rIVdnvH8FC0bcw7FlN5qA4j-AlwBSb5gNrgm5w3VbyjzSPWqlYwlVJM5aA_9zbuqDCPPIZrdLgRRY93nq40PFDANu5fB486dfMKbwyHhpAfuq_q4WCJW8HQELv7SOmxBYv7w" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://archive.org/stream/cu31924001022684#page/n437/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Cornell University Library <li><a href="https://archive.org/stream/introductiontost00flow#page/418/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Marine Biological Laboratory and Woods Hole Oceanographic Institution (MBLWHOI) Library <li><a href="https://archive.org/stream/b2191610x#page/418/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Royal College of Physicians in Edinburgh <li><a href="https://archive.org/stream/anintroductiont00lydegoog#page/n440/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the University of Wisconsin-Madison`,
            location: `London, England`,
            medium: `Physically published book, digitized`,
            publisher: `Adam and Charles Black`,
            summary: `The section on elephants, "Suborder Proboscidea", is on pages 418-436. Details TBA.`,
            title: `An Introduction to the Study of Mammals Living and Extinct`,
        },    
        {
            contributors: `Anonymous`,
            date: `1899`,
            duration: `106 x 72 cm (41.7 x 28 in)`,
            languages: `English`,
            links: `<li><a href="https://www.loc.gov/resource/ppmsca.55077/" target="_blank">From the Library of Congress</a>`,
            location: `Buffalo, New York, United States of America`,
            medium: `Physically published chromolithograph poster, digitized`,
            notes: `<li><a href="https://www.loc.gov/resource/cph.3b52708/" target="_blank">Color film copy transparency from the Library of Congress.</a>`,
            publisher: `Courier Litho. Co.`,
            summary: `TBA.`,
            title: `Ringling Bros. World's Greatest Shows: Nothing Like Them Ever Seen Before. The Funny, Wonderful Elephant Brass Band.`,
        },
    ]
]