module.exports = [
        [{
            container: `<i>Philosophical Transactions, Giving Some Account of the Present Undertaking Studies, and Labours of the Ingenious, in Many Considerable Parts of the World.</i> (Phil. Trans.), physically published academic journal`,
            contributors: `Anthony van Leeuwenhoek (author)`,
            date: `1712/>12`,
            duration: `pp. 518-522`,
            iteration: `Vol. 27, No. 336`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1098/rstl.1710.0062" target="_blank">From publisher (DOI: 10.1098/rstl.1710.0062)</a> <li><a href="https://archive.org/stream/philosophicaltra2717roya#page/518/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London <li><a href="https://www.jstor.org/stable/103162" target="_blank">From JSTOR</a>`,
            location: `London, England`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Printed for H. Clemens, William Innys, and D. Brown`,
            summary: `TBA.`,
            title: `I. Some Remarks upon the Disposition of the Parts, and Microscopical Observations upon the Contexture of the Skin of Elephants.`,
        }],
        [{
            container: `<i>Philosophical Transactions, Giving Some Account of the Present Undertaking Studies, and Labours of the Ingenious, in Many Considerable Parts of the World.</i> (Phil. Trans.), physically published academic journal`,
            contributors: `Hans Sloane (author)`,
            date: `1728/>09`,
            duration: `pp. 457-471`,
            iteration: `Vol. 35, No. 403`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1098/rstl.1727.0042" target="_blank">From publisher (DOI: 10.1098/rstl.1727.0042)</a> <li><a href="https://archive.org/stream/philosophicaltra3517roya#page/457/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London <li><a href="https://www.jstor.org/stable/103702" target="_blank">From JSTOR</a>`,
            location: `London, England`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Printed by William Innys for the Royal Society`,
            summary: `TBA.`,
            title: `I. An Account of Elephants Teeth and Bones found under Ground.`,
            
        }],
        [{
            container: `<i>Philosophical Transactions, Giving Some Account of the Present Undertaking Studies, and Labours of the Ingenious, in Many Considerable Parts of the World.</i> (Phil. Trans.), physically published academic journal`,
            contributors: `John Philip Breyne (author)`,
            date: `1739`,
            duration: `pp. 124-125`,
            iteration: `Vol. 40, No. 446`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1098/rstl.1737.0026" target="_blank">From publisher (DOI: 10.1098/rstl.1737.0026)</a> <li><a href="https://archive.org/stream/philosophicaltra4017roya#page/124/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London <li><a href="https://www.jstor.org/stable/103902" target="_blank">From JSTOR</a>`,
            location: `London, England`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Printed by T. Woodward and C. Davis for the Royal Society`,
            summary: `TBA.`,
            title: `VIII. A Letter From John Phil. Breyne, M. D. F. R. S. To Sir Hans Sloane, Bart. Pres. R. S. With Observations, and a Description of Some Mammoth's Bones Dug Up in Siberia.`,   
        }],
        [{
            contributors: `Carolus Linnaeus (author)`,
            date: `1758`,
            duration: `823 pp.`,
            eyedee: `Linnaeus_1758`,
            iteration: `10th ed., Tome 1`,
            languages: `Latin`,
            links: `<li><a href="https://archive.org/stream/mobot31753000798865#page/33/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Missouri Botanical Garden <li><a href="https://reader.digitale-sammlungen.de/de/fs1/object/display/bsb10076014_00041.html" target="_blank">From Bayerische Staatsbibliothek</a> (<a href="https://web.archive.org/web/20210207005415/https://download.digitale-sammlungen.de/pdf/16126589828888bsb10076014.pdf" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://gdz.sub.uni-goettingen.de/id/PPN362053006?tify={%22pages%22:[37],%22view%22:%22info%22}" target="_blank">From Göt­tinger Digi­tali­sierungs­zentrum (GDZ)</a>`,
            location: `Stockholm, Sweden`,
            medium: `Physically published book, digitized`,
            publisher: `Laurentius Salvius`,
            summary: `Linnaeus establishes a system of biological classification in which each animal is given a two part (binomial) name consisting of a genus followed by a species within that genus. Similar species are grouped into the same genera, similar genera into orders, similar orders into classes, and similar classes into kingdoms. On page 33, Linnaeus classifies all living elephants as a single genus and species, <i>Elephas maximus</i>, in the order Bruta, the class Mammalia, and the kingdom Animalia.`,
            title:`Systema Naturae per Regna Tria Naturae Secundum Classes, Ordines, Genera, Species, Cum Characteribus, Differentiis, Synonymis, Locis.`,
        }],
        [{
            container: `<i>Philosophical Transactions, Giving Some Account of the Present Undertaking Studies, and Labours of the Ingenious, in Many Considerable Parts of the World.</i> (Phil. Trans.), physically published academic journal`,
            contributors: `William Hunter (author)`,
            date: `1769/>06/>15`,
            duration: `pp. 34-45`,
            iteration: `Vol. 58`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1098/rstl.1768.0005" target="_blank">From publisher (DOI: 10.1098/rstl.1768.0005)</a><li><a href="https://archive.org/stream/philosophicaltra5817roya#page/34/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London<li><a href="https://www.jstor.org/stable/105753" target="_blank">From JSTOR</a>`,
            location: `London, England`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Printed by L. Davis and C. Reymers for the Royal Society`,
            summary: `TBA.`,
            title: `V. Observations on Bones, Commonly Supposed to Be Elephant Bones, Which Have Been Found Near the River Ohio in America.`,
        }],
        [{
            contributors: `Thomas Pennant (author)`,
            date: `1771/>03/>20`,
            duration: `382 pp.`,
            iteration: `1st ed.`,
            languages: `English`,
            links: `<li><a href="https://archive.org/stream/synopsisofquadru00penn#page/85/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries`,
            location: `Chester, England`,
            medium: `Physically published book, digitized`,
            publisher: `Printed by J. Monk`,
            summary: `The chapter on elephants, "XIV. Elephant.", is on pages 85-93.  Details TBA.`,
            title: `Synopsis of Quadrupeds`,
        }],
        [{
            contributors: `Carolus Linnaeus (coauthor); Johann Fridrich Gmelin (coauthor)`,
            date: `1788`,
            duration: `500 pp.`,
            eyedee: `Linnaeus_Gmelin_1788`,
            iteration: `13th ed., Tome 1`,
            languages: `Latin`,
            links: `<li><a href="https://archive.org/stream/mobot31753000801537#page/58/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Missouri Botanical Garden<li><a href="https://archive.org/stream/carolilinnsys01linn#page/58/mode/2up" target="_blank">From Internet archive</a>, copy provided by NCSU Libraries`,
            location: `Leizpig, Germany`,
            medium: `Physically published book, digitized`,
            publisher: `Georg. Emmanuel Beer`,
            summary: `The 13th edition of <a id="Linnaeus_1758_color_0" onclick="goToSource('1700-1799','Linnaeus_1758', this.id)">Linnaeus, 1758</a> with additions from Johann Fridrich Gmelin.  The section on elephants has been expanded but retains most of Linnaeus's original description, and can be found on page 58.`,
            title: `Systema Naturae per Regna Tria Naturae Secundum Classes, Ordines, Genera, Species, Cum Characteribus, Differentiis, Synonymis, Locis.`,
            
        }],
        [{
            contributors: `Johann Friedrich Blumenbach (author)`,
            date: `1797/>03/>20`,
            duration: `714 pp.`,
            eyedee: `Blumenbach_1797`,
            iteration: `5th ed.`,
            languages: `German, Latin`,
            links: `<li><a href="https://www.google.com/books/edition/Handbuch_der_Naturgeschichte/c4g5AAAAcAAJ?hl=en&gbpv=1&pg=PA124" target="_blank">From Google Books</a>, copy provided by Bayerische Staatsbibliothek (<a href="https://web.archive.org/web/20210207161402/https://books.googleusercontent.com/books/content?req=AKW5Qae5HmmtQeVus5uQJRzeuTVfw17qZB9b6zEByrLwdDTBi2D_zmnmyg3Q9P5iuGAEz426xOgn1CeZuLmdg7efp_HzPSXoGIdqiLVnFdD7uDEagC5dZVoMYifJtn8JPlOGiBi8d96-0HdXcyxXMjF7FkKx6pz8AcXVnaQfSvKNN__TRgR3_r_TdmhOnQy6-9kBPZH_hKbFM-v_Tam_yLWkaJDG-7-XcL4JYFUHX57lVF5z0O8VTFavnKaAWXO8BGuOnKqwWdW7CKHeI2cqcsiFsFHs-Z8QyA" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://www.google.com/books/edition/D_Joh_Fr_Blumenbachs_Handbuch_der_Naturg/d5dlAAAAcAAJ?hl=en&gbpv=1&pg=PA124" target="_blank">From Google Books</a>, copy provided by Bayerische Staatsbibliothek (<a href="https://web.archive.org/web/20210207161809/https://books.googleusercontent.com/books/content?req=AKW5Qac42eZ_lX1QQ1nrFIwgtJlbjNpkClqTHU5cpAqlGNpovwSsS71MFIVNZQ_YjcrHA5Wh8IdRpxdlopejNK2xfO80rWUxiVKqsSF-Pn4qSj_3yiZa0sPtpVvSajNGlX-U7-_DuvWmoGrnlnfBAXV51O5ArKnInLmIFGyWpIzhzt47WscOzI_g6o1RNtVzcLvFtJFAkswBI6T4QdUGKjuf85FjvpYUKApw4MV-lneuMqwpPKrSLOWhJqW7XsXvdeZC0uH3YoNBegoZ7cV-dWQRFv1EnFYNREvdqNjDqMbbH7p8rEQvRn8" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://www.google.com/books/edition/_/xTZcAAAAcAAJ?hl=en&gbpv=1&pg=PA124" target="_blank">From Google Books</a>, copy provided by Bayerische Staatsbibliothek (<a href="https://web.archive.org/web/20210207162329/https://books.googleusercontent.com/books/content?req=AKW5Qae40lEcE9cWPn5gETbzSol6VGbpbBJLhIrnV9bsTANoMldU-zmaojHifTPkxmeKNaPwnEMlLDOdPNzvlo8uu6CNAnflq6N89Tha21PqcF6l20OnIreDaVORXZGOXJJQU9B66ThAlQ8-VsZlJxN5P57T7jjDiuDnOqlFHqXv9gcJ1S-EUiOLZxxeBBvHIKJBeh7jdbgKzT9hsix0e2qHpo-tF2LdWsLHSmtxE1Yl9j8CHjZHOijSKgvG3A-FOOsTyIrEGU3VK_8pJseheksfyO_jHddiuA" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://www.google.com/books/edition/D_Joh_Friedr_Blumenbachs_Handbuch_der_Na/xaxgAAAAcAAJ?hl=en&gbpv=1&pg=PA124" target="_blank">From Google Books</a>, copy provided by the British Library (<a href="https://web.archive.org/web/20210207163638/https://books.googleusercontent.com/books/content?req=AKW5QafTV_Mr9vnGqXUzzutnF21c2L-72y2P80CZ7Zaw2h_LMjjxhqc2PfY87gORmI371m46nnVmFK8xcd32BLNijlbhu4BOLVFm9sXGUiB5-v1QzdYaWymC6T6S5Zbepn7Sh2M8qDYbk0SdZzGW7lfpba1A9IAL4GbhB0XakJkbrrEhIZknGnYoVmAc_99xKP9AwqQyCH4ifR5kwC_BKYKLmwAYzR-SwdhukXf-eHXra0uHim6qiPxHC7EhYEVZU01kKU3_ptfzAcWzCTLEJpn0J0TocWudcc24OshJQyy3Dde6-KzCbw4" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://archive.org/stream/djohfrblumenbach00blum#page/124/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries <li><a href="https://reader.digitale-sammlungen.de/de/fs1/object/goToPage/bsb10074883.html?pageNo=148" target="_blank">From Bayerische Staatsbibliothek</a> (<a href="https://web.archive.org/web/20210207011419/https://download.digitale-sammlungen.de/pdf/16126596538888bsb10074883.pdf" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://reader.digitale-sammlungen.de/de/fs1/object/goToPage/bsb11271835.html?pageNo=146" target="_blank">From Bayerische Staatsbibliothek</a> (<a  href="https://web.archive.org/web/20210207011458/https://download.digitale-sammlungen.de/pdf/16126597818888bsb11271835.pdf" target="_blank">archived in the Wayback Machine</a>) <li><a href="https://reader.digitale-sammlungen.de/de/fs1/object/goToPage/bsb11112082.html?pageNo=142" target="_blank">From Bayerische Staatsbibliothek</a> (<a  href="https://web.archive.org/web/20210207011638/https://download.digitale-sammlungen.de/pdf/16126599738888bsb11112082.pdf" target="_blank">archived in the Wayback Machine</a>) <li><a href="http://access.bl.uk/item/viewer/ark:/81055/vdc_100027397547.0x000001#?c=0&m=0&s=0&cv=147&xywh=-1344%2C-127%2C5158%2C2535" target="_blank">From the British Library</a> <li><a href="https://blumenbach-online.de/fileadmin/wikiuser/Daten_Digitalisierung/ID%2000026/00026.pdf" target="_blank">From the Göttingen Academy of Sciences's Blumenbach Online</a> <li><a href="https://blumenbach-online.de/fileadmin/wikiuser/Daten_Digitalisierung/ID%2000038/00038.pdf" target="_blank">From the Göttingen Academy of Sciences's Blumenbach Online</a> <li><a href="https://www.deutschestextarchiv.de/book/view/blumenbach_naturgeschichte_1797?p=146" target="_blank">From the Deutsches Textarchiv</a>`,
            location: `Göttingen, Germany`,
            notes: `<li>Bottommost copy from the Göttingen Academy of Sciences's Blumenbach Online was owned by Blumenbach.`,
            publisher: `Johann Christian Dieterich`,
            summary: `Blumenbach recognizes two species of living elephants and describes them on pages 124-125. He gives each a distinct name, <i>Elephas asiaticus</i> for the Asian elephant and <i>E</i>. <i>africanus</i> for the African elephant, and places them in the order Belluae.`,
            medium: `Physically published book, digitized`,
            title: `Handbuch der Naturgeschichte.`,
        }],
        [{
            contributors: `Georges Léopold Chrétien Frédéric Dagobert Cuvier (author)`,
            date: `1798`,
            duration: `710 pp.`,
            eyedee: `Cuvier_1798`,
            iteration: `1st ed.`,
            languages: `French`,
            links: `<li><a href="https://archive.org/stream/tableaulment00cuvi#page/146/mode/2up" target="_blank">From Internet Archive</a>, copy provided by Smithsonian Libraries <li><a href="https://archive.org/stream/tableaulmen00cuvi#page/146/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the University of Toronto`,
            location: `Paris, France`,
            medium: `Physically published book, digitized`,
            notes: `<li>Published in year 6 of the French Republican calendar, established in 1793. The first year of the calendar began on September 22nd, 1792, meaning year 6 corresponds to 1798 (Convention nationale, 1793).`,
            publisher: `Printed by Baudouin for the Corps législatif and l'Institut national`,
            references: `<p class="refs">Convention nationale (1793). <a href="https://tolosana.univ-toulouse.fr/fr/notice/042658012" target="_blank"><i>Calendrier de la République française</i></a>. Paris: Imprimerie nationale France.</p>`,
            summary: `Cuvier recognizes two species of living elephants and describes them on pages 148-149. He gives each a distinct name, <i>Elephas indicus</i> for the Asian elephant and <i>E</i>. <i>capensis</i> for the African elephant, and states that elephants warrant placement in a new, unnamed order.`,
            title: `Tableau Élémentaire de l'Histoire Naturelle des Animaux.`,
        }],
        [{
            container: `<i>Philosophical Transactions of the Royal Society of London</i> (Phil. Trans. R. Soc. Lond.), physically published academic journal`,
            contributors: `John Corse (author)`,
            date: `1799/>06/>13`,
            duration: `pp. 205-236`,
            iteration: `[Vol. 89], Pt. 2`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1098/rstl.1799.0014" target="_blank">From publisher (DOI: 10.1098/rstl.1799.0014)</a><li><a href="https://archive.org/stream/philosophicaltra8917roya#page/205/mode/2up" target="_blank">From Internet Archive</a>, copy provided by the Natural History Museum Library, London<li><a href="https://www.jstor.org/stable/107034" target="_blank">From JSTOR</a>`,
            location: `London, England`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `W. Bulmer & Co.`,
            summary: `TBA.`,
            title: `XIII. Observations on the Different Species of Asiatic Elephants, and Their Mode of Dentition.`,
        }],
]