module.exports = [
    [{
            container: `<i>Elephant</i>, physically published academic journal`,
            contributors: `Peter Grubb (coauthor); Colin P. Groves (coauthor); Joseph P. Dudley (coauthor); Jeheskel Shoshani (coauthor)`,
            date: `2000/01`,
            duration: `pp. 1-4`,
            iteration: `Vol. 2, No. 4`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.22237/elephant/1521732169" target="_blank">From Wayne State University DigitalCommons (DOI: 10.22237/elephant/1521732169)</a>`,
            location: `Bloomfield Hills, Michigan, United States of America`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Elephant Research Foundation (ERF)`,
            summary: `TBA.`,
            title: `Living African Elephants Belong to Two Species: <i>Loxodonta africana</i> (Blumenbach, 1797) and <i>Loxodonta cyclotis</i> (Matschie, 1900)`,
        }],
        [{
            container: `<i>Elephant</i>, physically published academic journal`,
            contributors: `Colin P. Groves (coauthor); Peter Grubb (coauthor)`,
            date: `2000/01`,
            duration: `pp. 4-7`,
            iteration: `Vol. 2, No. 4`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.22237/elephant/1521732173" target="_blank">From Wayne State University DigitalCommons (DOI: 10.22237/elephant/1521732173)</a>`,
            location: `Bloomfield Hills, Michigan, United States of America`,
            medium: `Physically published academic journal article, digitized`,
            publisher: `Elephant Research Foundation (ERF)`,
            summary: `TBA.`,
            title: `Do <i>Loxodonta cyclotis</i> and <i>L</i>. <i>africana</i> Interbreed?`,   
        }],
        [{
            
            container: `<i>Heredity</i> (Hered.), digitally published academic journal`,
            contributors: `Prithiviraj Fernando (coauthor); Michael E. Pfrender (coauthor); Sandra E. Encalada (coauthor); Russell Lande (coauthor)`,
            date: `2000/03/01`,
            duration: `pp. 362-372`,
            iteration: `Vol. 84`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1046/j.1365-2540.2000.00674.x" target="_blank">From publisher (DOI: 10.1046/j.1365-2540.2000.00674.x)</a><li><a href="https://www3.nd.edu/~mpfrende/PDFs/Fernando%20et%20al%20Heredity%202000.pdf" target="_blank">From the University of Notre Dame</a><li><a href="https://www.researchgate.net/publication/290500155_Mitochondrial_DNA_variation_phylogeography_and_population_structure_of_the_Asian_elephant" target="_blank">From ResearchGate</a><li><a href="https://www.researchgate.net/publication/12554926_Fernando_P_Pfrender_ME_Encalada_SE_Lande_R_Mitochondrial_DNA_variation_phylogeography_and_population_structure_of_the_Asian_elephant_Heredity_84_362-372" target="_blank">From ResearchGate</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Nature Publishing Group`,
            summary: `TBA.`,
            title: `Mitochondrial DNA variation, phylogeography and population structure of the Asian elephant`,
        }],
        [{
            container: `<i>News in Physiological Sciences</i> (NIPS), digitally published academic journal`,
            contributors: `John B. West (author)`,
            date: `2002/04/01`,
            duration: `pp. 47-50`,
            iteration: `Vol. 17, Issue 2`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1152/nips.01374.2001" target="_blank">From publisher (DOI: 10.1152/nips.01374.2001)</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `American Physiological Society (APS)`,
            summary: `TBA.`,
            title: `Why Doesn't the Elephant Have a Pleural Space?`,
        }],
        [{
            container: `<i>PLoS Biology</i> (PLoS Biol.), digitally published academic journal`,
            contributors: `Prithiviraj Fernando (coauthor); T.N.C. Vidya (coauthor); John Payne (coauthor); Michael Stuewe (coauthor); Geoffrey Davison (coauthor); Raymond J. Alfred (coauthor); Patrick Andau (coauthor); Edwin Bosi (coauthor); Annelisa Kilbourn (coauthor); Don J. Melnick (coauthor)`,
            date: `2003/08/18`,
            duration: `pp. 110-115`,
            iteration: `Vol. 1, Issue 1`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1371/journal.pbio.0000006" target="_blank">From publisher (DOI: 10.1371/journal.pbio.0000006)</a><li><a href="https://academiccommons.columbia.edu/doi/10.7916/D8W958ZZ" target="_blank">From Columbia University Libraries</a><li><a href="https://www.researchgate.net/publication/6233845_DNA_Analysis_Indicates_That_Asian_Elephants_Are_Native_to_Borneo_and_Are_Therefore_a_High_Priority_for_Conservation" target="_blank">From ResearchGate</a><li><a href="https://fh-sites.imgix.net/sites/4169/2020/06/17185748/fernando_2003.pdf" target="_blank">From imgIX</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Public Library of Science (PLoS)`,
            summary: `TBA.`,
            title: `DNA Analysis Indicates That Asian Elephants Are Native to Borneo and Are Therefore a High Priority for Conservation`,
        }],
        [{
            container: `<i>Physiological and Biochemical Zoology: Ecological and Evolutionary Approaches</i> (Phys. Biochem. Zool.), digitally published academic journal`,
            contributors: `Kathleen E. Hunt (coauthor); Samuel K. Wasser (coauthor)`,
            date: `2003/>12`,
            duration: `pp. 918-928`,
            iteration: `Vol. 76, No. 6`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1086/380209" target="_blank">From publisher (DOI: 10.1086/380209)</a> <li><a href="https://www.jstor.org/stable/10.1086/380209" target="_blank">From JSTOR</a> <li><a href="https://www.researchgate.net/publication/5384225_Effect_of_Long-Term_Preservation_Methods_on_Fecal_Glucocorticoid_Concentrations_of_Grizzly_Bear_and_African_Elephant" target="_blank">From ResearchGate</a>`,
            location: `Chicago, Illinois, United States of America`,
            medium: `Digitally published academic journal article`,
            publisher: `The University of Chicago Press`,
            summary: `TBA.`,
            title: `Effect of Long‐Term Preservation Methods on Fecal Glucocorticoid Concentrations of Grizzly Bear and African Elephant`,
        }],
        [{
            container: `<i>Quaternary International</i> (Quat. Int.), digitally published academic journal`,
            contributors: `Jeheskel Shoshani (coauthor); Pascal Tassy (coauthor)`,
            date: `2004/06/26`,
            duration: `pp. 5-20`,
            iteration: `Vols. 126-128 <i>Studying Proboscideans: knowledge, Problems and Perspectives. Selected papers from"The world of Elephants" Congress, Rome</i>`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1016/j.quaint.2004.04.011" target="_blank">From publisher (DOI: 10.1016/j.quaint.2004.04.011)</a><li><a href="http://biochem.flas.kps.ku.ac.th/elephant.pdf" target="_blank">From Envi Biochem KPS ชีวเคมี สิ่งแวดล้อม เทคโนโลยีและชีวิต</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Elsevier`,
            summary: `TBA.`,
            title: `Advances in proboscidean taxonomy & classification, anatomy & physiology, and ecology & behavior`,
        }],    
        [{
            container: `<i>YouTube</i>, website`,
            contributors: `jawed (uploader)`,
            date: `2005/04/23`,
            duration: `18 s`,
            languages: `English`,
            links: `<li><a href="https://www.youtube.com/watch?v=jNQXAC9IVRw" target="_blank">From publisher</a>`,
            location: `N/A`,
            medium: `Digitally published video`,
            publisher: `YouTube`,
            summary: `The first YouTube video, filmed at the elephant exhibit at the San Diego Zoo.`,
            title: `Me at the zoo`,
        }],    
        [{
            container: `<i>Genetics</i> (Genet.), digitally published academic journal`,
            contributors: `Shozo Yokoyama (coauthor); Naomi Takenaka (coauthor); Dalen W. Agnew (coauthor); Jeheskel Shoshani (coauthor)`,
            date: `2005/05/01`,
            duration: `pp. 335-344`,
            iteration: `Vol. 170, No. 1`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1534/genetics.104.039511" target="_blank">From publisher (DOI: 10.1534/genetics.104.039511)</a><li><a href="https://www.researchgate.net/publication/7952815_Elephants_and_Human_Color-Blind_Deuteranopes_Have_Identical_Sets_of_Visual_Pigments" target="_blank">From ResearchGate</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Genetics Society of America (GSA)`,
            summary: `TBA.`,
            title: `Elephants and Human Color-Blind Deuteranopes Have Identical Sets of Visual Pigments`,
        }],
        [{
            container: `<i>Brain Research Bulletin</i> (Brain Res. Bull.), digitally published academic journal`,
            contributors: `Jeheskel Shoshani (coauthor); William J. Kupsky (coauthor); Gary H. Marchant (coauthor)`,
            date: `2006/04/18`,
            duration: `pp. 124-157`,
            iteration: `Vol. 70, Issue 2`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1016/j.brainresbull.2006.03.016" target="_blank">From publisher (DOI: 10.1016/j.brainresbull.2006.03.016)</a><li><a href="http://drnissani.net/MNISSANI/ElephantCorner/ElephantBrain_shoshani.pdf" target="_blank">From Moti Nissani's Webpage</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Elsevier`,
            summary: `TBA.`,
            title: `Elephant brain: Part I: Gross morphology, functions, comparative anatomy, and evolution`,
        }],
        [{
            container: `<i>Applied Animal Behaviour Science</i> (Appl. Anim. Behav. Sci.), digitally published academic journal`,
            contributors: `Iain Douglas-Hamilton (coauthor); Shivani Bhalla (coauthor); George Wittemyer (coauthor); Fritz Vollrath (coauthor)`,
            date: `2006/06/27`,
            duration: `pp. 87-102`,
            iteration: `Vol. 100, Issues 1-2`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1016/j.applanim.2006.04.014" target="_blank">From publisher (DOI: 10.1016/j.applanim.2006.04.014)</a><li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.588.1305" target="_blank">From CiteSeerX</a><li><a href="https://web.archive.org/web/20121127020837/http://www.savetheelephants.org/files/pdf/publications/2006%20Douglas-Hamilton%20et%20al%20Behavioural%20reactions%20of%20elephants%20to%20a%20dying%20matriarch.pdf" target="_blank">From Save the Elephants</a>, archived in the Wayback Machine`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Elsevier`,
            summary: `TBA.`,
            title: `Behavioural reactions of elephants towards a dying and deceased matriarch`,
        }],
        [{
            container: `<i>PLoS Biology</i> (PLoS Biol.), digitally published academic journal`,
            contributors: `Liza Gross (author)`,
            date: `2007/04/03`,
            duration: `pp. 0001-0003`,
            iteration: `Vol. 5, Issue 4`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1371/journal.pbio.0050115" target="_blank">From publisher (DOI: 10.1371/journal.pbio.0050115)</a>`,
            location: `N/A`,
            medium: `Digitally published article`,
            publisher: `Public Library of Science (PLoS)`,
            summary: `A laymen-oriented summary of <a id="Blake_et_al_2007_color" onclick="goToSource('2000-2021','Blake_et_al_2007', this.id)">Blake et al., 2007</a>.`,
            title: `In the Shadows of the Congo Basin Forest, Elephants Fall to the Illegal Ivory Trade`,
        }],
        [{
            container: `<i>PLoS Biology</i> (PLoS Biol.), digitally published academic journal`,
            contributors: `Stephen Blake (coauthor); Samantha Strindberg (coauthor); Patrick Boudjan (coauthor); Calixte Makombo (coauthor); Inogwabini Bila-Isia (coauthor); Omari Ilambu (coauthor); Falk Grossmann (coauthor); Lambert Bene-Bene (coauthor); Bruno de Semboli (coauthor); Valentin Mbenzo (coauthor); Dino S'hwa (coauthor); Rosine Bayogo (coauthor); Liz Williamson (coauthor); Mike Fay (coauthor); John Hart (coauthor); Fiona Maisels (coauthor)`,
            date: `2007/04/03`,
            duration: `pp. 0945-0953`,
            eyedee: `Blake_et_al_2007`,
            iteration: `Vol. 5, Issue 4`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1371/journal.pbio.0050111" target="_blank">From publisher (DOI: 10.1371/journal.pbio.0050111)</a><li><a href="https://dspace.stir.ac.uk/handle/1893/1176#.YCfc_3WYXx4" target="_blank">From the University of Stirling Online Research Repository (STORRE)</a><li><a href="https://www.academia.edu/11927981/Forest_elephant_crisis_in_the_Congo_Basin" target="_blank">From Academia</a><li><a href="https://www.academia.edu/12991147/Forest_Elephant_Crisis_in_the_Congo_Basin" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/6415339_Forest_Elephant_Crisis_in_the_Congo_Basin" target="_blank">From ResearchGate</a><li><a href="https://www.researchgate.net/publication/215934739_Forest_elephant_crisis_in_the_Congo_Basin" target="_blank">From ResearchGate</a><li><a href="https://www.sciencebuzz.com/forest-elephant-crisis-in-the-congo-basin/" target="_blank">From Science Buzz</a>`,
            location: `N/A`,
            medium: `Digitally published article`,
            publisher: `Public Library of Science (PLoS)`,
            summary: `TBA.`,
            title: `Forest Elephant Crisis in the Congo Basin`,
        }],
        [{
            container: `<i>Journal of Anatomy</i> (J. Anat.), digitally published academic journal`,
            contributors: `D.M. Bouley (coauthor); C.N. Alarcón (coauthor); T. Hildebrandt (coauthor); Caitlin E. O’Connell‐Rodwell (coauthor)`,
            date: `2007/08/15`,
            duration: `pp. 428-435`,
            iteration: `Vol. 211, Issue 4`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1111/j.1469-7580.2007.00792.x" target="_blank">From publisher (DOI: 10.1111/j.1469-7580.2007.00792.x)</a><li><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2375831/" target="_blank">From PubMed Central</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Wiley Online Library on behalf of the Anatomical Society (AS)`,
            summary: `TBA.`,
            title: `The distribution, density and three‐dimensional histomorphology of Pacinian corpuscles in the foot of the Asian elephant (<i>Elephas maximus</i>) and their potential role in seismic communication`,
        }],
        [{
            container: `<i>Molecular Ecology</i> (Mol. Ecol.), digitally published academic journal`,
            contributors: `Elizabeth A. Archie (coauthor); Julie A. Hollister‐Smith (coauthor); Joyce H. Poole (coauthor); Phyllis C. Lee (coauthor); Cynthia J. Moss (coauthor); Jésus E. Maldonado (coauthor); Robert C. Fleischer (coauthor); Susan C. Alberts (coauthor)`,
            date: `2007/09/04`,
            duration: `pp. 4138-4148`,
            iteration: `Vol. 16, Issue 19`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1111/j.1365-294X.2007.03483.x" target="_blank">From publisher (DOI: 10.1111/j.1365-294X.2007.03483.x)</a><li><a href="https://web.archive.org/web/20160308224835/https://sites.biology.duke.edu/albertslab/pdfs/Archie&al_2007.pdf" target="_blank">From the Duke University Department of Biology</a>, archived in the Wayback Machine<li><a href="https://repository.si.edu/handle/10088/6000" target="_blank">From Smithsonian Research Online DSpace Repository</a><li><a href="https://web.archive.org/web/20170110131548/http://www3.nd.edu:80/~earchie/documents/1543inbreeding.pdf" target="_blank">From the University of Notre Dame</a>, archived in the Wayback Machine<li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.515.7606" target="_blank">From CiteSeerX</a><li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.510.5270" target="_blank">From CiteSeerX</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Wiley Online Library`,
            summary: `TBA.`,
            title: `Behavioural inbreeding avoidance in wild African elephants`,
        }],
        [{
            container: `<i>Current Biology</i> (Curr. Biol.), digitally published academic journal`,
            contributors: `Lucy E. King (coauthor); Iain Douglas-Hamilton (coauthor); Fritz Vollrath (coauthor)`,
            date: `2007/10/09`,
            duration: `2 pp.`,
            iteration: `Vol. 17, Issue 19`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1016/j.cub.2007.07.038" target="_blank">From publisher (DOI: 10.1016/j.cub.2007.07.038)</a><li><a href="https://www.sciencedirect.com/science/article/pii/S0960982207017186" target="_blank">From Elsevier</a><li><a href="https://core.ac.uk/download/pdf/82503538.pdf" target="_blank">From CORE</a><li><a href="https://www.researchgate.net/publication/5920247_African_elephants_run_from_the_sound_of_disturbed_bees" target="_blank">From ResearchGate</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Cell Press`,
            summary: `TBA.`,
            title: `African elephants run from the sound of disturbed bees`,
        }],
        [{
            container: `<i>The IUCN Red List of Threatened Species</i>, digitally published scientific database`,
            contributors: `J. Blanc (author); D. Balfour (reviewer); C. Craig (reviewer); Holly T. Dublin (reviewer); Chris Thouless (reviewer)`,
            date: `2008/06/30`,
            duration: `16 pp.`,
            languages: `English`,
            links: `<li><a href="https://dx.doi.org/10.2305/IUCN.UK.2008.RLTS.T12392A3339343.en" target="_blank">From publisher (DOI: 10.2305/IUCN.UK.2008.RLTS.T12392A3339343.en)</a>`,
            location: `N/A`,
            medium: `Digitally published article`,
            publisher: `International Union for Conservation of Nature (IUCN)`,
            summary: `TBA.`,
            title: `<i>Loxodonta africana</i>, African elephant`,
        }],
        [{
            container: `<i>Animal Welfare</i> (Anim. Welf.), digitally published academic journal`,
            contributors: `D.L. Wells (coauthor); R.M. Irwin (coauthor)`,
            date: `2008/11/01`,
            duration: `pp. 335-340`,
            iteration: `Vol. 17, No. 4`,
            languages: `English`,
            links: `<li><a href="https://www.ingentaconnect.com/content/ufaw/aw/2008/00000017/00000004/art00001" target="_blank">From publisher</a> through Ingenta Connect`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Universities Federation for Animal Welfare (UFAW)`,
            summary: `TBA.`,
            title: `Auditory stimulation as enrichment for zoo-housed Asian elephants (<i>Elephas maximus</i>)`,
        }],
        [{
            container: `<i>Philosophical Transactions of the Royal Society B</i> (Phil. Trans. R. Soc. B), digitally published academic journal`,
            contributors: `T.N.C. Vidya (coauthor); Raman Sukumar (coauthor); Don J. Melnick (coauthor)`,
            date: `2008/11/18`,
            duration: `pp. 893-902`,
            iteration: `Vol. 276, Issue 1658`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1098/rspb.2008.1494" target="_blank">From publisher (DOI: 10.1098/rspb.2008.1494)</a><li><a href="https://www.researchgate.net/publication/23483866_Range-wide_mtDNA_phylogeography_yields_insights_into_the_origins_of_Asian_elephants" target="_blank">From ResearchGate</a><li><a href="https://www.jstor.org/stable/30243964" target="_blank">Digitized physical copy from JSTOR</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `The Royal Society`,
            summary: `TBA.`,
            title: `Range-wide mtDNA phylogeography yields insights into the origins of Asian elephants`,
        }],
        [{
            container: `<i>Science</i> (Sci.), digitally published academic journal`,
            contributors: `Ros Clubb (coauthor); Marcus Rowcliffe (coauthor); Phyllis C. Lee (coauthor); Khyne U. Mar (coauthor); Cynthia J. Moss (coauthor); Georgia J. Mason (coauthor)`,
            date: `2008/12/12`,
            duration: `p. 1649`,
            iteration: `Vol. 322, Issue 5908`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1126/science.1164298" target="_blank">From publisher (DOI: 10.1126/science.1164298)</a><li><a href="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.940.3314" target="_blank">From CiteSeerX</a><li><a href="https://www.academia.edu/5078924/Compromised_Survivorship_in_Zoo_Elephants" target="_blank">From Academia</a><li><a href="https://www.researchgate.net/publication/23655237_Compromised_Survivorship_in_Zoo_Elephants" target="_blank">From ResearchGate</a><li><a href="https://web.archive.org/web/20090529195253/http://www.elephants.com/media/Compromised%20Survivorship%20in%20Zoo%20Elephants.pdf" target="_blank">From the Elephant Sanctuary</a>, archived in the Wayback Machine<li><a href="https://endcap.eu/wp-content/uploads/2012/06/Compromised-Survivorship-in-Zoo-Elephants-2008-G.-Mason-et-al.pdf" target="_blank">From ENDCAP</a><li><a href="http://www.freewpzelephants.com/wp-content/uploads/2008/12/zoo-life-harmful-to-elephants.pdf" target="_blank">From the Friends of Woodland Park Zoo Elephants</a><li><a href="https://web.archive.org/web/20170808115604/http://www.rufford.org/files/Science%20Vol%20322%2012%20December%202008.pdf" target="_blank">From the Rufford Foundation</a>, archived in the Wayback Machine<li><a href="https://web.archive.org/web/20170809215617/http://www.rufford.org/files/Science%20Clubb%20etal%202008.pdf" target="_blank">From the Rufford Foundation</a>, archived in the Wayback Machine`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `American Association for the Advancement of Science (AAAS)`,
            summary: `TBA.`,
            title: `Compromised Survivorship in Zoo Elephants`,
        }],
        [{
            container: `<i>Biotropica</i>, digitally published academic journal`,
            contributors: `Ahimsa Campos‐Arceiz (author)`,
            date: `2009/06/29`,
            duration: `pp. 406-407`,
            iteration: `Vol. 41, Issue 4`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1111/j.1744-7429.2009.00525.x" target="_blank">From publisher (DOI: 10.1111/j.1744-7429.2009.00525.x)</a><li><a href="http://www.chm.bris.ac.uk/sillymolecules/shithappens.pdf" target="_blank">From the University of Bristol's School of Chemistry</a> <li><a href="https://www.academia.edu/1486428/Shit_Happens_to_be_Useful_Use_of_Elephant_Dung_as_Habitat_by_Amphibians" target="_blank">From Academia</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Wiley Online Library on behalf of the Association for Tropical Biology and Conservation`,
            summary: `TBA.`,
            title: `Shit Happens (to be Useful)! Use of Elephant Dung as Habitat by Amphibians`,
        }],
        [{
            container: `<i>The Anatomical Record: Advances in Integrative Anatomy and Evolutionary Biology</i> (Anat. Rec.), digitally published academic journal`,
            contributors: `Nancy E. Todd (author)`,
            date: `2009/12/28`,
            duration: `pp. 62-73`,
            iteration: `Vol. 293, Issue 1`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1002/ar.21011" target="_blank">From publisher (DOI: 10.1002/ar.21011)</a> through Wiley Online Library`,
            location: `Rockville, Maryland, United States of America`,
            medium: `Digitally published academic journal article`,
            publisher: `American Association for Anatomy (AAA)`,
            summary: `TBA.`,
            title: `Qualitative Comparison of the Cranio‐Dental Osteology of the Extant Elephants, <i>Elephas maximus</i> (Asian Elephant) and <i>Loxodonta africana</i> (African Elephant)`,
        }],
        [{
            container: `<i>The Anatomical Record: Advances in Integrative Anatomy and Evolutionary Biology</i> (Anat. Rec.), digitally published academic journal`,
            contributors: `Nancy E. Todd (author)`,
            date: `2009/12/28`,
            duration: `pp. 74-90`,
            iteration: `Vol. 293, Issue 1`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1002/ar.21010" target="_blank">From publisher (DOI: 10.1002/ar.21010)</a> through Wiley Online Library<li><a href="https://www.academia.edu/10092521/New_Phylogenetic_Analysis_of_the_Family_Elephantidae_Based_on_Cranial_Dental_Morphology" target="_blank">From Academia</a>`,
            location: `Rockville, Maryland, United States of America`,
            medium: `Digitally published academic journal article`,
            publisher: `American Association for Anatomy (AAA)`,
            summary: `TBA.`,
            title: `New Phylogenetic Analysis of the Family Elephantidae Based on Cranial‐Dental Morphology`,
        }], 
        [{
            container: `<i>PLoS Biology</i> (PLoS Biol.), digitally published academic journal`,
            contributors: `Nadin Rohland (coauthor); David Reich (coauthor); Swapan Mallick (coauthor); Matthias Meyer (coauthor); Richard E. Green (coauthor); Nicholas J. Georgiadis (coauthor); Alfred L. Roca (coauthor); Michael Hofreiter (coauthor)`,
            date: `2010/12/21`,
            duration: `10 pp.`,
            eyedee: `Rohland_et_al_2010`,
            iteration: `Vol. 8, Issue 12`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1371/journal.pbio.1000564" target="_blank">From publisher (DOI: 10.1371/journal.pbio.1000564)</a><li><a href="https://genetics.med.harvard.edu/reichlab/Reich_Lab/Publications_files/2010_Rohland_Mastodon.pdf" target="_blank">From the David Reich Lab</a><li><a href="http://nrs.harvard.edu/urn-3:HUL.InstRepos:4874828" target="_blank">From Digital Access to Scholarship at Harvard (DASH)</a><li><a href="https://europepmc.org/article/PMC/3006346" target="_blank">From Europe PMC</a><li><a href="https://www.academia.edu/35196283/Genomic_DNA_sequences_from_mastodon_and_woolly_mammoth_reveal_deep_speciation_of_forest_and_savanna_elephants" target="_blank">From Academia</a>
            <li><a href="https://www.researchgate.net/publication/49726374_Genomic_DNA_Sequences_from_Mastodon_and_Woolly_Mammoth_Reveal_Deep_Speciation_of_Forest_and_Savanna_Elephants" target="_blank">From ResearchGate</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Public Library of Science (PLoS)`,
            summary: `TBA.`,
            title: `Genomic DNA Sequences from Mastodon and Woolly Mammoth Reveal Deep Speciation of Forest and Savanna Elephants`,
        }],
        [{
            container: `<i>Nature News</i>, published news website`,
            contributors: `Natasha Gilbert (author)`,
            date: `2010/12/21`,
            duration: `549 words`,
            languages: `N/A`,
            links: `<li><a href="https://doi.org/10.1038/news.2010.691" target="_blank">From publisher (DOI: 10.1038/news.2010.691)</a>`,
            location: `London, England`,
            medium: `Digitally published news article`,                
            publisher: `Nature Publishing Group`,
            summary: `A laymen-oriented summary of <a id="Rohland_et_al_2010_color" onclick="goToSource('2000-2021','Rohland_et_al_2010', this.id)">Rohland et al., 2010</a> with quotes from one of the paper's coauthors.`,
            title: `African elephants are two distinct species`,
        }],
        [{
            container: `<i>Smithsonian Magazine</i>, digitally published magazine`,
            contributors: `Laura Helmuth (author)`,
            date: `2010/12/27`,
            duration: `476 words`,
            languages: `N/A`,
            links: `<li><a href="https://www.smithsonianmag.com/science-nature/the-elephant-family-tree-extinct-and-extant-40883904/" target="_blank">From publisher</a>`,
            location: `N/A`,
            medium: `Digitally published magazine article`,                
            publisher: `Smithsonian`,
            summary: `A laymen-oriented summary of <a id="Rohland_et_al_2010_color" onclick="goToSource('2000-2021','Rohland_et_al_2010', this.id)">Rohland et al., 2010</a>.`,
            title: `The Elephant Family Tree, Extinct and Extant`,
        }],
        [{
            container: `<i>The IUCN Red List of Threatened Species</i>, digitally published scientific database`,
            contributors: `A. Gopala (coauthor); O. Hadian (coauthor); Sunarto (coauthor); A. Sitompul (coauthor); A. Williams (coauthor); P. Leimgruber (coauthor); S.E. Chambliss (coauthor); D. Gunaryardi (coauthor); S. Hedges (reviewer); A. Desai (reviewer); M. Tyson (reviewer)`,
            date: `2011/08/01`,
            duration: `11 pp.`,
            languages: `English`,
            links: `<li><a href="https://dx.doi.org/10.2305/IUCN.UK.2011-2.RLTS.T199856A9129626.en" target="_blank">From publisher (DOI: 10.2305/IUCN.UK.2011-2.RLTS.T199856A9129626.en)</a>`,
            location: `N/A`,
            medium: `Digitally published article`,
            publisher: `International Union for Conservation of Nature (IUCN)`,
            summary: `TBA.`,
            title: `<i>Elephas maximus</i> ssp. <i>maximus</i>, Sumatran elephant`,
        }],
        [{
            container: `<i>Brain, Behavior and Evolution</i> (Brain Behav. Evol.), digitally published academic journal`,
            contributors: `Busisiwe C. Maseko (coauthor); Bob Jacobs (coauthor); Muhammad A. Spocter (coauthor); Chet C. Sherwood (coauthor); P.R. Hoff (coauthor); Paul R. Manger (coauthor)`,
            date: `2012/12/29`,
            duration: `pp. 40-55`,
            iteration: `Vol. 81`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1159/000345565" target="_blank">From publisher (DOI: 10.1159/000345565)</a><li><a href="https://web.archive.org/web/20170811055855/https://www.coloradocollege.edu/dotAsset/e0c9b276-e4f9-4dea-8b16-495715d9ff9e.pdf" target="_blank">From Colorado College</a>, archived in the Wayback Machine<li><a href="https://www.researchgate.net/publication/234076293_Qualitative_and_Quantitative_Aspects_of_the_Microanatomy_of_the_African_Elephant_Cerebellar_Cortex" target="_blank">From ResearchGate</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Karger`,
            summary: `TBA.`,
            title: `Qualitative and Quantitative Aspects of the Microanatomy of the African Elephant Cerebellar Cortex`,
        }],      
        [{
            container: `<i>Zoological Journal of the Linnean Society</i> (Zool. J. Linn. Soc.), digitally published academic journal`,
            contributors: `Advait M. Jukar (coauthor); S. Kathleen Lyons (coauthor); Mark D. Uhen (coauthor)`,
            date: `2018/01/16`,
            duration: `pp. 919-931`,
            iteration: `Vol. 184, Issue 3`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1093/zoolinnean/zlx108" target="_blank">From publisher (DOI: 10.1093/zoolinnean/zlx108)</a>`,
            location: `London, England`,
            medium: `Digitally published academic journal article`,
            publisher: `The Linnean Society of London`,
            summary: `TBA.`,
            title: `A cranial correlate of body mass in proboscideans`,
        }],      
        [{
            container: `<i>Proceedings of the National Academy of Sciences</i> (PNAS), digitally published academic journal`,
            contributors: `Eleftheria Palkopoulou (coauthor); Mark Lipson (coauthor); Swapan Mallick (coauthor); Svend Nielsen (coauthor); Nadin Rohland (coauthor); Sina Baleka (coauthor); Emil Karpinski (coauthor); Atma M. Ivancevic (coauthor); Thu-Hien To (coauthor); R. Daniel Kortschak (coauthor); Joy M. Raison (coauthor); Zhipeng Qu (coauthor); Tat-Jun Chin (coauthor); Kurt W. Alt (coauthor); Stefan Claesson (coauthor); Love Dalén (coauthor); Ross D.E. MacPhee (coauthor); Harald Meller (coauthor); Alfred L. Roca (coauthor); Oliver A. Ryder (coauthor); David Heiman (coauthor); Sarah Young (coauthor); Matthew Breen (coauthor); Christina Williams (coauthor); Bronwen L. Aken (coauthor); Magali Ruffier (coauthor); Elinor Karlsson (coauthor); Jeremy Johnson (coauthor); Federica Di Palma (coauthor); Jessica Alfoldi (coauthor);  David L. Adelson (coauthor); Thomas Mailund (coauthor); Kasper Munch (coauthor); Kerstin Lindblad-Toh (coauthor); Michael Hofreiter (coauthor); Hendrik Poinar (coauthor); David Reich (coauthor)`,
            date: `2018/02/26`,
            duration: `pp. E2566–E2574`,
            eyedee: `Palkopoulou_et_al_2018`,
            iteration: `Vol. 115, No. 11`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1073/pnas.1720554115" target="_blank">From publisher (DOI: 10.1073/pnas.1720554115)</a><li><a href="https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/2018_PNAS_ElephantGenome_3.pdf" target="_blank">From the David Reich Lab</a><li><a href="https://www.researchgate.net/publication/323409209_A_comprehensive_genomic_history_of_extinct_and_living_elephants" target="_blank">From ResearchGate</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `National Academy of Sciences (NAS)`,
            summary: `TBA.`,
            title: `A comprehensive genomic history of extinct and living elephants`,
        }], 
        [{
            container: `<i>Behavioral Ecology</i> (Behav. Ecol.), digitally published academic journal`,
            contributors: `Michael A. Pardo (coauthor); Joyce H. Poole (coauthor); Angela S. Stoeger (coauthor); Peter H. Wrege (coauthor); Caitlin E. O'Connell-Rodwell (coauthor); Udaha Kapugedara Padmalal (coauthor); Shermin de Silva (coauthor)`,
            date: `2019/02/23`,
            duration: `pp. 809-820`,
            eyedee: `Pardo_et_al_2019`,
            iteration: `Vol. 30, Issue 3`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1093/beheco/arz018" target="_blank">From publisher (DOI: 10.1093/beheco/arz018)</a> <li><a href="https://www.researchgate.net/publication/331875685_Differences_in_combinatorial_calls_among_the_3_elephant_species_cannot_be_explained_by_phylogeny" target="_blank">From ResearchGate</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,
            publisher: `Oxford Academic`,
            summary: `TBA.`,
            title: `Differences in combinatorial calls among the 3 elephant species cannot be explained by phylogeny`,
        }],
        [{
            container: `<i>Maximus</i>, published blog`,
            contributors: `Michael A. Pardo (author)`,
            date: `2019/05/01`,
            duration: `798 words`,
            languages: `N/A`,
            links: `<li><a href="https://maximus.trunksnleaves.org/2019/05/01/call-combinations-differ/" target="_blank">From publisher</a>`,
            location: `N/A`,
            medium: `Published blog post`,                
            publisher: `Trunks & Leaves Inc.`,
            summary: `A laymen-oriented summary of <a id="Pardo_et_al_2019_color" onclick="goToSource('2000-2021','Pardo_et_al_2019', this.id)">Pardo et al., 2019</a> by one of the paper's coauthors.`,
            title: `Call Combinations Differ Among Living Elephants`,
        }],
        [{
            container: `<i>Polygon</i>, published news website`,
            contributors: `Matt Patches (author)`,
            date: `2019/06/07`,
            duration: `1774 words`,
            languages: `English`,
            links: `<li><a href="https://www.polygon.com/2019/6/7/18648048/godzilla-king-of-monsters-post-credits-ending-kong-woolly-mammoth-interview" target="_blank">From publisher</a>`,
            location: `N/A`,
            medium: `Digitally published news article`,
            publisher: `Polygon`,                
            summary: `An interview with <i>Godzilla: King of the Monsters</i> (2019) director Michael Dougherty, in which he says that Behemoth's design was heavily inspired by woolly mammoths.`,
            title: `An incredibly spoilery conversation with Godzilla: King of Monsters director Mike Dougherty`,
        }],  
        [{
            container: `<i>The IUCN Red List of Threatened Species</i>, digitally published scientific database`,
            contributors: `C. Williams (coauthor, reviewer, facilitator, compiler); S.K. Tiwari (coauthor, facilitator, compiler); V.R. Goswami (coauthor); S. de Silva (coauthor); A. Kumar (coauthor); N. Baskaran (coauthor); K. Yoganand (coauthor); V. Menon (coauthor); T.N.C. Vidya (reviewer); B. Goossens (reviewer)`,
            date: `2019/09/18`,
            duration: `29 pp.`,
            languages: `English`,
            links: `<li><a href="https://dx.doi.org/10.2305/IUCN.UK.2020-3.RLTS.T7140A45818198.en" target="_blank">From publisher (DOI: 10.2305/IUCN.UK.2020-3.RLTS.T7140A45818198.en)</a>`,
            location: `N/A`,
            medium: `Digitally published article`,
            publisher: `International Union for Conservation of Nature (IUCN)`,
            summary: `TBA.`,
            title: `<i>Elephas maximus</i>, Asian elephant`,
        }],  
        [{
            container: `<i>Primates</i>, digitally published academic journal`,
            contributors: `Shifra Z. Goldenberg (coauthor); George Wittemyer (coauthor)`,
            date: `2019/11/11`,
            duration: `pp. 119-128`,
            eyedee: `Goldenberg_Wittemyer_2019`,
            iteration: `Vol. 61`,
            languages: `English`,
            links: `<li><a href="https://doi.org/10.1007/s10329-019-00766-5" target="_blank">From publisher (DOI: 10.1007/s10329-019-00766-5)</a>`,
            location: `N/A`,
            medium: `Digitally published academic journal article`,              
            publisher: `SpringerLink`,
            summary: `TBA.`,
            title: `Elephant behavior toward the dead: A review and insights from field observations`,
        }],
        [{   
            container: `<i>Pokémon Trading Card Game (TCG): Sword and Shield — Darkness Ablaze</i>, physically published trading card game expansion`,
            contributors: `Kouki Saito (illustrator)`,
            date: `<li>Japanese copy: 2020/06/05 (ムゲンゾーン, 2020)<li>English copy: 2020/08/14 (Sword & Shield, 2020)`,
            duration: `6.3 x 8.8 cm (2.5 x 3.5 in)`,
            iteration:`<li>Japanese copy: No. 134/190<li>English copy: No. 132/189`,
            languages: `Japanese, English`,
            links: `<li><a href="https://www.pokemon-card.com/card-search/details.php/card/38779/regu/XY" target="_blank">Japanese copy from publisher</a><li><a href="https://bulbapedia.bulbagarden.net/wiki/File:CopperajahDarknessAblaze132.jpg" target="_blank">Japanese copy from Bulbapedia</a>, copy provided by Ruixiang95<li><a href="https://www.pokemon.com/us/pokemon-tcg/pokemon-cards/ss-series/swsh3/132/" target="_blank">English copy from publisher</a><li><a href="https://pkmncards.com/card/copperajah-darkness-ablaze-daa-132/" target="_blank">English copy from PkmnCards</a><li><a href="https://www.serebii.net/card/darknessablaze/132.shtml" target="_blank">English copy from Serebii.net</a>`,
            location: `N/A`,
            medium: `Physically published trading card, digitized`,
            publisher: `The Pokémon Company`,
            references:`<p class="refs">ムゲンゾーン (2020). <i>ポケモンカードゲーム</i>. <a href="https://www.pokemon-card.com/ex/s3/" target="_blank">https://www.pokemon-card.com/ex/s3/</a></p><p class="refs"">Sword & Shield—Darkness Ablaze (2020). <i>The Official Pokémon Website</i>. <a href="https://www.pokemon.com/us/pokemon-tcg/sword-shield-darkness-ablaze/explore-and-watch/" target="_blank">https://www.pokemon.com/us/pokemon-tcg/sword-shield-darkness-ablaze/explore-and-watch/</a></p>`,
            summary: `TBA.`,
            title: `Copperajah`,
        }],
        [{
            container: `<i>IUCN News</i>, published news website`,
            contributors: `IUCN SSC African Elephant Specialist Group (author)`,
            date: `2020/07/20`,
            duration: `1 p.`,
            languages: `English`,
            links: `<li><a href="https://www.iucn.org/news/species-survival-commission/202007/statement-iucn-ssc-african-elephant-specialist-group-elephant-deaths-botswana" target="_blank">From publisher</a>`,
            location: `Nairobi, Kenya`,
            medium: `Digitally published news article`,
            publisher: `International Union for Conservation of Nature (IUCN)`,
            summary: `TBA.`,
            title: `Statement of the IUCN SSC African Elephant Specialist Group on elephant deaths in Botswana`,
        }],
        [{
            container: `<i>Wikipedia</i>, published website`,
            contributors: `Elephant940 (compiler)`,
            date: `Created 2020/12/29, last updated 2021/03/01`,
            duration: `389 Wikipedia articles`,
            languages: `English`,
            links: `<li><a href="https://en.wikipedia.org/wiki/User:Elephant940/Books/Elephants" target="_blank">From publisher</a>`,
            location: `N/A`,
            medium: `Published webpage`,
            publisher: `Wikimedia Foundation`,
            summary: `A comprehensive list of English Wikipedia articles relating to probsocideans.`,
            title: `User:Elephant940/Books/Elephants`,
        }],
        [{
            container: `<i>A Moment of Science</i>, published radio program`,
            contributors: `Paul Patton (author)`,
            date: `2021/02/08`,
            duration: `<li>Article: 261 words <li>Radio segment: 2 min`,
            eyedee: `Patton_2021`,
            languages: `English`,
            links: `<li><a href="https://indianapublicmedia.org/amomentofscience/do-elephants-grieve-their-dead.php" target="_blank">From publisher</a>`,
            location: `Bloomington, Indiana, United States of America`,
            medium: `Digitally published news article and radio segment`,
            publisher: `Indiana Public Media`,
            summary: `A laymen-oriented summary of <a id="Goldenberg_Wittemyer_2019_color" onclick="goToSource('2000-2021','Goldenberg_Wittemyer_2019', this.id)">Goldenberg and Wittemyer, 2019</a>.`,
            title: `Do Elephants Grieve Their Dead?`,
        }]
]